### ISSUE TITLE
EDTA docker version

### ISSUE THREAD

**Issue by brettChapman** [oushujun/EDTA#105]
Hi, after about 2 weeks of running EDTA.pl I've come across these errors:

```
2020-08-27 04:48:03,766 -WARNING- exit code 1 for CMD 'hmmscan --notextw -E 0.01 --domE 0.01 --noali --domtblout ./tmp/chunk_aaseq.1.fasta.domtbl /opt/conda/lib/python3.7/site-packages/TEsorter/database/REXdb_protein_database_viridiplantae_v3.0_plus_metazoa_v3.hmm ./tmp/chunk_aaseq.1.fasta'
2020-08-27 04:48:03,766 -WARNING- 
	STDOUT:
b''
	STDERR:
b'\nError: Failed to open binary auxfiles for /opt/conda/lib/python3.7/site-packages/TEsorter/database/REXdb_protein_database_viridiplantae_v3.0_plus_metazoa_v3.hmm: use hmmpress first\n\n'

.....

.....

b'\nError: Failed to open binary auxfiles for /opt/conda/lib/python3.7/site-packages/TEsorter/database/REXdb_protein_database_viridiplantae_v3.0_plus_metazoa_v3.hmm: use hmmpress first\n\n'


Traceback (most recent call last):
  File "/opt/conda/bin/TEsorter", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/TEsorter/app.py", line 976, in main
    pipeline(Args())
  File "/opt/conda/lib/python3.7/site-packages/TEsorter/app.py", line 164, in pipeline
    maxeval = args.max_evalue,
  File "/opt/conda/lib/python3.7/site-packages/TEsorter/app.py", line 884, in LTRlibAnn
    hmmscan_pp(aaSeq, hmmdb=DB[hmmdb], hmmout=domtbl, tmpdir=tmpdir, processors=processors)
  File "/opt/conda/lib/python3.7/site-packages/TEsorter/app.py", line 860, in hmmscan_pp
    for line in open(domtbl_file):
FileNotFoundError: [Errno 2] No such file or directory: './tmp/chunk_aaseq.1.fasta.domtbl'

Input not found!
perl rename_RM_TE.pl RM_*/consensi.fa.classified > RepeatModeler.TE.raw.fa at /opt/conda/share/EDTA/util/rename_RM_TE.pl line 19.
				RepeatModeler is finished, but no consensi.fa.classified files found.

				Skipping the CDS cleaning step (--cds [File]) since no CDS file is provided or it's empty.

Thu Aug 27 05:56:34 UTC 2020	EDTA final stage finished! You may check out:
				The final EDTA TE library: felCat5.fna.mod.EDTA.TElib.fa
Thu Aug 27 05:56:34 UTC 2020	Perform post-EDTA analysis for whole-genome annotation:

Thu Aug 27 05:56:34 UTC 2020	Homology-based annotation of TEs using felCat5.fna.mod.EDTA.TElib.fa from scratch.
```

I first ran ltr, helitron and tir, before running EDTA.pl. I installed EDTA like so and ran from singularity:
```
singularity pull docker://kapeel/edta:latest
```
I'm running all commands through the Singularity *.sif container, binding my working directory like so:

```
srun -n 1 singularity exec --bind ${PWD}:${PWD} ${EDTA_IMAGE} EDTA.pl --threads 16 --overwrite 0 --genome felCat5.fna --sensitive 1 --anno 1 --evaluate 1
```

I've attached the complete stdout with included errors.

Thanks.

[EDTA_errors.txt](https://github.com/oushujun/EDTA/files/5134453/EDTA_errors.txt)

**Comment by oushujun** [comment]
Hi,

Your previous steps look fine with me. Something is wrong with TEsorter. Maybe you can test run TEsorter on the RepeatModeler library? Its location is `*mod.EDTA.final/RM*/consensi.fa`. If possible, please use the conda version which is usually newer than the singularity version.

Best,
Shujun

**Comment by brettChapman** [comment]
Hi

I tried running TEsorter with consensi.fa and received the following errors:

```
singularity exec --bind /data/EDTA_analysis_testing:/data/EDTA_analysis_testing /data/edta_builds/edta_latest.sif TEsorter consensi.fa
2020-08-31 01:43:41,431 -WARNING- Grid computing is not available because DRMAA not configured properly: Could not find drmaa library.  Please specify its full path using the environment variable DRMAA_LIBRARY_PATH
2020-08-31 01:43:41,464 -INFO- No DRMAA, Switching to local/cluster mode.
2020-08-31 01:43:41,473 -INFO- VARS: {'sequence': 'consensi.fa', 'hmm_database': 'rexdb', 'seq_type': 'nucl', 'prefix': 'consensi.fa.rexdb', 'force_write_hmmscan': False, 'processors': 4, 'tmp_dir': './tmp', 'min_coverage': 20, 'max_evalue': 0.001, 'disable_pass2': False, 'pass2_rule': '80-80-80', 'no_library': False, 'no_reverse': False, 'no_cleanup': False, 'p2_identity': 80.0, 'p2_coverage': 80.0, 'p2_length': 80.0}
2020-08-31 01:43:41,473 -INFO- checking dependencies:
2020-08-31 01:43:41,492 -INFO- hmmer	3.3	OK
2020-08-31 01:43:41,880 -INFO- blastn	2.9.0+	OK
2020-08-31 01:43:41,881 -INFO- check database rexdb
2020-08-31 01:43:41,881 -INFO- db path: /opt/conda/lib/python3.7/site-packages/TEsorter/database
2020-08-31 01:43:41,881 -INFO- db file: REXdb_protein_database_viridiplantae_v3.0_plus_metazoa_v3.hmm
2020-08-31 01:43:41,881 -INFO- db REXdb_protein_database_viridiplantae_v3.0_plus_metazoa_v3.hmm not yet ready, building db!
failed to open SSI index /opt/conda/lib/python3.7/site-packages/TEsorter/database/REXdb_protein_database_viridiplantae_v3.0_plu
2020-08-31 01:43:41,886 -INFO- 
2020-08-31 01:43:41,886 -INFO- Start classifying pipeline
2020-08-31 01:43:41,900 -INFO- total 569 sequences
2020-08-31 01:43:41,900 -INFO- translating `consensi.fa` in six frames
/opt/conda/lib/python3.7/site-packages/Bio/Seq.py:2859: BiopythonWarning: Partial codon, len(sequence) not a multiple of three. Explicitly trim the sequence or add trailing N before translation. This may become an error in future.
  BiopythonWarning,
2020-08-31 01:43:42,422 -INFO- HMM scanning against `/opt/conda/lib/python3.7/site-packages/TEsorter/database/REXdb_protein_database_viridiplantae_v3.0_plus_metazoa_v3.hmm`
2020-08-31 01:43:42,459 -INFO- Creating server instance (pp-1.6.4.4)
2020-08-31 01:43:42,459 -INFO- Running on Python 3.7.6 linux
2020-08-31 01:43:42,660 -INFO- pp local server started with 4 workers
2020-08-31 01:43:42,689 -INFO- Task 0 started
2020-08-31 01:43:42,689 -INFO- Task 1 started
2020-08-31 01:43:42,690 -INFO- Task 2 started
2020-08-31 01:43:42,690 -INFO- Task 3 started
2020-08-31 01:43:42,714 -WARNING- exit code 1 for CMD 'hmmscan --notextw -E 0.01 --domE 0.01 --noali --domtblout ./tmp/chunk_aaseq.1.fasta.domtbl /opt/conda/lib/python3.7/site-packages/TEsorter/database/REXdb_protein_database_viridiplantae_v3.0_plus_metazoa_v3.hmm ./tmp/chunk_aaseq.1.fasta'
2020-08-31 01:43:42,715 -WARNING- 
	STDOUT:
b''
	STDERR:
b'\nError: Failed to open binary auxfiles for /opt/conda/lib/python3.7/site-packages/TEsorter/database/REXdb_protein_database_viridiplantae_v3.0_plus_metazoa_v3.hmm: use hmmpress first\n\n'


2020-08-31 01:43:42,715 -WARNING- exit code 1 for CMD 'hmmscan --notextw -E 0.01 --domE 0.01 --noali --domtblout ./tmp/chunk_aaseq.2.fasta.domtbl /opt/conda/lib/python3.7/site-packages/TEsorter/database/REXdb_protein_database_viridiplantae_v3.0_plus_metazoa_v3.hmm ./tmp/chunk_aaseq.2.fasta'
2020-08-31 01:43:42,715 -WARNING- 
	STDOUT:
b''
	STDERR:
b'\nError: Failed to open binary auxfiles for /opt/conda/lib/python3.7/site-packages/TEsorter/database/REXdb_protein_database_viridiplantae_v3.0_plus_metazoa_v3.hmm: use hmmpress first\n\n'


2020-08-31 01:43:42,715 -WARNING- exit code 1 for CMD 'hmmscan --notextw -E 0.01 --domE 0.01 --noali --domtblout ./tmp/chunk_aaseq.3.fasta.domtbl /opt/conda/lib/python3.7/site-packages/TEsorter/database/REXdb_protein_database_viridiplantae_v3.0_plus_metazoa_v3.hmm ./tmp/chunk_aaseq.3.fasta'
2020-08-31 01:43:42,715 -WARNING- 
	STDOUT:
b''
	STDERR:
b'\nError: Failed to open binary auxfiles for /opt/conda/lib/python3.7/site-packages/TEsorter/database/REXdb_protein_database_viridiplantae_v3.0_plus_metazoa_v3.hmm: use hmmpress first\n\n'


2020-08-31 01:43:42,715 -WARNING- exit code 1 for CMD 'hmmscan --notextw -E 0.01 --domE 0.01 --noali --domtblout ./tmp/chunk_aaseq.4.fasta.domtbl /opt/conda/lib/python3.7/site-packages/TEsorter/database/REXdb_protein_database_viridiplantae_v3.0_plus_metazoa_v3.hmm ./tmp/chunk_aaseq.4.fasta'
2020-08-31 01:43:42,715 -WARNING- 
	STDOUT:
b''
	STDERR:
b'\nError: Failed to open binary auxfiles for /opt/conda/lib/python3.7/site-packages/TEsorter/database/REXdb_protein_database_viridiplantae_v3.0_plus_metazoa_v3.hmm: use hmmpress first\n\n'


Traceback (most recent call last):
  File "/opt/conda/bin/TEsorter", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/TEsorter/app.py", line 976, in main
    pipeline(Args())
  File "/opt/conda/lib/python3.7/site-packages/TEsorter/app.py", line 164, in pipeline
    maxeval = args.max_evalue,
  File "/opt/conda/lib/python3.7/site-packages/TEsorter/app.py", line 884, in LTRlibAnn
    hmmscan_pp(aaSeq, hmmdb=DB[hmmdb], hmmout=domtbl, tmpdir=tmpdir, processors=processors)
  File "/opt/conda/lib/python3.7/site-packages/TEsorter/app.py", line 860, in hmmscan_pp
    for line in open(domtbl_file):
FileNotFoundError: [Errno 2] No such file or directory: './tmp/chunk_aaseq.1.fasta.domtbl'
```

If I try to install from conda and resume running EDTA.pl with ```--overwrite 0```, will it pick up that it needs to rerun TEsorter? EDTA.pl is currently still running, having skipped over TEsorter and is now running RepeatModeler and RepeatMasker. If I kill it now, and rerun with the conda version, will it reuse previously generated files or will it run EDTA.pl from the beginning again? Thanks.

**Comment by oushujun** [comment]
Hello,

The program will retain existing raw results (LTR, TIR, Helitron). If there
is RepeatMasker .out file of the genome available, it will also be
retained too. Other results will be overwritten disregard the --overwrite
parameter because those steps are relatively fast. TEsorter is used to
partially remove misclassified sequences. If it's not executed correctly,
the outcome will contain more misclassification but the execution of the
program probably won't be interrupted, that's why you are seeing
RepeatMasker and RepeatModeler are still running. You may kill them and
resume EDTA.

Shujun

**Comment by brettChapman** [comment]
Thanks.

I usually install all my tools through Docker and Singularity.

Would installing EDTA through Docker based on this Dockerfile result in the most up-to-date installation? https://hub.docker.com/r/kapeel/edta/dockerfile

I've tried installing conda packages before within a Dockerfile, first miniconda, and then conda install, but it's always ended up in permission errors due to where the binaries are accessible from. I managed to get around it in one case before, because a yaml file was provided with the package where I could set up a conda environment and compile from there.

**Comment by oushujun** [comment]
That is the correct link to the Docker/Singularity version, but it usually has a lag in terms of updates. I will push the new update to Docker soon. To avoid permission deny errors, you may reinstall your miniconda in a different location, then specify where you store your conda envs upon installation.

**Comment by brettChapman** [comment]
Hi

I've tried installing from Conda and everything seems to go smoothly. However on running EDTA.pl I get an error about RMblast not being installed in RepeatMasker.

Heres my Dockerfile:

```
FROM continuumio/miniconda3

SHELL ["/bin/bash", "-c"]

RUN conda config --add channels defaults
RUN conda config --add channels bioconda
RUN conda config --add channels conda-forge
RUN conda config --add channels r

RUN conda create -n EDTA
RUN conda install -c bioconda repeatmodeler mdust
RUN conda install -c bioconda edta

## Install Repeat Masker libraries steps included courtesy @wangshun1211 for contributions
RUN cd /opt && wget https://github.com/lfaino/LoReAn/raw/noIPRS/third_party/software/RepeatMasker.Libraries.tar.gz && \
    tar -zxf RepeatMasker.Libraries.tar.gz && rm -rf /opt/conda/share/RepeatMasker/Libraries && \
    mv ./Libraries /opt/conda/share/RepeatMasker/. && chmod -R 755 /opt/conda/share/RepeatMasker/Libraries && \
    rm -f RepeatMasker.Libraries.tar.gz 

RUN git clone https://github.com/oushujun/EDTA.git
RUN source activate EDTA
RUN echo "source activate EDTA" > ~/.bashrc
ENV PATH="/EDTA/:${PATH}"
```

Heres my EDTA.pl error:

```
singularity exec --bind /data/EDTA_analysis_testing:/data/EDTA_analysis_testing /data/edta_builds/edta.sif EDTA.pl --threads 16 --overwrite 0 --genome /data/EDTA_analysis_testing/felCat5.fna --sensitive 1 --anno 1 --evaluate 1

########################################################
##### Extensive de-novo TE Annotator (EDTA) v1.9.0  ####
##### Shujun Ou (shujun.ou.1@gmail.com)             ####
########################################################



Tue Sep  8 07:35:34 UTC 2020	Dependency checking:
Error: The RMblast engine is not installed in RepeatMasker!
srun: error: node-10: task 0: Exited with exit code 255
```

Theres no mention of installing RMblast within RepeatMasker in the documentation. Should I manually install RBblast and RepeatMasker, then use RepeatMasker's configure script to access the RMBlast binaries? Or is this something which should have been done automatically when installing EDTA from conda? Thanks.

**Comment by oushujun** [comment]
Hi, you don't need docker/singularity for the conda version. By creating a conda env and activate it, you can directly call out EDTA.pl from the bash ENV. Conda installs dependencies including RMblast and RepeatMasker for you automatically.

Shujun

**Comment by brettChapman** [comment]
Hi, thanks. I use Docker/Singularity for all my tools on my cluster, so I'd like to put EDTA in a Docker and Singularity container to run on my cluster.

I'll try and install again, but only rely on the conda environment to set things up within my Docker container.

**Comment by oushujun** [comment]
There is a docker/singularity version: https://hub.docker.com/r/kapeel/edta
It will be updated to v1.9.0 in a day or two. Or you may use that recipe to create your own.

**Comment by oushujun** [comment]
@brettChapman the docker/singularity version EDTA has been updated to v1.9.0: https://hub.docker.com/r/kapeel/edta

**Comment by brettChapman** [comment]
Thanks for the update.

I've also managed to setup my own Dockerfile. I then continued the EDTA.pl run from where it left off. So far no errors.

Here's my Dockerfile:

```
FROM continuumio/miniconda3

RUN conda update -n base -c defaults conda

RUN apt-get update \
        && apt-get install -y --no-install-recommends \
        build-essential \
        make \
        && rm -rf /var/lib/apt/lists/*

RUN conda config --add channels anaconda --add channels conda-forge --add channels bioconda --add channels r
RUN conda install -c bioconda -c conda-forge -y edta

ENV TERM=xterm

RUN cd /opt/conda/share/RepeatMasker/ && perl ./configure -trfbin=`which trf` -hmmerbin=`which nhmmscan` -rmblastbin=`which rmblastn`

RUN (echo y;echo o conf prerequisites_policy follow;echo o conf commit)|cpan

RUN cpan Text::Soundex
```
