### ISSUE TITLE
sum file is empty.

### ISSUE THREAD

**Issue by wyim-pgl** [oushujun/EDTA#147]
Dear Shujun,

During the annotation stage, I found the below warning and the SUM file is empty.

```
Fri Jan  8 09:45:07 PST 2021    Homology-based annotation of TEs using genome_chr.fasta.mod.EDTA.TElib.fa from scratch.

Use of uninitialized value $TE_class in pattern match (m//) at /data/gpfs/assoc/pgl/bin/EDTA/util/gff2bed.pl line 81, <GFF> line 6.
Use of uninitialized value $TE_class in concatenation (.) or string at /data/gpfs/assoc/pgl/bin/EDTA/util/gff2bed.pl line 84, <GFF> line 6.
Use of uninitialized value $TE_class in concatenation (.) or string at /data/gpfs/assoc/pgl/bin/EDTA/util/gff2bed.pl line 84, <GFF> line 9.
Use of uninitialized value $TE_class in pattern match (m//) at /data/gpfs/assoc/pgl/bin/EDTA/util/gff2bed.pl line 81, <GFF> line 13.
Use of uninitialized value $TE_class in concatenation (.) or string at /data/gpfs/assoc/pgl/bin/EDTA/util/gff2bed.pl line 84, <GFF> line 13.
Use of uninitialized value $TE_class in concatenation (.) or string at /data/gpfs/assoc/pgl/bin/EDTA/util/gff2bed.pl line 84, <GFF> line 16.
Use of uninitialized value $TE_class in pattern match (m//) at /data/gpfs/assoc/pgl/bin/EDTA/util/gff2bed.pl line 81, <GFF> line 21.
Use of uninitialized value $TE_class in concatenation (.) or string at /data/gpfs/assoc/pgl/bin/EDTA/util/gff2bed.pl line 84, <GFF> line 21.
Use of uninitialized value $TE_class in concatenation (.) or string at /data/gpfs/assoc/pgl/bin/EDTA/util/gff2bed.pl line 84, <GFF> line 24.
Use of uninitialized value $TE_class in pattern match (m//) at /data/gpfs/assoc/pgl/bin/EDTA/util/gff2bed.pl line 81, <GFF> line 31.
Use of uninitialized value $TE_class in concatenation (.) or string at /data/gpfs/assoc/pgl/bin/EDTA/util/gff2bed.pl line 84, <GFF> line 31.
Use of uninitialized value $TE_class in concatenation (.) or string at /data/gpfs/assoc/pgl/bin/EDTA/util/gff2bed.pl line 84, <GFF> line 34.
Use of uninitialized value $TE_class in pattern match (m//) at /data/gpfs/assoc/pgl/bin/EDTA/util/gff2bed.pl line 81, <GFF> line 37.
Use of uninitialized value $TE_class in concatenation (.) or string at /data/gpfs/assoc/pgl/bin/EDTA/util/gff2bed.pl line 84, <GFF> line 37.

```

By using buildSummary.pl script to regenerate error, I found that mod.EDTA.TEanno.out has some fault in the last column (superfamily). Some lines didn't have superfamily followed by TE ID. In fasta file header it has the ID.  Do you have any solution for this?

```
10000 0.001 0.001 0.001 MC_Chr7 7953643 7954298 NA . TE_00005169
10000 0.001 0.001 0.001 MC_Chr7 7989814 7990016 NA . TE_00002511
10000 0.001 0.001 0.001 MC_Chr7 7993394 7993629 NA . TE_00002511
10000 0.001 0.001 0.001 MC_Chr7 8083778 8089232 NA . TE_00004390
10000 0.001 0.001 0.001 MC_Chr7 8442076 8447449 NA . TE_00003754
10000 0.001 0.001 0.001 MC_Chr7 8556701 8556752 NA . TE_00004781
10000 0.001 0.001 0.001 MC_Chr7 8557004 8561360 NA . TE_00004781
10000 0.001 0.001 0.001 MC_Chr7 8561612 8561710 NA . TE_00004781
10000 0.001 0.001 0.001 MC_Chr7 8615191 8616513 NA . TE_00002099
10000 0.001 0.001 0.001 MC_Chr7 8628636 8628794 NA . TE_00002099
10000 0.001 0.001 0.001 MC_Chr7 8632482 8632821 NA . TE_00002099
```
![image](https://user-images.githubusercontent.com/907041/104070245-4e572400-51bb-11eb-900c-1bcf1b19e480.png)

**Comment by oushujun** [comment]
Hello @wyim-pgl,

Please try on the test files.

Did you annotate the genome from head to toe or separate it into different steps?

Shujun

**Comment by wyim-pgl** [comment]
Hi @oushujun ,
I followed the divide and conquer methods that you described in README.
Do I need to start all over ?

**Comment by wyim-pgl** [comment]
Dear @oushujun ,
This whoe message from annotation step running.

```bash
########################################################
##### Extensive de-novo TE Annotator (EDTA) v1.9.4  ####
##### Shujun Ou (shujun.ou.1@gmail.com)             ####
########################################################



Mon Jan 11 10:39:28 PST 2021	Dependency checking:
				All passed!

	A CDS file ../final_version/iceplant.cds is provided via --cds. Please make sure this is the DNA sequence of coding regions only.

Mon Jan 11 10:40:00 PST 2021	Perform post-EDTA analysis for whole-genome annotation:

Mon Jan 11 10:40:00 PST 2021	Homology-based annotation of TEs using iceplant.fasta.mod.EDTA.TElib.fa from scratch.

Use of uninitialized value $TE_class in pattern match (m//) at /data/gpfs/assoc/pgl/bin/miniconda3/envs/edta/share/EDTA/util/gff2bed.pl line 81, <GFF> line 6.
Use of uninitialized value $TE_class in concatenation (.) or string at /data/gpfs/assoc/pgl/bin/miniconda3/envs/edta/share/EDTA/util/gff2bed.pl line 84, <GFF> line 6.
Use of uninitialized value $TE_class in concatenation (.) or string at 
.
.
.
.
.
Use of uninitialized value $TE_class in concatenation (.) or string at /data/gpfs/assoc/pgl/bin/miniconda3/envs/edta/share/EDTA/util/gff2bed.pl line 84, <GFF> line 452057.

Warning: structural not found in the TE_SO database, will use the general term 'repeat_region	SO:0000657' to replace it.

Warning: structural not found in the TE_SO database, will use the general term 'repeat_region	SO:0000657' to replace it.

Warning: structural not found in the TE_SO database, will use the general term 'repeat_region	SO:0000657' to replace it.

.
.
.


Warning: structural not found in the TE_SO database, will use the general term 'repeat_region	SO:0000657' to replace it.
Mon Jan 11 11:51:43 PST 2021	TE annotation using the EDTA library has finished! Check out:
				Whole-genome TE annotation (total TE: ): iceplant.fasta.mod.EDTA.TEanno.gff3
				Whole-genome TE annotation summary: iceplant.fasta.mod.EDTA.TEanno.sum
				Low-threshold TE masking for MAKER gene annotation (masked: 17.85%): iceplant.fasta.mod.MAKER.masked

Mon Jan 11 11:51:44 PST 2021	Evaluate the level of inconsistency for whole-genome TE annotation (slow step):

Use of uninitialized value in pattern match (m//) at /data/gpfs/assoc/pgl/bin/miniconda3/envs/edta/share/EDTA/util/call_seq_by_list.pl line 88.
Use of uninitialized value $chr_pre in hash element at /data/gpfs/assoc/pgl/bin/miniconda3/envs/edta/share/EDTA/util/call_seq_by_list.pl line 90.
Use of uninitialized value $pos in pattern match (m//) at /data/gpfs/assoc/pgl/bin/miniconda3/envs/edta/share/EDTA/util/call_seq_by_list.pl line 100.
Use of uninitialized value $pos in concatenation (.) or string at /data/gpfs/assoc/pgl/bin/miniconda3/envs/edta/share/EDTA/util/call_seq_by_list.pl line 103.
ERROR: Can not recognize this MSU position in the list!
ERROR: TE annotation stats results not found in iceplant.fasta.mod.EDTA.TE.fa.stat!

```

**Comment by wyim-pgl** [comment]
This is a message from the test data set. I don't know what's wrong in here. Because I successfully finished EDTA with other genomes previously.


```
EDTA.pl --genome genome.fa --cds genome.cds.fa --curatedlib ../database/rice6.9.5.liban --exclude genome.exclude.bed --overwrite 1 --sensitive 1 --anno 1 --evaluate 1 --threads 10

########################################################
##### Extensive de-novo TE Annotator (EDTA) v1.9.4  ####
##### Shujun Ou (shujun.ou.1@gmail.com)             ####
########################################################



Mon Jan 11 12:58:22 PST 2021    Dependency checking:
                                All passed!

        A custom library ../database/rice6.9.5.liban is provided via --curatedlib. Please make sure this is a manually curated library but not machine generated.

        A CDS file genome.cds.fa is provided via --cds. Please make sure this is the DNA sequence of coding regions only.

        A BED file is provided via --exclude. Regions specified by this file will be excluded from TE annotation and masking.

Mon Jan 11 12:58:50 PST 2021    Obtain raw TE libraries using various structure-based programs:
Mon Jan 11 12:58:50 PST 2021    EDTA_raw: Check dependencies, prepare working directories.

Mon Jan 11 12:59:15 PST 2021    Start to find LTR candidates.

Mon Jan 11 12:59:15 PST 2021    Identify LTR retrotransposon candidates from scratch.

Warning: LOC list genome.fa.mod.ltrTE.veryfalse is empty.
Mon Jan 11 13:00:48 PST 2021    Finish finding LTR candidates.

Mon Jan 11 13:00:48 PST 2021    Start to find TIR candidates.

Mon Jan 11 13:00:48 PST 2021    Identify TIR candidates from scratch.

Species: others
Mon Jan 11 13:02:08 PST 2021    Finish finding TIR candidates.

Mon Jan 11 13:02:08 PST 2021    Start to find Helitron candidates.

Mon Jan 11 13:02:08 PST 2021    Identify Helitron candidates from scratch.

Mon Jan 11 13:02:41 PST 2021    Finish finding Helitron candidates.

Mon Jan 11 13:02:41 PST 2021    Execution of EDTA_raw.pl is finished!

Mon Jan 11 13:02:41 PST 2021    Obtain raw TE libraries finished.
                                All intact TEs found by EDTA:
                                        genome.fa.mod.EDTA.intact.fa
                                        genome.fa.mod.EDTA.intact.gff3

Mon Jan 11 13:02:41 PST 2021    Perform EDTA advcance filtering for raw TE candidates and generate the stage 1 library:




Mon Jan 11 13:06:03 PST 2021    EDTA advcance filtering finished.

Mon Jan 11 13:06:03 PST 2021    Perform EDTA final steps to generate a non-redundant comprehensive TE library:

                                Use RepeatModeler to identify any remaining TEs that are missed by structure-based methods.

2021-01-11 13:07:06,044 -WARNING- Grid computing is not available because DRMAA not configured properly: Could not find drmaa library.  Please specify its full path using the environment variable DRMAA_LIBRARY_PATH
2021-01-11 13:07:06,044 -INFO- No DRMAA, Switching to local/cluster mode.
2021-01-11 13:07:06,089 -INFO- VARS: {'sequence': 'genome.fa.mod.RM.consensi.fa', 'hmm_database': 'rexdb', 'seq_type': 'nucl', 'prefix': 'genome.fa.mod.RM.consensi.fa.rexdb', 'force_write_hmmscan': False, 'processors': 10, 'tmp_dir': './tmp', 'min_coverage': 20, 'max_evalue': 0.001, 'disable_pass2': False, 'pass2_rule': '80-80-80', 'no_library': False, 'no_reverse': False, 'no_cleanup': False, 'p2_identity': 80.0, 'p2_coverage': 80.0, 'p2_length': 80.0}
2021-01-11 13:07:06,089 -INFO- checking dependencies:
2021-01-11 13:07:06,152 -INFO- hmmer    3.3     OK
2021-01-11 13:07:06,219 -INFO- blastn   2.9.0+  OK
2021-01-11 13:07:06,219 -INFO- check database rexdb
2021-01-11 13:07:06,219 -INFO- db path: /data/gpfs/assoc/pgl/bin/miniconda3/envs/edta/lib/python3.6/site-packages/TEsorter/database
2021-01-11 13:07:06,219 -INFO- db file: REXdb_protein_database_viridiplantae_v3.0_plus_metazoa_v3.hmm
2021-01-11 13:07:06,220 -INFO- REXdb_protein_database_viridiplantae_v3.0_plus_metazoa_v3.hmm    OK
2021-01-11 13:07:06,220 -INFO- Start classifying pipeline
2021-01-11 13:07:06,430 -INFO- total 1 sequences
2021-01-11 13:07:06,430 -INFO- translating `genome.fa.mod.RM.consensi.fa` in six frames
/data/gpfs/home/wyim/scratch/bin/miniconda3/envs/edta/lib/python3.6/site-packages/Bio/Seq.py:2859: BiopythonWarning: Partial codon, len(sequence) not a multiple of three. Explicitly trim the sequence or add trailing N before translation. This may become an error in future.
  BiopythonWarning,
2021-01-11 13:07:06,451 -INFO- HMM scanning against `/data/gpfs/assoc/pgl/bin/miniconda3/envs/edta/lib/python3.6/site-packages/TEsorter/database/REXdb_protein_database_viridiplantae_v3.0_plus_metazoa_v3.hmm`
2021-01-11 13:07:06,454 -INFO- Creating server instance (pp-1.6.4.4)
2021-01-11 13:07:06,454 -INFO- Running on Python 3.6.10 linux
2021-01-11 13:07:07,343 -INFO- pp local server started with 10 workers
2021-01-11 13:07:07,450 -INFO- Task 0 started
2021-01-11 13:07:07,451 -INFO- Task 1 started
2021-01-11 13:07:07,451 -INFO- Task 2 started
2021-01-11 13:07:07,452 -INFO- Task 3 started
2021-01-11 13:07:07,452 -INFO- Task 4 started
2021-01-11 13:07:07,452 -INFO- Task 5 started
2021-01-11 13:07:07,453 -INFO- Task 6 started
2021-01-11 13:07:07,453 -INFO- Task 7 started
2021-01-11 13:07:07,453 -INFO- Task 8 started
2021-01-11 13:07:07,454 -INFO- Task 9 started
2021-01-11 13:07:07,670 -WARNING- exit code 1 for CMD 'hmmscan --notextw -E 0.01 --domE 0.01 --noali --domtblout ./tmp/chunk_aaseq.7.fasta.domtbl /data/gpfs/assoc/pgl/bin/miniconda3/envs/edta/lib/python3.6/site-packages/TEsorter/database/REXdb_protein_database_viridiplantae_v3.0_plus_metazoa_v3.hmm ./tmp/chunk_aaseq.7.fasta'
2021-01-11 13:07:07,670 -WARNING-
        STDOUT:
b''
        STDERR:
b'\nError: Sequence file ./tmp/chunk_aaseq.7.fasta is empty or misformatted\n\n'


2021-01-11 13:07:07,670 -WARNING- exit code 1 for CMD 'hmmscan --notextw -E 0.01 --domE 0.01 --noali --domtblout ./tmp/chunk_aaseq.8.fasta.domtbl /data/gpfs/assoc/pgl/bin/miniconda3/envs/edta/lib/python3.6/site-packages/TEsorter/database/REXdb_protein_database_viridiplantae_v3.0_plus_metazoa_v3.hmm ./tmp/chunk_aaseq.8.fasta'
2021-01-11 13:07:07,670 -WARNING-
        STDOUT:
b''
        STDERR:
b'\nError: Sequence file ./tmp/chunk_aaseq.8.fasta is empty or misformatted\n\n'


2021-01-11 13:07:07,670 -WARNING- exit code 1 for CMD 'hmmscan --notextw -E 0.01 --domE 0.01 --noali --domtblout ./tmp/chunk_aaseq.9.fasta.domtbl /data/gpfs/assoc/pgl/bin/miniconda3/envs/edta/lib/python3.6/site-packages/TEsorter/database/REXdb_protein_database_viridiplantae_v3.0_plus_metazoa_v3.hmm ./tmp/chunk_aaseq.9.fasta'
2021-01-11 13:07:07,670 -WARNING-
        STDOUT:
b''
        STDERR:
b'\nError: Sequence file ./tmp/chunk_aaseq.9.fasta is empty or misformatted\n\n'


2021-01-11 13:07:07,670 -WARNING- exit code 1 for CMD 'hmmscan --notextw -E 0.01 --domE 0.01 --noali --domtblout ./tmp/chunk_aaseq.10.fasta.domtbl /data/gpfs/assoc/pgl/bin/miniconda3/envs/edta/lib/python3.6/site-packages/TEsorter/database/REXdb_protein_database_viridiplantae_v3.0_plus_metazoa_v3.hmm ./tmp/chunk_aaseq.10.fasta'
2021-01-11 13:07:07,670 -WARNING-
        STDOUT:
b''
        STDERR:
b'\nError: Sequence file ./tmp/chunk_aaseq.10.fasta is empty or misformatted\n\n'


Traceback (most recent call last):
  File "/data/gpfs/home/wyim/scratch/bin/miniconda3/envs/edta/bin/TEsorter", line 10, in <module>
    sys.exit(main())
  File "/data/gpfs/home/wyim/scratch/bin/miniconda3/envs/edta/lib/python3.6/site-packages/TEsorter/app.py", line 976, in main
    pipeline(Args())
  File "/data/gpfs/home/wyim/scratch/bin/miniconda3/envs/edta/lib/python3.6/site-packages/TEsorter/app.py", line 164, in pipeline
    maxeval = args.max_evalue,
  File "/data/gpfs/home/wyim/scratch/bin/miniconda3/envs/edta/lib/python3.6/site-packages/TEsorter/app.py", line 884, in LTRlibAnn
    hmmscan_pp(aaSeq, hmmdb=DB[hmmdb], hmmout=domtbl, tmpdir=tmpdir, processors=processors)
  File "/data/gpfs/home/wyim/scratch/bin/miniconda3/envs/edta/lib/python3.6/site-packages/TEsorter/app.py", line 860, in hmmscan_pp
    for line in open(domtbl_file):
FileNotFoundError: [Errno 2] No such file or directory: './tmp/chunk_aaseq.7.fasta.domtbl'

Input not found!
perl rename_RM_TE.pl RM_*/consensi.fa.classified > RepeatModeler.TE.raw.fa at /data/gpfs/assoc/pgl/bin/miniconda3/envs/edta/share/EDTA/util/rename_RM_TE.pl line 20.

        Input file "genome.fa.mod.RepeatModeler.raw.fa.masked" not found!


        Usage: perl cleanup_tandem.pl -f sample.fa [options] > sample.cln.fa
        Options:
                -misschar       [n|l]   Define the letter representing unknown sequences; default: n. l: recognize lower case letters
                -Nscreen        [0|1]   Enable (1) or disable (0) the -nc parameter; default: 1
                -nc             [int]   Ambuguous sequence len cutoff; discard the entire sequence if > this number; default: 0
                -nr             [0-1]   Ambuguous sequence percentage cutoff; discard the entire sequence if > this number; default: 1
                -minlen         [int]   Minimum sequence length filter after clean up; default: 100 (bp)
                -maxlen         [int]   Maximum sequence length filter after clean up; default: 25000 (bp)
                -cleanN         [0|1]   Retain (0) or remove (1) the -misschar taget in output sequence; default: 0
                -cleanT         [0|1]   Remove entire seq. if any terminal seq (20bp) has 15bp of N (1); disabled by default (0).
                -minrm          [int]   The minimum length of -misschar to be removed if -cleanN 1; default: 1.
                -trf            [0|1]   Enable (1) or disable (0) tandem repeat finder (trf); default: 1
                -trf_path       path    Path to the trf program

Mon Jan 11 13:07:43 PST 2021    Clean up TE-related sequences in the CDS file with TEsorter:

2021-01-11 13:07:44,027 -WARNING- Grid computing is not available because DRMAA not configured properly: Could not find drmaa library.  Please specify its full path using the environment variable DRMAA_LIBRARY_PATH
2021-01-11 13:07:44,027 -INFO- No DRMAA, Switching to local/cluster mode.
2021-01-11 13:07:44,032 -INFO- VARS: {'sequence': 'genome.cds.fa.code', 'hmm_database': 'rexdb', 'seq_type': 'nucl', 'prefix': 'genome.cds.fa.code.rexdb', 'force_write_hmmscan': False, 'processors': 10, 'tmp_dir': './tmp', 'min_coverage': 20, 'max_evalue': 0.001, 'disable_pass2': False, 'pass2_rule': '80-80-80', 'no_library': False, 'no_reverse': False, 'no_cleanup': False, 'p2_identity': 80.0, 'p2_coverage': 80.0, 'p2_length': 80.0}
2021-01-11 13:07:44,032 -INFO- checking dependencies:
2021-01-11 13:07:44,043 -INFO- hmmer    3.3     OK
2021-01-11 13:07:44,109 -INFO- blastn   2.9.0+  OK
2021-01-11 13:07:44,109 -INFO- check database rexdb
2021-01-11 13:07:44,109 -INFO- db path: /data/gpfs/assoc/pgl/bin/miniconda3/envs/edta/lib/python3.6/site-packages/TEsorter/database
2021-01-11 13:07:44,109 -INFO- db file: REXdb_protein_database_viridiplantae_v3.0_plus_metazoa_v3.hmm
2021-01-11 13:07:44,110 -INFO- REXdb_protein_database_viridiplantae_v3.0_plus_metazoa_v3.hmm    OK
2021-01-11 13:07:44,110 -INFO- Start classifying pipeline
2021-01-11 13:07:44,120 -INFO- total 139 sequences
2021-01-11 13:07:44,120 -INFO- translating `genome.cds.fa.code` in six frames
/data/gpfs/home/wyim/scratch/bin/miniconda3/envs/edta/lib/python3.6/site-packages/Bio/Seq.py:2859: BiopythonWarning: Partial codon, len(sequence) not a multiple of three. Explicitly trim the sequence or add trailing N before translation. This may become an error in future.
  BiopythonWarning,
2021-01-11 13:07:44,405 -INFO- HMM scanning against `/data/gpfs/assoc/pgl/bin/miniconda3/envs/edta/lib/python3.6/site-packages/TEsorter/database/REXdb_protein_database_viridiplantae_v3.0_plus_metazoa_v3.hmm`
2021-01-11 13:07:44,420 -INFO- Creating server instance (pp-1.6.4.4)
2021-01-11 13:07:44,420 -INFO- Running on Python 3.6.10 linux
2021-01-11 13:07:45,232 -INFO- pp local server started with 10 workers
2021-01-11 13:07:45,263 -INFO- Task 0 started
2021-01-11 13:07:45,264 -INFO- Task 1 started
2021-01-11 13:07:45,265 -INFO- Task 2 started
2021-01-11 13:07:45,265 -INFO- Task 3 started
2021-01-11 13:07:45,266 -INFO- Task 4 started
2021-01-11 13:07:45,267 -INFO- Task 5 started
2021-01-11 13:07:45,267 -INFO- Task 6 started
2021-01-11 13:07:45,268 -INFO- Task 7 started
2021-01-11 13:07:45,268 -INFO- Task 8 started
2021-01-11 13:07:45,269 -INFO- Task 9 started
2021-01-11 13:07:48,006 -INFO- generating gene anntations
2021-01-11 13:07:48,017 -INFO- 2 sequences classified by HMM
2021-01-11 13:07:48,017 -INFO- see protein domain sequences in `genome.cds.fa.code.rexdb.dom.faa` and annotation gff3 file in `genome.cds.fa.code.rexdb.dom.gff3`
2021-01-11 13:07:48,017 -INFO- classifying the unclassified sequences by searching against the classified ones
2021-01-11 13:07:48,024 -INFO- using the 80-80-80 rule
2021-01-11 13:07:48,024 -INFO- run CMD: `makeblastdb -in ./tmp/pass1_classified.fa -dbtype nucl`
2021-01-11 13:07:48,075 -INFO- run CMD: `blastn -query ./tmp/pass1_unclassified.fa -db ./tmp/pass1_classified.fa -out ./tmp/pass1_unclassified.fa.blastout -outfmt '6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore qlen slen qcovs qcovhsp sstrand' -num_threads 10`
2021-01-11 13:07:48,228 -INFO- 1 sequences classified in pass 2
2021-01-11 13:07:48,228 -INFO- total 3 sequences classified.
2021-01-11 13:07:48,228 -INFO- see classified sequences in `genome.cds.fa.code.rexdb.cls.tsv`
2021-01-11 13:07:48,228 -INFO- writing library for RepeatMasker in `genome.cds.fa.code.rexdb.cls.lib`
2021-01-11 13:07:48,235 -INFO- writing classified protein domains in `genome.cds.fa.code.rexdb.cls.pep`
2021-01-11 13:07:48,235 -INFO- Summary of classifications:
Order           Superfamily      # of Sequences# of Clade Sequences    # of Clades# of full Domains
LTR             Gypsy                         1              1              1              0
Maverick        unknown                       2              0              0              0
2021-01-11 13:07:48,235 -INFO- Pipeline done.
2021-01-11 13:07:48,236 -INFO- cleaning the temporary directory ./tmp
                                Remove CDS-related sequences in the EDTA library:

Mon Jan 11 13:09:33 PST 2021    Combine the high-quality TE library rice6.9.5.liban with the EDTA library:

Mon Jan 11 13:10:30 PST 2021    EDTA final stage finished! You may check out:
                                The final EDTA TE library: genome.fa.mod.EDTA.TElib.fa
                                Family names of intact TEs have been updated by rice6.9.5.liban: genome.fa.mod.EDTA.intact.gff3
                                Comparing to the provided library, EDTA found these novel TEs: genome.fa.mod.EDTA.TElib.novel.fa
                                The provided library has been incorporated into the final library: genome.fa.mod.EDTA.TElib.fa

Mon Jan 11 13:10:30 PST 2021    Perform post-EDTA analysis for whole-genome annotation:

Mon Jan 11 13:10:30 PST 2021    Homology-based annotation of TEs using genome.fa.mod.EDTA.TElib.fa from scratch.

Use of uninitialized value $TE_class in pattern match (m//) at /data/gpfs/assoc/pgl/bin/miniconda3/envs/edta/share/EDTA/util/gff2bed.pl line 81, <GFF> line 11.
Use of uninitialized value $TE_class in concatenation (.) or string at /data/gpfs/assoc/pgl/bin/miniconda3/envs/edta/share/EDTA/util/gff2bed.pl line 84, <GFF> line 11.
Use of uninitialized value $TE_class in concatenation (.) or string at /data/gpfs/assoc/pgl/bin/miniconda3/envs/edta/share/EDTA/util/gff2bed.pl line 84, <GFF> line 14.
Use of uninitialized value $TE_class in pattern match (m//) at /data/gpfs/assoc/pgl/bin/miniconda3/envs/edta/share/EDTA/util/gff2bed.pl line 81, <GFF> line 19.
Use of uninitialized value $TE_class in concatenation (.) or string at /data/gpfs/assoc/pgl/bin/miniconda3/envs/edta/share/EDTA/util/gff2bed.pl line 84, <GFF> line 19.
Use of uninitialized value $TE_class in concatenation (.) or string at /data/gpfs/assoc/pgl/bin/miniconda3/envs/edta/share/EDTA/util/gff2bed.pl line 84, <GFF> line 22.
Use of uninitialized value $TE_class in pattern match (m//) at /data/gpfs/assoc/pgl/bin/miniconda3/envs/edta/share/EDTA/util/gff2bed.pl line 81, <GFF> line 28.
Use of uninitialized value $TE_class in concatenation (.) or string at /data/gpfs/assoc/pgl/bin/miniconda3/envs/edta/share/EDTA/util/gff2bed.pl line 84, <GFF> line 28.
Use of uninitialized value $TE_class in concatenation (.) or string at /data/gpfs/assoc/pgl/bin/miniconda3/envs/edta/share/EDTA/util/gff2bed.pl line 84, <GFF> line 31.
Use of uninitialized value $TE_class in pattern match (m//) at /data/gpfs/assoc/pgl/bin/miniconda3/envs/edta/share/EDTA/util/gff2bed.pl line 81, <GFF> line 38.
Use of uninitialized value $TE_class in concatenation (.) or string at /data/gpfs/assoc/pgl/bin/miniconda3/envs/edta/share/EDTA/util/gff2bed.pl line 84, <GFF> line 38.
Use of uninitialized value $TE_class in concatenation (.) or string at /data/gpfs/assoc/pgl/bin/miniconda3/envs/edta/share/EDTA/util/gff2bed.pl line 84, <GFF> line 41.
Use of uninitialized value $TE_class in pattern match (m//) at /data/gpfs/assoc/pgl/bin/miniconda3/envs/edta/share/EDTA/util/gff2bed.pl line 81, <GFF> line 107.
Use of uninitialized value $TE_class in concatenation (.) or string at /data/gpfs/assoc/pgl/bin/miniconda3/envs/edta/share/EDTA/util/gff2bed.pl line 84, <GFF> line 107.
Use of uninitialized value $TE_class in concatenation (.) or string at /data/gpfs/assoc/pgl/bin/miniconda3/envs/edta/share/EDTA/util/gff2bed.pl line 84, <GFF> line 110.
Use of uninitialized value $TE_class in pattern match (m//) at /data/gpfs/assoc/pgl/bin/miniconda3/envs/edta/share/EDTA/util/gff2bed.pl line 81, <GFF> line 182.
Use of uninitialized value $TE_class in concatenation (.) or string at /data/gpfs/assoc/pgl/bin/miniconda3/envs/edta/share/EDTA/util/gff2bed.pl line 84, <GFF> line 182.
Use of uninitialized value $TE_class in concatenation (.) or string at /data/gpfs/assoc/pgl/bin/miniconda3/envs/edta/share/EDTA/util/gff2bed.pl line 84, <GFF> line 185.
Use of uninitialized value $TE_class in pattern match (m//) at /data/gpfs/assoc/pgl/bin/miniconda3/envs/edta/share/EDTA/util/gff2bed.pl line 81, <GFF> line 227.
Use of uninitialized value $TE_class in concatenation (.) or string at /data/gpfs/assoc/pgl/bin/miniconda3/envs/edta/share/EDTA/util/gff2bed.pl line 84, <GFF> line 227.
Use of uninitialized value $TE_class in concatenation (.) or string at /data/gpfs/assoc/pgl/bin/miniconda3/envs/edta/share/EDTA/util/gff2bed.pl line 84, <GFF> line 230.
Use of uninitialized value $TE_class in pattern match (m//) at /data/gpfs/assoc/pgl/bin/miniconda3/envs/edta/share/EDTA/util/gff2bed.pl line 81, <GFF> line 298.
Use of uninitialized value $TE_class in concatenation (.) or string at /data/gpfs/assoc/pgl/bin/miniconda3/envs/edta/share/EDTA/util/gff2bed.pl line 84, <GFF> line 298.
Use of uninitialized value $TE_class in concatenation (.) or string at /data/gpfs/assoc/pgl/bin/miniconda3/envs/edta/share/EDTA/util/gff2bed.pl line 84, <GFF> line 301.

Warning: structural not found in the TE_SO database, will use the general term 'repeat_region   SO:0000657' to replace it.

Warning: structural not found in the TE_SO database, will use the general term 'repeat_region   SO:0000657' to replace it.

Warning: structural not found in the TE_SO database, will use the general term 'repeat_region   SO:0000657' to replace it.

Warning: structural not found in the TE_SO database, will use the general term 'repeat_region   SO:0000657' to replace it.

Warning: structural not found in the TE_SO database, will use the general term 'repeat_region   SO:0000657' to replace it.
Mon Jan 11 13:11:04 PST 2021    TE annotation using the EDTA library has finished! Check out:
                                Whole-genome TE annotation (total TE: ): genome.fa.mod.EDTA.TEanno.gff3
                                Whole-genome TE annotation summary: genome.fa.mod.EDTA.TEanno.sum
                                Low-threshold TE masking for MAKER gene annotation (masked: 16.32%): genome.fa.mod.MAKER.masked

Mon Jan 11 13:11:04 PST 2021    Evaluate the level of inconsistency for whole-genome TE annotation (slow step):

Use of uninitialized value in pattern match (m//) at /data/gpfs/assoc/pgl/bin/miniconda3/envs/edta/share/EDTA/util/call_seq_by_list.pl line 88.
Use of uninitialized value $chr_pre in hash element at /data/gpfs/assoc/pgl/bin/miniconda3/envs/edta/share/EDTA/util/call_seq_by_list.pl line 90.
Use of uninitialized value $pos in pattern match (m//) at /data/gpfs/assoc/pgl/bin/miniconda3/envs/edta/share/EDTA/util/call_seq_by_list.pl line 100.
Use of uninitialized value $pos in concatenation (.) or string at /data/gpfs/assoc/pgl/bin/miniconda3/envs/edta/share/EDTA/util/call_seq_by_list.pl line 103.
ERROR: Can not recognize this MSU position in the list!
ERROR: TE annotation stats results not found in genome.fa.mod.EDTA.TE.fa.stat!
```

**Comment by oushujun** [comment]
The installation seems broken. You may try to reinstall or use this docker/singularity version: https://hub.docker.com/r/kapeel/edta

**Comment by wyim-pgl** [comment]
@oushujun  After reinstallation, sum file was generated.
My installation steps were below.
```bash
conda create -n EDTA
conda activate EDTA
conda config --env --add channels anaconda --add channels conda-forge --add channels bioconda
conda install -y cd-hit repeatmodeler muscle mdust blast openjdk perl perl-text-soundex multiprocess regex tensorflow>=1.14.0 keras>=2.2.4 scikit-learn>=0.19.0 biopython pandas glob2 python>=3.6 tesorter genericrepeatfinder genometools ltr_retriever ltr_finder
conda install -y tensorflow 'h5py<3.0.0'
```
