### ISSUE TITLE
Error in advance filtering

### ISSUE THREAD

**Issue by janetxinli** [oushujun/EDTA#149]
Hello!

I've installed `EDTA v1.9.4` via `conda` in order to create a custom repeat library before annotating eight different fungal genomes. Three of my runs have resulted in an error and no repeat library output. I ran `EDTA` with the following parameters:

```
/usr/bin/time -pv EDTA.pl --genome JB-39.pilon.fa --cds /projects/btl_scratch/janli/projects/bbassiana/data/GCA_001682635.1_ASM168263v1_cds_from_genomic.fna --sensitive 1 --anno 1 --evaluate 1 --threads 48
```

and this is the error I'm seeing, during the advanced filtering step:

```
Tue Jan 12 13:01:26 PST 2021    Obtain raw TE libraries finished.
                                All intact TEs found by EDTA:
                                        JB-39.pilon.fa.mod.EDTA.intact.fa
                                        JB-39.pilon.fa.mod.EDTA.intact.gff3

Tue Jan 12 13:01:26 PST 2021    Perform EDTA advcance filtering for raw TE candidates and generate the stage 1 library:


        Input file "JB-39.pilon.fa.mod.TIR.Helitron.fa.stg1.raw.masked" not found!


        Usage: perl cleanup_tandem.pl -f sample.fa [options] > sample.cln.fa
        Options:
                -misschar       [n|l]   Define the letter representing unknown sequences; default: n. l: recognize lower case letters
                -Nscreen        [0|1]   Enable (1) or disable (0) the -nc parameter; default: 1
                -nc             [int]   Ambuguous sequence len cutoff; discard the entire sequence if > this number; default: 0
                -nr             [0-1]   Ambuguous sequence percentage cutoff; discard the entire sequence if > this number; default: 1
                -minlen         [int]   Minimum sequence length filter after clean up; default: 100 (bp)
                -maxlen         [int]   Maximum sequence length filter after clean up; default: 25000 (bp)
                -cleanN         [0|1]   Retain (0) or remove (1) the -misschar taget in output sequence; default: 0
                -cleanT         [0|1]   Remove entire seq. if any terminal seq (20bp) has 15bp of N (1); disabled by default (0).
                -minrm          [int]   The minimum length of -misschar to be removed if -cleanN 1; default: 1.
                -trf            [0|1]   Enable (1) or disable (0) tandem repeat finder (trf); default: 1
                -trf_path       path    Path to the trf program


ERROR: Input sequence file is not exist!
```

In my other (successful) runs, I didn't receive the above error and `EDTA` was able to perform the filtering, but I received another error later down the line:

```
Tue Jan 12 13:01:22 PST 2021    EDTA advcance filtering finished.

Tue Jan 12 13:01:22 PST 2021    Perform EDTA final steps to generate a non-redundant comprehensive TE library:

                                Use RepeatModeler to identify any remaining TEs that are missed by structure-based met
hods.

Traceback (most recent call last):
  File "/projects/btl/janli/miniconda3/envs/edta/bin/TEsorter", line 6, in <module>
    from TEsorter.app import main
  File "/projects/btl/janli/miniconda3/envs/edta/lib/python3.6/site-packages/TEsorter/app.py", line 25, in <module>
    from .modules.RunCmdsMP import run_cmd, pp_run
  File "/projects/btl/janli/miniconda3/envs/edta/lib/python3.6/site-packages/TEsorter/modules/RunCmdsMP.py", line 20,
in <module>
    import drmaa    # for grid
  File "/projects/btl/janli/miniconda3/envs/edta/lib/python3.6/site-packages/drmaa/__init__.py", line 65, in <module>
    from .session import JobInfo, JobTemplate, Session
  File "/projects/btl/janli/miniconda3/envs/edta/lib/python3.6/site-packages/drmaa/session.py", line 39, in <module>
    from drmaa.helpers import (adapt_rusage, Attribute, attribute_names_iterator,
  File "/projects/btl/janli/miniconda3/envs/edta/lib/python3.6/site-packages/drmaa/helpers.py", line 36, in <module>
    from drmaa.wrappers import (drmaa_attr_names_t, drmaa_attr_values_t,
  File "/projects/btl/janli/miniconda3/envs/edta/lib/python3.6/site-packages/drmaa/wrappers.py", line 56, in <module>
    _lib = CDLL(libpath, mode=RTLD_GLOBAL)
  File "/projects/btl/janli/miniconda3/envs/edta/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/libdrmaa.so.1: cannot open shared object file: No such file or directory

Input not found!
perl rename_RM_TE.pl RM_*/consensi.fa.classified > RepeatModeler.TE.raw.fa at /projects/btl/janli/miniconda3/envs/edta
/share/EDTA/util/rename_RM_TE.pl line 20.

        Input file "JB-41.pilon.fa.mod.RepeatModeler.raw.fa.masked" not found!
```

I still got a final output for the runs with this error, but it seems like both have to do with `RepeatMasker`. Do you have any idea or suggestion as to what this error is about? 

Thanks so much!

**Comment by oushujun** [comment]
Hello,

If you have run the test files and pass, your installation should be ok. Check the sequence names.

Best,
Shujun

**Comment by janetxinli** [comment]
Hi Shujun,

My installation and sequence names should both be fine. I just tried running the intermediate `EDTA_processI.pl` script individually and printed the `RepeatMasker` stderr out, and it seems that there are no repetitive sequences being detected when using the `LTR.HQ` repeats to mask the `stg1.raw` sequences. This is why I saw the error. 

I don't know how many other people would come across this issue, but having the stderr or a more informative error message printed out would make things clearer for this step!

**Comment by oushujun** [comment]
Thank you for testing out! In this case you may proceed with `--force 1` to use rice repeats to fill in the missing parts. The rice repeat may not help to annotate your genome because of divergence, but it can help to make it through the pipeline so that you can get other repeats of your genome.

Shujun

**Comment by oushujun** [comment]
From the later errors, they suggest that the `TEsorter` is not correctly installed. You may test it out with some TE sequences using the EDTA conda env. You may also try out the latest conda recipe that comes from the current version (v1.9.6).

Shujun

**Comment by janetxinli** [comment]
Thanks for your suggestions, Shujun! I used `--force 1` and that helped with one of my annotations. I appreciate your help!
