### ISSUE TITLE
TESorter issue with Rice genome 

### ISSUE THREAD

**Issue by oliviamr** [oushujun/EDTA#170]
Hi Shunjun!

I am running some issue just right at the almost end of the finish line. I wonder if I could use some of your help to solve this. 

Thanks, 
Olivia

021-03-05 09:51:33,661 -INFO- VARS: {'sequence': 'genome.cds.fa.code', 'hmm_database': 'rexdb', 'seq_type': 'nucl', 'prefix': 'genome.cds.fa.code.rexdb', 'force_write_hmmscan': F
alse, 'processors': 16, 'tmp_dir': './tmp', 'min_coverage': 20, 'max_evalue': 0.001, 'disable_pass2': False, 'pass2_rule': '80-80-80', 'no_library': False, 'no_reverse': False, 'n
o_cleanup': False, 'p2_identity': 80.0, 'p2_coverage': 80.0, 'p2_length': 80.0}
2021-03-05 09:51:33,661 -INFO- checking dependencies:
2021-03-05 09:51:33,671 -INFO- hmmer	3.3.2	OK
2021-03-05 09:51:33,733 -INFO- blastn	2.10.0+	OK
2021-03-05 09:51:33,733 -INFO- check database rexdb
2021-03-05 09:51:33,734 -INFO- db path: ~omendivi/.conda/envs/EDTA/lib/python3.6/site-packages/TEsorter/database
2021-03-05 09:51:33,734 -INFO- db file: REXdb_protein_database_viridiplantae_v3.0_plus_metazoa_v3.hmm
2021-03-05 09:51:33,734 -INFO- REXdb_protein_database_viridiplantae_v3.0_plus_metazoa_v3.hmm	OK
2021-03-05 09:51:33,734 -INFO- Start classifying pipeline
2021-03-05 09:51:33,746 -INFO- total 2 sequences
2021-03-05 09:51:33,746 -INFO- translating `genome.cds.fa.code` in six frames
Traceback (most recent call last):
  File "~omendivi/.conda/envs/EDTA/bin/TEsorter", line 10, in <module>
    sys.exit(main())
  File "~omendivi/.conda/envs/EDTA/lib/python3.6/site-packages/TEsorter/app.py", line 1014, in main
    pipeline(Args())
  File "~omendivi/.conda/envs/EDTA/lib/python3.6/site-packages/TEsorter/app.py", line 167, in pipeline
    maxeval = args.max_evalue,
  File "~omendivi/.conda/envs/EDTA/lib/python3.6/site-packages/TEsorter/app.py", line 902, in LTRlibAnn
    aaSeq = translate(ltrlib, prefix=tmp_prefix)
  File "~omendivi/.conda/envs/EDTA/lib/python3.6/site-packages/TEsorter/app.py", line 851, in translate
    six_frame_translate(inSeq, fp)
  File "~omendivi/.conda/envs/EDTA/lib/python3.6/site-packages/TEsorter/modules/translate_seq.py", line 8, in six_frame_translate
    for seq, suffix0 in zip([rc.seq, rc.seq.reverse_complement()], ['aa', 'rev_aa']):
  File "~omendivi/.conda/envs/EDTA/lib/python3.6/site-packages/Bio/Seq.py", line 825, in reverse_complement
    return self.complement()[::-1]
  File "~omendivi/.conda/envs/EDTA/lib/python3.6/site-packages/Bio/Seq.py", line 761, in complement
    raise ValueError("Mixed RNA/DNA found")
ValueError: Mixed RNA/DNA found
cat: genome.cds.fa.code.rexdb.cls.tsv: No such file or directory
awk: fatal: cannot open file `rice_genome.fasta.mod.EDTA.raw.fa.out' for reading (No such file or directory)
awk: fatal: cannot open file `rice_genome.fasta.mod.EDTA.raw.fa.out' for reading (No such file or directory)
				Warning: No TE-related CDS found (genome.cds.fa.code.TE empty). Will not use the self-cleaning step.

	Input file "rice_genome.fasta.mod.EDTA.raw.fa.masked" not found!

        Usage: perl cleanup_tandem.pl -f sample.fa [options] > sample.cln.fa
	Options:
		-misschar	[n|l]	Define the letter representing unknown sequences; default: n. l: recognize lower case letters
		-Nscreen	[0|1]	Enable (1) or disable (0) the -nc parameter; default: 1
		-nc		[int]	Ambuguous sequence len cutoff; discard the entire sequence if > this number; default: 0
		-nr		[0-1]	Ambuguous sequence percentage cutoff; discard the entire sequence if > this number; default: 1
		-minlen		[int]	Minimum sequence length filter after clean up; default: 100 (bp)
		-maxlen		[int]	Maximum sequence length filter after clean up; default: 25000 (bp)
		-cleanN		[0|1]	Retain (0) or remove (1) the -misschar taget in output sequence; default: 0
		-cleanT		[0|1]	Remove entire seq. if any terminal seq (20bp) has 15bp of N (1); disabled by default (0).
		-minrm		[int]	The minimum length of -misschar to be removed if -cleanN 1; default: 1.
		-trf		[0|1]	Enable (1) or disable (0) tandem repeat finder (trf); default: 1
		-trf_path	path	Path to the trf program

	Input file "rice_genome.fasta.mod.EDTA.intact.fa.raw.masked" not found!

        Usage: perl cleanup_tandem.pl -f sample.fa [options] > sample.cln.fa
	Options:
		-misschar	[n|l]	Define the letter representing unknown sequences; default: n. l: recognize lower case letters
		-Nscreen	[0|1]	Enable (1) or disable (0) the -nc parameter; default: 1
		-nc		[int]	Ambuguous sequence len cutoff; discard the entire sequence if > this number; default: 0
		-nr		[0-1]	Ambuguous sequence percentage cutoff; discard the entire sequence if > this number; default: 1
		-minlen		[int]	Minimum sequence length filter after clean up; default: 100 (bp)
		-maxlen		[int]	Maximum sequence length filter after clean up; default: 25000 (bp)
		-cleanN		[0|1]	Retain (0) or remove (1) the -misschar taget in output sequence; default: 0
		-cleanT		[0|1]	Remove entire seq. if any terminal seq (20bp) has 15bp of N (1); disabled by default (0).
		-minrm		[int]	The minimum length of -misschar to be removed if -cleanN 1; default: 1.
		-trf		[0|1]	Enable (1) or disable (0) tandem repeat finder (trf); default: 1
		-trf_path	path	Path to the trf program

Input not found!
ERROR: Final TE library not found in rice_genome.fasta.mod.EDTA.TElib.fa at ~omendivi/.conda/envs/EDTA/share/EDTA/EDTA.pl line 565.

**Comment by oushujun** [comment]
Hi, there is an error in your report: ValueError("Mixed RNA/DNA found")
You may want to take care of this first. Check your input file for --cds.

Best,
Shujun

**Comment by oushujun** [comment]
Close due to inactivity. Please reopen it if the issue is unresolved. - Shujun

**Comment by oliviamr** [comment]
Yes, I sorted this. 
Thank you 👍🏻
