### ISSUE TITLE
Error during the Identify TIR candidates from scratch

### ISSUE THREAD

**Issue by shehongbing** [oushujun/EDTA#177]
Hi,
     when i run the EDTA.pl using test data. And a error occurred as  followed:

Species: others
Traceback (most recent call last):
  File "/data/pub/shehb/miniconda2/envs/EDTA/bin/EDTA/bin/TIR-Learner2.5/Module2/ProcessGRFmite.py", line 104, in <module>
    pool = multiprocessing.Pool(int(t))
  File "/data/pub/shehb/miniconda2/envs/EDTA/lib/python3.6/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/data/pub/shehb/miniconda2/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 156, in __init__
    self._setup_queues()
  File "/data/pub/shehb/miniconda2/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 249, in _setup_queues
    self._inqueue = self._ctx.SimpleQueue()
  File "/data/pub/shehb/miniconda2/envs/EDTA/lib/python3.6/multiprocessing/context.py", line 112, in SimpleQueue
    return SimpleQueue(ctx=self.get_context())
  File "/data/pub/shehb/miniconda2/envs/EDTA/lib/python3.6/multiprocessing/queues.py", line 315, in __init__
    self._rlock = ctx.Lock()
  File "/data/pub/shehb/miniconda2/envs/EDTA/lib/python3.6/multiprocessing/context.py", line 67, in Lock
    return Lock(ctx=self.get_context())
  File "/data/pub/shehb/miniconda2/envs/EDTA/lib/python3.6/multiprocessing/synchronize.py", line 162, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/data/pub/shehb/miniconda2/envs/EDTA/lib/python3.6/multiprocessing/synchronize.py", line 59, in __init__
    unlink_now)
PermissionError: [Errno 13] Permission denied

It might be about the multiprocess. what should i do.

Thx

**Comment by oushujun** [comment]
Hello, sorry I didn't encounter this before. You may need to search around
to diagnose the issue. A recommendation from me would be reinstalling a
brand new conda and EDTA. Hope this helps.

Best,
Shujun
