### ISSUE TITLE
TIR step failure

### ISSUE THREAD

**Issue by cjy8709** [oushujun/EDTA#202]
Dear Shujun

I have an error during the TIR step that I think similar error has been seen previously. Note I've tried the test data and it works fine.
I am using EDTA ver 1.9.9 that was installed using conda EDTA. I've also tried the singulairty version as well and still get the same error below:

Thu Jul  1 12:17:18 EDT 2021	EDTA_raw: Check dependencies, prepare working directories.

Thu Jul  1 12:17:20 EDT 2021	Start to find LTR candidates.

Thu Jul  1 12:17:20 EDT 2021	Identify LTR retrotransposon candidates from scratch.

Thu Jul  1 12:45:35 EDT 2021	Finish finding LTR candidates.

Thu Jul  1 12:45:35 EDT 2021	Start to find TIR candidates.

Thu Jul  1 12:45:35 EDT 2021	Identify TIR candidates from scratch.

Species: Rice
cat: '*-+-*-+-*.gff3': No such file or directory
Traceback (most recent call last):
  File "/home/jyc387/PROGRAMS_AND_SCRIPTS/PROGRAMS/EDTA/bin/TIR-Learner2.5/Module3/CombineAll.py", line 80, in <module>
    f_m1=removeDupinSingle("%s.gff3"%(genome_Name+spliter+"Module1"))
  File "/home/jyc387/PROGRAMS_AND_SCRIPTS/PROGRAMS/EDTA/bin/TIR-Learner2.5/Module3/CombineAll.py", line 56, in removeDupinSingle
    f=pd.read_csv(file,header=None,sep="\t") #shujun
  File "/scratch/jyc387/miniconda3/envs/EDTA/lib/python3.6/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/scratch/jyc387/miniconda3/envs/EDTA/lib/python3.6/site-packages/pandas/io/parsers.py", line 454, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/scratch/jyc387/miniconda3/envs/EDTA/lib/python3.6/site-packages/pandas/io/parsers.py", line 948, in __init__
    self._make_engine(self.engine)
  File "/scratch/jyc387/miniconda3/envs/EDTA/lib/python3.6/site-packages/pandas/io/parsers.py", line 1180, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/scratch/jyc387/miniconda3/envs/EDTA/lib/python3.6/site-packages/pandas/io/parsers.py", line 2010, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 540, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/scratch/jyc387/miniconda3/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/scratch/jyc387/miniconda3/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/jyc387/PROGRAMS_AND_SCRIPTS/PROGRAMS/EDTA/bin/TIR-Learner2.5/Module3/GetAllSeq.py", line 32, in GetListFromFile
    f=open(file,"r+")
FileNotFoundError: [Errno 2] No such file or directory: 'TIR-Learner_FinalAnn.gff3'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jyc387/PROGRAMS_AND_SCRIPTS/PROGRAMS/EDTA/bin/TIR-Learner2.5/Module3/GetAllSeq.py", line 63, in <module>
    pool.map(GetListFromFile,fileList) #shujun
  File "/scratch/jyc387/miniconda3/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/scratch/jyc387/miniconda3/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: 'TIR-Learner_FinalAnn.gff3'
cp: cannot stat 'TIR-Learner/*FinalAnn*.gff3': No such file or directory
cp: cannot stat 'TIR-Learner/*FinalAnn*.fa': No such file or directory
Can't open ./TIR-Learner-Result/TIR-Learner_FinalAnn.fa: No such file or directory at /home/jyc387/PROGRAMS_AND_SCRIPTS/PROGRAMS/EDTA/util/rename_tirlearner.pl line 19.
Warning: LOC list GCA_009830595.1_AzucenaRS1_genomic.12chr.fa.mod.TIR.ext30.list is empty.

Error: Error while loading sequenceCan't open ./TIR-Learner-Result/TIR-Learner_FinalAnn.gff3: No such file or directory.
Warning: The TIR result file has 0 bp!

Thu Jul  1 13:50:34 EDT 2021	Start to find Helitron candidates.

Thu Jul  1 13:50:34 EDT 2021	Identify Helitron candidates from scratch.

The EDTA command I've used is:

perl /home/jyc387/PROGRAMS_AND_SCRIPTS/PROGRAMS/EDTA/EDTA.pl --genome "$GENOME" --species Rice --cds "$CDS" --exclude "$BED" --anno 1 --threads 20

Thanks for the advice!

**Comment by cjy8709** [comment]
After playing around with my data I found that if I change the name of my chromosomes things seem to work now.
Previously the chromosome name was "CM020633.1" but when I changed it to "CM020633" it seems to not have any problems at the TIR step. Very strange that a period is not allowed in the chromosome name for the TIR step.

**Comment by oushujun** [comment]
Thanks for pointing that out. I will take a look.

Shujun

**Comment by oushujun** [comment]
Hello @cjy8709,

I added ".1" to the seq name of the test data "genome.fa" and run EDTA, and didn't encounter any errors. Can you double check your input data?

Thanks,
Shujun
