### ISSUE TITLE
TIR question

### ISSUE THREAD

**Issue by helen5588** [oushujun/EDTA#267]
When I installed the EDTA 2.0.0, I tried to run it. But there is something wrong in the step of the TIR. Is this the version problem of the python ?
Traceback (most recent call last):
  File "/opt/Bio/EDTA/2.0.0/share/EDTA/bin/TIR-Learner2.5/Module3_New/getDataset.py", line 13, in <module>
    from sklearn.preprocessing import LabelEncoder, OneHotEncoder
  File "/opt/Bio/EDTA/2.0.0/lib/python3.6/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/opt/Bio/EDTA/2.0.0/lib/python3.6/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/opt/Bio/EDTA/2.0.0/lib/python3.6/site-packages/sklearn/utils/__init__.py", line 23, in <module>
    from .class_weight import compute_class_weight, compute_sample_weight
  File "/opt/Bio/EDTA/2.0.0/lib/python3.6/site-packages/sklearn/utils/class_weight.py", line 7, in <module>
    from .validation import _deprecate_positional_args
  File "/opt/Bio/EDTA/2.0.0/lib/python3.6/site-packages/sklearn/utils/validation.py", line 22, in <module>
    import joblib
  File "/opt/Bio/EDTA/2.0.0/lib/python3.6/site-packages/joblib/__init__.py", line 120, in <module>
    from .parallel import Parallel
  File "/opt/Bio/EDTA/2.0.0/lib/python3.6/site-packages/joblib/parallel.py", line 26, in <module>
    from ._parallel_backends import (FallbackToBackend, MultiprocessingBackend,
  File "/opt/Bio/EDTA/2.0.0/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 17, in <module>
    from .pool import MemmappingPool
  File "/opt/Bio/EDTA/2.0.0/lib/python3.6/site-packages/joblib/pool.py", line 31, in <module>
    from ._memmapping_reducer import get_memmapping_reducers
  File "/opt/Bio/EDTA/2.0.0/lib/python3.6/site-packages/joblib/_memmapping_reducer.py", line 37, in <module>
    from .externals.loky.backend import resource_tracker
  File "/opt/Bio/EDTA/2.0.0/lib/python3.6/site-packages/joblib/externals/loky/__init__.py", line 12, in <module>
    from .backend.reduction import set_loky_pickler
  File "/opt/Bio/EDTA/2.0.0/lib/python3.6/site-packages/joblib/externals/loky/backend/reduction.py", line 125, in <module>
    from joblib.externals import cloudpickle  # noqa: F401
  File "/opt/Bio/EDTA/2.0.0/lib/python3.6/site-packages/joblib/externals/cloudpickle/__init__.py", line 4, in <module>
    from .cloudpickle import *  # noqa
  File "/opt/Bio/EDTA/2.0.0/lib/python3.6/site-packages/joblib/externals/cloudpickle/cloudpickle.py", line 64, in <module>
    import typing_extensions as _typing_extensions
  File "/opt/Bio/EDTA/2.0.0/lib/python3.6/site-packages/typing_extensions.py", line 159, in <module>
    class _FinalForm(typing._SpecialForm, _root=True):
AttributeError: module 'typing' has no attribute '_SpecialForm'

**Comment by oushujun** [comment]
You may want to test with the small data in EDTA/test/. Most likely your env is not correctly set up.

Shujun

**Comment by oushujun** [comment]
@helen5588 any luck?

**Comment by oushujun** [comment]
This issue should be fixed in v2.2.2 with the new TIR-Learner 3.
