### ISSUE TITLE
THE SAME ISSUE: RMblast engine is not installed in RepeatMasker

### ISSUE THREAD

**Issue by jun3234** [oushujun/EDTA#284]
Thank you for this great tools !

I have met some problem, could you help me ?

I installed EDTA through `conda`,

by two ways:

```
#the first way
git clone https://github.com/oushujun/EDTA.git
conda env create -f EDTA.yml

#the second way
conda create -n EDTA
conda activate EDTA
mamba install -c conda-forge -c bioconda edta python=3.6 tensorflow=1.14 'h5py<3'
```

But all this two raised the same issues:  `Error: The RMblast engine is not installed in RepeatMasker!`, and the `logs` file info:

```
########################################################
##### Extensive de-novo TE Annotator (EDTA) v2.0.1  ####
##### Shujun Ou (shujun.ou.1@gmail.com)             ####
########################################################



Fri Jul 22 09:48:37 CST 2022    Dependency checking:
```

I found the `RM_58761.FriJul220949002022` directory, the `log` file info as follows:

```
Building a new DB, current time: 07/22/2022 09:50:10
New DB name:   /home/jing_liu/Kingfruit/workdir/asm/04.repeat_anno/RM_58761.FriJul220949002022/dummy060817.fa.353930
New DB title:  dummy060817.fa.353930
Sequence type: Nucleotide
Keep MBits: T
Maximum file size: 1000000000B
Adding sequences from FASTA; added 1 sequences in 0.000669956 seconds.

No volumes were created.

BLAST Database creation error: mdb_env_open: Cannot allocate memory
```

I checked the dependency env by `EDTA.pl  --check_dependencies`, and screen shows as follows:

all dependencies seem exists !

```
########################################################
##### Extensive de-novo TE Annotator (EDTA) v2.0.1  ####
##### Shujun Ou (shujun.ou.1@gmail.com)             ####
########################################################



Fri Jul 22 10:04:26 CST 2022    Dependency checking:
                                All passed!
```

For further check; `RepeatMasker -h` and `which rmblastn` also ran ok !

![image](https://user-images.githubusercontent.com/20549259/180347495-0983e8ff-3dee-4afc-9f0b-70a52fbd599f.png)

![image](https://user-images.githubusercontent.com/20549259/180347683-66d838a8-ae08-426d-abb0-0b2f4d08764b.png)

I also read the #249, #250 and some others, re-install `conda` can't  resolve this issue.

Could you help me ?

**Comment by oushujun** [comment]
Maybe this is related: https://gitlab.com/ezlab/busco/-/issues/356

**Comment by jun3234** [comment]
I solved the problem eventually. Commenting the `#SBATCH --mem` command line in `slurm`  scripts and It run OK!

**Comment by jun3234** [comment]
But soon, I met another issue. Once run in `slurm`  system, There are always show error:

```
Sun Jul 24 11:00:48 CST 2022    Start to find TIR candidates.

Sun Jul 24 11:00:48 CST 2022    Identify TIR candidates from scratch.

Species: others
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/jing_liu/anaconda3/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/jing_liu/anaconda3/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/jing_liu/anaconda3/envs/EDTA/share/EDTA/bin/TIR-Learner2.5/Module3_New/getDataset.py", line 110, in Predict
    model = load_model(path+'/CNN0912.h5')
  File "/home/jing_liu/anaconda3/envs/EDTA/lib/python3.6/site-packages/tensorflow/python/keras/saving/save.py", line 146, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/home/jing_liu/anaconda3/envs/EDTA/lib/python3.6/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 215, in load_model_from_hdf5
    load_weights_from_hdf5_group(f['model_weights'], model.layers)
  File "/home/jing_liu/anaconda3/envs/EDTA/lib/python3.6/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 728, in load_weights_from_hdf5_group
    g = f[name]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/jing_liu/anaconda3/envs/EDTA/lib/python3.6/site-packages/h5py/_hl/group.py", line 264, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (file read failed: time = Sun Jul 24 12:50:10 2022\n, filename = '/home/jing_liu/anaconda3/envs/EDTA/share/EDTA/bin/TIR-Learner2.5
/CNN0912.h5', file descriptor = 5, errno = 5, error message = 'Input/output error', buf = 0x55746310aa30, total read size = 512, bytes this sub-read = 512, bytes a
ctually read = 18446744073709551615, offset = 0)"
"""

**Comment by oushujun** [comment]
Looks like your version is not correctly installed. Please reinstall and test with the small file included in the package.
