### ISSUE TITLE
ERROR: No candidate is found in the file(s) you specified.

### ISSUE THREAD

**Issue by caixu0518** [oushujun/EDTA#287]
Hi shujun,

When I'm running the EDTA process, I'm getting an error that I can't fix. I have pasted my log file as below, I hope to get your help.

Best,
Xu

########################################################
########################################################

2022年 07月 26日 星期二 22:28:33 CST	Dependency checking:
				All passed!

2022年 07月 26日 星期二 22:28:39 CST	Obtain raw TE libraries using various structure-based programs: 
2022年 07月 26日 星期二 22:28:40 CST	EDTA_raw: Check dependencies, prepare working directories.

2022年 07月 26日 星期二 22:28:45 CST	Start to find LTR candidates.

2022年 07月 26日 星期二 22:28:45 CST	Identify LTR retrotransposon candidates from scratch.

2022年 07月 26日 星期二 22:28:45 CST	Existing raw result aa.fa.mod.harvest.scn found!
				Will use this for further analyses.

2022年 07月 26日 星期二 22:28:45 CST	Existing raw result aa.fa.mod.finder.combine.scn found!
				Will use this for further analyses.

**ERROR: No candidate is found in the file(s) you specified.**

**awk: fatal: cannot open file `aa.fa.mod.pass.list' for reading (没有那个文件或目录)
Warning: LOC list - is empty.**

	perl rename_LTR_skim.pl target_sequence.fa LTR_retriever.defalse

Error: Error while loading sequence
	perl filter_gff3.pl file.gff3 file.list > new.gff3

2022年 07月 26日 星期二 22:29:04 CST	Warning: The LTR result file has 0 bp!

2022年 07月 26日 星期二 22:29:04 CST	Start to find TIR candidates.

2022年 07月 26日 星期二 22:29:04 CST	Identify TIR candidates from scratch.

Species: others
cat: '*-+-*-+-*.gff3': 没有那个文件或目录
rm: 无法删除 '*-+-*-+-*.gff3': 没有那个文件或目录
Traceback (most recent call last):
  File "/120t/caix/src/EDTA/test/EDTA-2.0.1/bin/TIR-Learner2.5/Module3_New/CombineAll.py", line 75, in <module>
    f_m3=removeDupinSingle("%s.gff3"%(genome_Name+spliter+"Module3"))
  File "/120t/caix/src/EDTA/test/EDTA-2.0.1/bin/TIR-Learner2.5/Module3_New/CombineAll.py", line 57, in removeDupinSingle
    f=pd.read_csv(file,header=None,sep="\t") #shujun
  File "/120t/caix/anaconda3/envs/edta/lib/python3.6/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/120t/caix/anaconda3/envs/edta/lib/python3.6/site-packages/pandas/io/parsers.py", line 454, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/120t/caix/anaconda3/envs/edta/lib/python3.6/site-packages/pandas/io/parsers.py", line 948, in __init__
    self._make_engine(self.engine)
  File "/120t/caix/anaconda3/envs/edta/lib/python3.6/site-packages/pandas/io/parsers.py", line 1180, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/120t/caix/anaconda3/envs/edta/lib/python3.6/site-packages/pandas/io/parsers.py", line 2010, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 540, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/120t/caix/anaconda3/envs/edta/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/120t/caix/anaconda3/envs/edta/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/120t/caix/src/EDTA/test/EDTA-2.0.1/bin/TIR-Learner2.5/Module3/GetAllSeq.py", line 32, in GetListFromFile
    f=open(file,"r+")
FileNotFoundError: [Errno 2] No such file or directory: 'TIR-Learner_FinalAnn.gff3'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/120t/caix/src/EDTA/test/EDTA-2.0.1/bin/TIR-Learner2.5/Module3/GetAllSeq.py", line 63, in <module>
    pool.map(GetListFromFile,fileList) #shujun
  File "/120t/caix/anaconda3/envs/edta/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/120t/caix/anaconda3/envs/edta/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: 'TIR-Learner_FinalAnn.gff3'
mv: 对 'TIR-Learner/*FinalAnn*.gff3' 调用 stat 失败: 没有那个文件或目录
mv: 对 'TIR-Learner/*FinalAnn*.fa' 调用 stat 失败: 没有那个文件或目录
Can't open ./TIR-Learner-Result/TIR-Learner_FinalAnn.fa: 没有那个文件或目录 at /120t/caix/src/EDTA/test/EDTA-2.0.1/util/rename_tirlearner.pl line 19.
Warning: LOC list aa.fa.mod.TIR.ext30.list is empty.

Error: Error while loading sequenceCan't open ./TIR-Learner-Result/TIR-Learner_FinalAnn.gff3: 没有那个文件或目录.
Warning: The TIR result file has 0 bp!

2022年 07月 26日 星期二 22:29:26 CST	Start to find Helitron candidates.

2022年 07月 26日 星期二 22:29:26 CST	Identify Helitron candidates from scratch.

Warning: LOC list aa.fa.mod.HelitronScanner.raw.ext.list is empty.
Warning: LOC list aa.fa.mod.HelitronScanner.raw.ext.list is empty.

Error: Error while loading sequence
	perl make_bed_with_intact.pl EDTA.intact.fa > EDTA.intact.bed 

2022年 07月 26日 星期二 22:29:42 CST	Warning: The Helitron result file has 0 bp!

2022年 07月 26日 星期二 22:29:42 CST	Execution of EDTA_raw.pl is finished!

ERROR: Raw LTR results not found in aa.fa.mod.EDTA.raw/aa.fa.mod.LTR.raw.fa
	If you believe the program is working properly, this may be caused by the lack of intact LTRs in your genome. Consider to use the --force 1 parameter to overwrite this check

**Comment by oushujun** [comment]
It says it cannot find any LTR, TIR, and Helitron in your input file.

Shujun

**Comment by oushujun** [comment]
@caixu0518 any luck?
