### ISSUE TITLE
python2 was called when running cleanup_TE.pl 

### ISSUE THREAD

**Issue by QiushiLi** [oushujun/EDTA#31]
Dear Shujun,

When the -cds option is added, it seems like EDTA switches to use python2 for TEsorter. See cleanup_TE.pl line 36.

`python2 $TEsorter $cds -p $threads`;

This caused many incompatible issues for like Biopython between python2 and python3.

I installed a separate conda env of python2 for the TEsorter, but still got error in test:

(py2) [qiushi.li@itbioyeaman03 test]$ python ../TEsorter.py rice6.9.5.liban
2019-11-27 07:08:19,201 -WARNING- No module named drmaa
grid computing is not available
2019-11-27 07:08:19,203 -INFO- VARS: {'seq_type': 'nucl', 'min_coverage': 20, 'disable_pass2': False, 'tmp_dir': './tmp', 'processors': 4, 'sequence': 'rice6.9.5.liban', 'no_library': False, 'p2_identity': 80.0, 'no_cleanup': False, 'force_write_hmmscan': False, 'p2_length': 80.0, 'prefix': 'rice6.9.5.liban.rexdb', 'max_evalue': 0.001, 'p2_coverage': 80.0, 'pass2_rule': '80-80-80', 'hmm_database': 'rexdb', 'no_reverse': False}
2019-11-27 07:08:19,203 -INFO- checking dependencies:
2019-11-27 07:08:19,213 -INFO- hmmer 3.2.1 OK
Traceback (most recent call last):
  File "../TEsorter.py", line 974, in <module>
    pipeline(Args())
  File "../TEsorter.py", line 116, in pipeline
    Dependency().check_blast()
  File "../TEsorter.py", line 920, in check_blast
    version = self.check_blast_version(program)
  File "../TEsorter.py", line 939, in check_blast_version
    version = re.compile(r'blast\S* ([\d\.\+]+)').search(out).groups()[0]
AttributeError: 'NoneType'  

Best,
Qiushi

**Comment by elsemikk** [comment]
I had the same issue, to get it to run I had to make a conda environment with python=2.7, blast, hmmer, bioconda, pp, and drmaa, and needed to define the variable DRMAA_LIBRARY_PATH as the path to libdrmaa.so.1.0 (obtained by apt install gridengine-drmaa-dev). After doing that the TEsorter seemed to run without error, but I'm not sure if it is the most efficient way.

**Comment by oushujun** [comment]
Dear @QiushiLi @elsemikk,

Thanks for your feedback. I updated the README for TEsorter installation instructions. In particular, you can install python2 dependencies for TEsorter using the system python2 and your local user account. The downside of this comparing to the conda way @elsemikk contributed is that you need to have pip available.

`python2 -m pip install --user numpy==1.14.3 biopython==1.74 pp`

Please let me know if the problem persists.

Best,
Shujun
