### ISSUE TITLE
terminate called after throwing an instance of 'std::logic_error'

### ISSUE THREAD

**Issue by JiyangChang** [oushujun/EDTA#311]
Dear Shujun,

Thanks for the great work!

I met some troubles during installation and run the test.

We installed EDTA in a traditional manner (not like you recommended in the description), and I got the following error message when I ran the test. How can I solve this? 
```
########################################################
##### Extensive de-novo TE Annotator (EDTA) v2.1.0  ####
##### Shujun Ou (shujun.ou.1@gmail.com)             ####
########################################################



Wed Nov  9 17:20:46 CET 2022	Dependency checking:
				All passed!

	A custom library /software/shared/apps/x86_64/EDTA/2.1.0/database/rice6.9.5.liban is provided via --curatedlib. Please make sure this is a manually curated library but not machine generated.

	A CDS file genome.cds.fa is provided via --cds. Please make sure this is the DNA sequence of coding regions only.

	A BED file is provided via --exclude. Regions specified by this file will be excluded from TE annotation and masking.

Wed Nov  9 17:20:50 CET 2022	Obtain raw TE libraries using various structure-based programs: 
Wed Nov  9 17:20:50 CET 2022	EDTA_raw: Check dependencies, prepare working directories.

Wed Nov  9 17:20:52 CET 2022	Start to find LTR candidates.

Wed Nov  9 17:20:52 CET 2022	Identify LTR retrotransposon candidates from scratch.

terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid
timeout: the monitored command dumped core
sh: line 1: 82213 Aborted                 timeout 300 /software/shared/apps/x86_64/GenericRepeatFinder/1.0/bin/ltr_finder -w 2 -C -D 15000 -d 1000 -L 7000 -l 100 -p 20 -M 0.85 Chr2_sub1 > Chr2_sub1.finder.scn
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid
sh: line 1: 82218 Aborted                 (core dumped) /software/shared/apps/x86_64/GenericRepeatFinder/1.0/bin/ltr_finder -w 2 -C -D 15000 -d 1000 -L 7000 -l 100 -p 20 -M 0.85 Chr2_sub1 > Chr2_sub1.finder.scn
Wed Nov  9 17:21:41 CET 2022	Finish finding LTR candidates.

Wed Nov  9 17:21:41 CET 2022	Start to find TIR candidates.

Wed Nov  9 17:21:41 CET 2022	Identify TIR candidates from scratch.

Species: others
Traceback (most recent call last):
  File "/shared/clssoft/apps/x86_64/EDTA/2.1.0/bin/TIR-Learner2.5/Module3_New/getDataset.py", line 12, in <module>
    from tensorflow.python.keras.utils import to_categorical
ImportError: cannot import name 'to_categorical'
cat: *-+-DTA.fa: No such file or directory
cat: *-+-DTC.fa: No such file or directory
cat: *-+-DTH.fa: No such file or directory
cat: *-+-DTM.fa: No such file or directory
cat: *-+-DTT.fa: No such file or directory
cat: *-+-NonTIR.fa: No such file or directory
cat: *-+-*-+-*.gff3: No such file or directory
rm: cannot remove ‘*-+-*-+-*.gff3’: No such file or directory
Traceback (most recent call last):
  File "/shared/clssoft/apps/x86_64/EDTA/2.1.0/bin/TIR-Learner2.5/Module3_New/CombineAll.py", line 75, in <module>
    f_m3=removeDupinSingle("%s.gff3"%(genome_Name+spliter+"Module3"))
  File "/shared/clssoft/apps/x86_64/EDTA/2.1.0/bin/TIR-Learner2.5/Module3_New/CombineAll.py", line 57, in removeDupinSingle
    f=pd.read_csv(file,header=None,sep="\t") #shujun
  File "/home/jicha/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/jicha/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 429, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/jicha/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/home/jicha/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1122, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/jicha/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1853, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 545, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/software/shared/apps/x86_64/python/3.6.5/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/software/shared/apps/x86_64/python/3.6.5/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/shared/clssoft/apps/x86_64/EDTA/2.1.0/bin/TIR-Learner2.5/Module3/GetAllSeq.py", line 32, in GetListFromFile
    f=open(file,"r+")
FileNotFoundError: [Errno 2] No such file or directory: 'TIR-Learner_FinalAnn_filter.gff3'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/shared/clssoft/apps/x86_64/EDTA/2.1.0/bin/TIR-Learner2.5/Module3/GetAllSeq.py", line 63, in <module>
    pool.map(GetListFromFile,fileList) #shujun
  File "/software/shared/apps/x86_64/python/3.6.5/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/software/shared/apps/x86_64/python/3.6.5/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: 'TIR-Learner_FinalAnn_filter.gff3'
mv: cannot stat ‘TIR-Learner/*FinalAnn*.gff3’: No such file or directory
mv: cannot stat ‘TIR-Learner/*FinalAnn*.fa’: No such file or directory
Can't open ./TIR-Learner-Result/TIR-Learner_FinalAnn.fa: No such file or directory at /shared/clssoft/apps/x86_64/EDTA/2.1.0/util/rename_tirlearner.pl line 19.
Warning: LOC list genome.fa.mod.TIR.ext30.list is empty.

Error: Error while loading sequenceCan't open ./TIR-Learner-Result/TIR-Learner_FinalAnn.gff3: No such file or directory.
Warning: The TIR result file has 0 bp!

Wed Nov  9 17:24:01 CET 2022	Start to find Helitron candidates.

Wed Nov  9 17:24:01 CET 2022	Identify Helitron candidates from scratch.

HelitronScanner result files for the genome.fa.mod is not found!

Filter HelitronScanner fasta candidates
	perl format_helitronscanner_out.pl -genome genome.fa [options]
		-sitefilter	[0|1]	1 will filter out candidate without AT or TT target site (default); 0 will not.
		-minscore	[int]	Candidates with head and tail quality scores add up less than this will be discarded. Default: 12
		-keepshorter	[0|1]	1 will keep the shorter possible when multi 5' end presents (default); 0 will not.
		-extlen	[int]	Length of flanking sequence for blast and output. Default: 30 (bp)
		-extout	[0|1]	Output original sequence (0, default) or extended (1) sequence.
		-h|-help	Display this help messege and exit.

HelitronScanner result files for the genome.fa.mod is not found!

Filter HelitronScanner fasta candidates
	perl format_helitronscanner_out.pl -genome genome.fa [options]
		-sitefilter	[0|1]	1 will filter out candidate without AT or TT target site (default); 0 will not.
		-minscore	[int]	Candidates with head and tail quality scores add up less than this will be discarded. Default: 12
		-keepshorter	[0|1]	1 will keep the shorter possible when multi 5' end presents (default); 0 will not.
		-extlen	[int]	Length of flanking sequence for blast and output. Default: 30 (bp)
		-extout	[0|1]	Output original sequence (0, default) or extended (1) sequence.
		-h|-help	Display this help messege and exit.

The query file genome.fa.mod.HelitronScanner.filtered.ext.fa is not found!

Filter HelitronScanner fasta candidates
	perl flanking_filter.pl -genome genome.fa -query candidate.fa [options]
		-genome	[file]	The multifasta file that used to generate the -query
		-query	[file]	The candidate TE sequence to be filtered by this script
		-extlen	[int]	The length of extended flanking sequence in -query. Default: 30 (bp)
		-tgt_out	[int]	Output taget site with [int] length on each terminal. Default: 15 (bp)
		-miniden	[int]	Minimum identity for flanking sequence alignment. Default: 80 (%)
		-mincov	[float]	Minimum coverage for flanking sequence alignment that counts as full match. Default: 0.8
		-maxct	[int]	Maximum allowed copy number for flanking sequence for a true element. Default: 1.
		-blastplus	[path]	Path to the blastn program. Defalut: read from $ENV
		-t|-threads	[int]	Number of threads to run this program. Default: 4
		-h|-help	Display this help messege and exit.

ERROR: No such file or directory at /shared/clssoft/apps/x86_64/EDTA/2.1.0/util/output_by_list.pl line 37.

Error: Error while loading sequence
	perl make_bed_with_intact.pl EDTA.intact.fa > EDTA.intact.bed 

Wed Nov  9 17:24:01 CET 2022	Warning: The Helitron result file has 0 bp!

Wed Nov  9 17:24:01 CET 2022	Execution of EDTA_raw.pl is finished!

ERROR: Raw TIR results not found in genome.fa.mod.EDTA.raw/genome.fa.mod.TIR.raw.fa
	If you believe the program is working properly, this may be caused by the lack of intact TIRs in your genome. Consider to use the --force 1 parameter to overwrite this check
```

**Comment by oushujun** [comment]
It Maybe related to the LTR_Finder version you used. Could you test it
separately?
ie.

 /software/shared/apps/x86_64/GenericRepeatFinder/1.0/bin/ltr_finder
-w 2 -C -D 15000 -d 1000 -L 7000 -l 100 -p 20 -M 0.85 Chr2_sub1 >
Chr2_sub1.finder.scn

Best,
Shujun

**Comment by JiyangChang** [comment]
I can't find the temperate file 'Chr2_sub1' so I cannot directly rerun this step. However, If I use `genome.fa` as the input file for the `ltr_finder` from GRF, I have the same error I got before.

```
/software/shared/apps/x86_64/GenericRepeatFinder/1.0/bin/ltr_finder  -w 2 -C -D 15000 -d 1000 -L 7000 -l 100 -p 20 -M 0.85 genome.fa > aaa.scn
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid
Aborted
```

Is this `ltr_finder` supposed to be used or a separate LTR_Finder should be used?

Thanks a lot!

**Comment by oushujun** [comment]
Yes, this version of `ltr_finder` could not be executed independently. I remotely remember I used this before and encounter errors.

The `keras` issue seems related to installation. `TIR-Learner` is very picky of keras versions because it was developed a while ago.

Shujun
