### ISSUE TITLE
TIR-Learner errors

### ISSUE THREAD

**Issue by MonsterLaplace** [oushujun/EDTA#313]
2022年 11月 21日 星期一 08:37:25 CST    Dependency checking:
                                All passed!

2022年 11月 21日 星期一 08:37:49 CST    The longest sequence ID in the genome contains 15 characters, which is longer than the limit (13)
                                Trying to reformat seq IDs...
                                Attempt 1...
                                Attempt 2...
2022年 11月 21日 星期一 08:38:01 CST    Seq ID conversion successful!

        A CDS file sheep.cds.fa is provided via --cds. Please make sure this is the DNA sequence of coding regions only.

2022年 11月 21日 星期一 08:38:13 CST    Obtain raw TE libraries using various structure-based programs: 
2022年 11月 21日 星期一 08:38:13 CST    EDTA_raw: Check dependencies, prepare working directories.

2022年 11月 21日 星期一 08:38:18 CST    Start to find LTR candidates.

2022年 11月 21日 星期一 08:38:18 CST    Identify LTR retrotransposon candidates from scratch.

2022年 11月 21日 星期一 10:21:03 CST    Finish finding LTR candidates.

2022年 11月 21日 星期一 10:21:03 CST    Start to find TIR candidates.

2022年 11月 21日 星期一 10:21:03 CST    Identify TIR candidates from scratch.

Species: others
Traceback (most recent call last):
  File "/home/xb/miniconda3/envs/EDTA/share/EDTA/bin/TIR-Learner2.5/Module2/RunGRF.py", line 79, in <module>
    if (len(str(records[0].seq))>int(length)+500):
IndexError: list index out of range
cp: 无法获取'TIR-Learner/*-p' 的文件状态(stat): 没有那个文件或目录
cat: '*-+-DTA.fa': 没有那个文件或目录
cat: '*-+-DTC.fa': 没有那个文件或目录
cat: '*-+-DTH.fa': 没有那个文件或目录
cat: '*-+-DTM.fa': 没有那个文件或目录
cat: '*-+-DTT.fa': 没有那个文件或目录
cat: '*-+-NonTIR.fa': 没有那个文件或目录
cat: '*-+-*-+-*.gff3': 没有那个文件或目录
rm: 无法删除'*-+-*-+-*.gff3': 没有那个文件或目录
Traceback (most recent call last):
  File "/home/xb/miniconda3/envs/EDTA/share/EDTA/bin/TIR-Learner2.5/Module3_New/CombineAll.py", line 75, in <module>
    f_m3=removeDupinSingle("%s.gff3"%(genome_Name+spliter+"Module3"))
  File "/home/xb/miniconda3/envs/EDTA/share/EDTA/bin/TIR-Learner2.5/Module3_New/CombineAll.py", line 57, in removeDupinSingle
    f=pd.read_csv(file,header=None,sep="\t") #shujun
  File "/home/xb/miniconda3/envs/EDTA/lib/python3.6/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/xb/miniconda3/envs/EDTA/lib/python3.6/site-packages/pandas/io/parsers.py", line 454, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/xb/miniconda3/envs/EDTA/lib/python3.6/site-packages/pandas/io/parsers.py", line 948, in __init__
    self._make_engine(self.engine)
  File "/home/xb/miniconda3/envs/EDTA/lib/python3.6/site-packages/pandas/io/parsers.py", line 1180, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/xb/miniconda3/envs/EDTA/lib/python3.6/site-packages/pandas/io/parsers.py", line 2010, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 540, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/xb/miniconda3/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/xb/miniconda3/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/xb/miniconda3/envs/EDTA/share/EDTA/bin/TIR-Learner2.5/Module3/GetAllSeq.py", line 32, in GetListFromFile
    f=open(file,"r+")
FileNotFoundError: [Errno 2] No such file or directory: 'TIR-Learner_FinalAnn_filter.gff3'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/xb/miniconda3/envs/EDTA/share/EDTA/bin/TIR-Learner2.5/Module3/GetAllSeq.py", line 63, in <module>
    pool.map(GetListFromFile,fileList) #shujun
  File "/home/xb/miniconda3/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/xb/miniconda3/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: 'TIR-Learner_FinalAnn_filter.gff3'
mv: 无法获取'TIR-Learner/*FinalAnn*.gff3' 的文件状态(stat): 没有那个文件或目录
mv: 无法获取'TIR-Learner/*FinalAnn*.fa' 的文件状态(stat): 没有那个文件或目录
Can't open ./TIR-Learner-Result/TIR-Learner_FinalAnn.fa: 没有那个文件或目录 at /home/xb/miniconda3/envs/EDTA/share/EDTA/util/rename_tirlearner.pl line 19.
Warning: LOC list sheep.fa.mod.TIR.ext30.list is empty.

Error: Error while loading sequenceCan't open ./TIR-Learner-Result/TIR-Learner_FinalAnn.gff3: 没有那个文件或目录.
Warning: The TIR result file has 0 bp!

**Comment by oushujun** [comment]
Hello,

It's likely that your genome file contains special characters. You may try the updated EDTA that better handles special characters. The best practice is to check your sequence file and try to tidy up sequence names before using EDTA. 

Thanks,
Shujun
