### ISSUE TITLE
Error in TIR-Learner step

### ISSUE THREAD

**Issue by AMartinsJr** [oushujun/EDTA#317]
Dear Shujun,
Thank you very much for this tool.
I am doing analysis in some large genomes and TIR-Learner erros are occurring as follow:

########################################################
########################################################

Wed Nov 30 16:30:12 -03 2022	Dependency checking:
				All passed!

	A custom library primates_Dfam-3.6.fa is provided via --curatedlib. Please make sure this is a manually curated library but not machine generated.

	A CDS file CDSHomosapiens140540.fna is provided via --cds. Please make sure this is the DNA sequence of coding regions only.

Wed Nov 30 16:30:53 -03 2022	Obtain raw TE libraries using various structure-based programs: 
Wed Nov 30 16:30:53 -03 2022	EDTA_raw: Check dependencies, prepare working directories.

Wed Nov 30 16:31:08 -03 2022	Start to find LTR candidates.

Wed Nov 30 16:31:08 -03 2022	Identify LTR retrotransposon candidates from scratch.

Wed Nov 30 18:47:36 -03 2022	Finish finding LTR candidates.

Wed Nov 30 18:47:36 -03 2022	Start to find TIR candidates.

Wed Nov 30 18:47:36 -03 2022	Identify TIR candidates from scratch.

Species: others
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/antonio/.conda/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/antonio/.conda/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/local/EDTA/bin/TIR-Learner2.5/Module3_New/getDataset.py", line 96, in getData
    inputfeatures=np.array(input_features)
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 940. MiB for an array with shape (123145, 400, 5) and data type float32
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/EDTA/bin/TIR-Learner2.5/Module3_New/getDataset.py", line 104, in <module>
    d = pool.map(getData,files)
  File "/home/antonio/.conda/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/antonio/.conda/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
numpy.core._exceptions.MemoryError: Unable to allocate 940. MiB for an array with shape (123145, 400, 5) and data type float32
cat: '*-+-DTA.fa': No such file or directory
cat: '*-+-DTC.fa': No such file or directory
cat: '*-+-DTH.fa': No such file or directory
cat: '*-+-DTM.fa': No such file or directory
cat: '*-+-DTT.fa': No such file or directory
cat: '*-+-NonTIR.fa': No such file or directory
cat: '*-+-*-+-*.gff3': No such file or directory
rm: cannot remove '*-+-*-+-*.gff3': No such file or directory
Traceback (most recent call last):
  File "/usr/local/EDTA/bin/TIR-Learner2.5/Module3_New/CombineAll.py", line 75, in <module>
    f_m3=removeDupinSingle("%s.gff3"%(genome_Name+spliter+"Module3"))
  File "/usr/local/EDTA/bin/TIR-Learner2.5/Module3_New/CombineAll.py", line 57, in removeDupinSingle
    f=pd.read_csv(file,header=None,sep="\t") #shujun
  File "/home/antonio/.conda/envs/EDTA/lib/python3.6/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/antonio/.conda/envs/EDTA/lib/python3.6/site-packages/pandas/io/parsers.py", line 454, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/antonio/.conda/envs/EDTA/lib/python3.6/site-packages/pandas/io/parsers.py", line 948, in __init__
    self._make_engine(self.engine)
  File "/home/antonio/.conda/envs/EDTA/lib/python3.6/site-packages/pandas/io/parsers.py", line 1180, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/antonio/.conda/envs/EDTA/lib/python3.6/site-packages/pandas/io/parsers.py", line 2010, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 540, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/antonio/.conda/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/antonio/.conda/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/local/EDTA/bin/TIR-Learner2.5/Module3/GetAllSeq.py", line 32, in GetListFromFile
    f=open(file,"r+")
FileNotFoundError: [Errno 2] No such file or directory: 'TIR-Learner_FinalAnn.gff3'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/EDTA/bin/TIR-Learner2.5/Module3/GetAllSeq.py", line 63, in <module>
    pool.map(GetListFromFile,fileList) #shujun
  File "/home/antonio/.conda/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/antonio/.conda/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: 'TIR-Learner_FinalAnn.gff3'
mv: cannot stat 'TIR-Learner/*FinalAnn*.gff3': No such file or directory
mv: cannot stat 'TIR-Learner/*FinalAnn*.fa': No such file or directory
Can't open ./TIR-Learner-Result/TIR-Learner_FinalAnn.fa: No such file or directory at /usr/local/EDTA/util/rename_tirlearner.pl line 19.
Warning: LOC list NovoAgeo1.fas.mod.TIR.ext30.list is empty.

Error: Error while loading sequenceCan't open ./TIR-Learner-Result/TIR-Learner_FinalAnn.gff3: No such file or directory.
Warning: The TIR result file has 0 bp!

Fri Dec  2 07:06:58 -03 2022	Start to find Helitron candidates.

Fri Dec  2 07:06:58 -03 2022	Identify Helitron candidates from scratch.

Killed
Sat Dec  3 04:54:25 -03 2022	Finish finding Helitron candidates.

Sat Dec  3 04:54:25 -03 2022	Execution of EDTA_raw.pl is finished!

ERROR: Raw TIR results not found in NovoAgeo1.fas.mod.EDTA.raw/NovoAgeo1.fas.mod.TIR.raw.fa
	If you believe the program is working properly, this may be caused by the lack of intact TIRs in your genome. Consider to use the --force 1 parameter to overwrite this check

I ran the analysis previously on other genomes and it worked fine.
What could be going wrong?

Best Regards,

Martins-Junior

**Comment by oushujun** [comment]
You may want to give it more memory.

**Comment by AMartinsJr** [comment]
> You may want to give it more memory.

Dear Shujun,
This server has 1 Tb of memory and no other task was running in it at the moment. Could this error have happened due to some other problem?

Best regards,

**Comment by oushujun** [comment]
This is the error message:

multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
File
"/home/antonio/.conda/envs/EDTA/lib/python3.6/multiprocessing/pool.py",
line 119, in worker
result = (True, func(*args, **kwds))
File
"/home/antonio/.conda/envs/EDTA/lib/python3.6/multiprocessing/pool.py",
line 44, in mapstar
return list(map(*args))
File "/usr/local/EDTA/bin/TIR-Learner2.5/Module3_New/getDataset.py", line
96, in getData
inputfeatures=np.array(input_features)
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 940. MiB for
an array with shape (123145, 400, 5) and data type float32
"""
Can you please run it again?

Shujun

**Comment by AMartinsJr** [comment]
Dear Shujun,

I ran the analysis again using two different servers, each one with 1Tb of memory, in two different genomes and the same error occurred.

This time I used 26 threads instead of 32.

The error was equal for both analysis and one of it is presented as follow:


########################################################
##### Extensive de-novo TE Annotator (EDTA) v2.0.1  ####
##### Shujun Ou (shujun.ou.1@gmail.com)             ####
########################################################



dom dez  4 12:30:30 -03 2022	Dependency checking:
				All passed!

	A custom library /media/storage3/ufpa/primates_Dfam-3.6.fa is provided via --curatedlib. Please make sure this is a manually curated library but not machine generated.

	A CDS file CDSHomosapiens140540.fna is provided via --cds. Please make sure this is the DNA sequence of coding regions only.

dom dez  4 12:31:22 -03 2022	Obtain raw TE libraries using various structure-based programs: 
dom dez  4 12:31:22 -03 2022	EDTA_raw: Check dependencies, prepare working directories.

dom dez  4 12:31:27 -03 2022	Start to find LTR candidates.

dom dez  4 12:31:27 -03 2022	Identify LTR retrotransposon candidates from scratch.

dom dez  4 14:23:38 -03 2022	Finish finding LTR candidates.

dom dez  4 14:23:38 -03 2022	Start to find TIR candidates.

dom dez  4 14:23:38 -03 2022	Identify TIR candidates from scratch.

Species: others
Traceback (most recent call last):
  File "/home/oliveirads/softwares/EDTA/bin/TIR-Learner2.5/Module2/RunGRF.py", line 79, in <module>
    if (len(str(records[0].seq))>int(length)+500):
IndexError: list index out of range
cp: impossível obter estado de 'TIR-Learner/*-p': Arquivo ou diretório inexistente
cat: '*-+-DTA.fa': Arquivo ou diretório inexistente
cat: '*-+-DTC.fa': Arquivo ou diretório inexistente
cat: '*-+-DTH.fa': Arquivo ou diretório inexistente
cat: '*-+-DTM.fa': Arquivo ou diretório inexistente
cat: '*-+-DTT.fa': Arquivo ou diretório inexistente
cat: '*-+-NonTIR.fa': Arquivo ou diretório inexistente
cat: '*-+-*-+-*.gff3': Arquivo ou diretório inexistente
rm: não foi possível remover '*-+-*-+-*.gff3': Arquivo ou diretório inexistente
Traceback (most recent call last):
  File "/home/oliveirads/softwares/EDTA/bin/TIR-Learner2.5/Module3_New/CombineAll.py", line 75, in <module>
    f_m3=removeDupinSingle("%s.gff3"%(genome_Name+spliter+"Module3"))
  File "/home/oliveirads/softwares/EDTA/bin/TIR-Learner2.5/Module3_New/CombineAll.py", line 57, in removeDupinSingle
    f=pd.read_csv(file,header=None,sep="\t") #shujun
  File "/home/oliveirads/miniconda3/envs/EDTA/lib/python3.6/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/oliveirads/miniconda3/envs/EDTA/lib/python3.6/site-packages/pandas/io/parsers.py", line 454, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/oliveirads/miniconda3/envs/EDTA/lib/python3.6/site-packages/pandas/io/parsers.py", line 948, in __init__
    self._make_engine(self.engine)
  File "/home/oliveirads/miniconda3/envs/EDTA/lib/python3.6/site-packages/pandas/io/parsers.py", line 1180, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/oliveirads/miniconda3/envs/EDTA/lib/python3.6/site-packages/pandas/io/parsers.py", line 2010, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 540, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/oliveirads/miniconda3/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/oliveirads/miniconda3/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/oliveirads/softwares/EDTA/bin/TIR-Learner2.5/Module3/GetAllSeq.py", line 32, in GetListFromFile
    f=open(file,"r+")
FileNotFoundError: [Errno 2] No such file or directory: 'TIR-Learner_FinalAnn_filter.gff3'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/oliveirads/softwares/EDTA/bin/TIR-Learner2.5/Module3/GetAllSeq.py", line 63, in <module>
    pool.map(GetListFromFile,fileList) #shujun
  File "/home/oliveirads/miniconda3/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/oliveirads/miniconda3/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: 'TIR-Learner_FinalAnn_filter.gff3'
mv: impossível obter estado de 'TIR-Learner/*FinalAnn*.gff3': Arquivo ou diretório inexistente
mv: impossível obter estado de 'TIR-Learner/*FinalAnn*.fa': Arquivo ou diretório inexistente
Can't open ./TIR-Learner-Result/TIR-Learner_FinalAnn.fa: Arquivo ou diretório inexistente at /home/oliveirads/softwares/EDTA/util/rename_tirlearner.pl line 19.
Warning: LOC list Atehyb1.fas.mod.TIR.ext30.list is empty.

Error: Error while loading sequenceCan't open ./TIR-Learner-Result/TIR-Learner_FinalAnn.gff3: Arquivo ou diretório inexistente.
Warning: The TIR result file has 0 bp!

dom dez  4 14:26:54 -03 2022	Start to find Helitron candidates.

dom dez  4 14:26:54 -03 2022	Identify Helitron candidates from scratch.

seg dez  5 06:25:10 -03 2022	Finish finding Helitron candidates.

seg dez  5 06:25:10 -03 2022	Execution of EDTA_raw.pl is finished!

seg dez  5 06:25:10 -03 2022	Obtain raw TE libraries finished.
				All intact TEs found by EDTA: 
					Atehyb1.fas.mod.EDTA.intact.fa
					Atehyb1.fas.mod.EDTA.intact.gff3

seg dez  5 06:25:10 -03 2022	Perform EDTA advance filtering for raw TE candidates and generate the stage 1 library: 

seg dez  5 06:30:54 -03 2022	EDTA advance filtering finished.

Is there any suggestion to fix this problem?

Best regards,

Martins-Junior

**Comment by oushujun** [comment]
Hello Martins-Junior,

Some search indicate this may be an issue of your system's setting. You may want to check this out: https://stackoverflow.com/questions/57507832/unable-to-allocate-array-with-shape-and-data-type

Also, can you also test EDTA with the test data?

Thanks,
Shujun

**Comment by oushujun** [comment]
@AMartinsJr any luck?

**Comment by xxu092** [comment]
@oushujun I am also getting 
```
Traceback (most recent call last):
  File "/bigdata/operations/pkgadmin/opt/linux/centos/8.x/x86_64/pkgs/edta/2.1.0/share/EDTA/bin/TIR-Learner2.5/Module2/RunGRF.py", line 79, in <module>
    if (len(str(records[0].seq))>int(length)+500):
IndexError: list index out of range
```
I tried to `echo 1 > /proc/sys/vm/overcommit_memory` as you suggested above, but as I am running on the cluster, permission was denied. Any other suggestions?

**Comment by oushujun** [comment]
@xxu092 this is a known bug: https://github.com/oushujun/EDTA/issues/281. I have not get a chance to dive deep for a solution.

**Comment by AMartinsJr** [comment]
> @AMartinsJr any luck?

Dear oushujun,
I've runned again with less cores of the server and it works well.
The analysis finished.

Best regards,

Martins-Junior, AMG.

**Comment by AMartinsJr** [comment]
> > @AMartinsJr any luck?
> 
> Dear oushujun, I've runned again with less cores of the server and it works well. The analysis finished.
> 
> Best regards,
> 
> Martins-Junior, AMG.

@oushujun It's very interesting that sometimes the analysis goes ok and in other moments don't. After write the previous comment, I've runned the analysis in a new genome and the same error occurred. Let's try again and hope.

Best regards,

**Comment by oushujun** [comment]
@AMartinsJr  Is this server solely for running EDTA? If CPUs are overutilized, which happens on shared servers, EDTA may run into errors.

Shujun

**Comment by oushujun** [comment]
> > > @AMartinsJr any luck?
> > 
> > 
> > Dear oushujun, I've runned again with less cores of the server and it works well. The analysis finished.
> > Best regards,
> > Martins-Junior, AMG.
> 
> @oushujun It's very interesting that sometimes the analysis goes ok and in other moments don't. After write the previous comment, I've runned the analysis in a new genome and the same error occurred. Let's try again and hope.
> 
> Best regards,

This is a known bug reported in #281 and has been fixed [50f91f1](https://github.com/oushujun/EDTA/commit/50f91f1f8c23188568677f9110b4a168064064c8).

Shujun

**Comment by AMartinsJr** [comment]
Dear Shujun,
Thank you for the returns.
I'll try to run the analysis only when the server is not in use by other
users.
Regards,
Martins-Junior

Em qui., 20 de abr. de 2023 às 11:39, Shujun Ou ***@***.***>
escreveu:

**Comment by oushujun** [comment]
@AMartinsJr Please update EDTA for your next runs. Both the RepeatMasker CPU overutilization and the TIR-Learner sequence ID issue have been fixed.

Shujun
