### ISSUE TITLE
TIR learner files missing error

### ISSUE THREAD

**Issue by katieemelianova** [oushujun/EDTA#365]
Hi there,

I am running EDTA to annotate TEs in some plant genomes, using the --force flag to get around not finding some classes of TEs and also providing a RepeatMasker out file. I seem to be getting a stacktrace showing that there has been an error in the TIR learner module, however the pipeline finishes and creates a *final directory. I wanted to check whether the internal TIR errors I'm getting are a problem, or can safely be ignored? Either way it seems an error is not being properly caught somewhere. Here is my command, followed by the error in questions:

```
cds="/scratch/botany/katie/assembled_genomes/publicly_available/doleifera/Dol.cds.fa"
genome="/scratch/botany/katie/assembled_genomes/assemblies/impolita/working/impolita.fasta"
rmod="/scratch/botany/katie/assembled_genomes/assemblies/impolita/working/impolita.fasta.out"

EDTA.pl --threads 32 --cds $cds --genome $genome --repeatmasker /apps/repeatmasker/4.1.5-3.11.3-5.36.1/RepeatMasker --repeatmodeler /apps/repeatmodeler/2.0.4-5.36.1-1.0.6/RepeatModeler  --force 1 --anno 1 --rmout $rmod
```

```
Mon May 29 10:06:05 CEST 2023   Identify TIR candidates from scratch.

Species: others
Traceback (most recent call last):
  File "/home/user/emelianova/.conda/envs/EDTA/share/EDTA/bin/TIR-Learner2.5/Module2/RunGRF.py", line 79, in <module>
    if (len(str(records[0].seq))>int(length)+500):
IndexError: list index out of range
cp: cannot stat 'TIR-Learner/*-p': No such file or directory
cat: '*-+-DTA.fa': No such file or directory
cat: '*-+-DTC.fa': No such file or directory
cat: '*-+-DTH.fa': No such file or directory
cat: '*-+-DTM.fa': No such file or directory
cat: '*-+-DTT.fa': No such file or directory
cat: '*-+-NonTIR.fa': No such file or directory
cat: '*-+-*-+-*.gff3': No such file or directory
rm: cannot remove '*-+-*-+-*.gff3': No such file or directory
Traceback (most recent call last):
  File "/home/user/emelianova/.conda/envs/EDTA/share/EDTA/bin/TIR-Learner2.5/Module3_New/CombineAll.py", line 75, in <module>
    f_m3=removeDupinSingle("%s.gff3"%(genome_Name+spliter+"Module3"))
  File "/home/user/emelianova/.conda/envs/EDTA/share/EDTA/bin/TIR-Learner2.5/Module3_New/CombineAll.py", line 57, in removeDupinSingle
    f=pd.read_csv(file,header=None,sep="\t") #shujun
  File "/home/user/emelianova/.conda/envs/EDTA/lib/python3.6/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/user/emelianova/.conda/envs/EDTA/lib/python3.6/site-packages/pandas/io/parsers.py", line 454, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/user/emelianova/.conda/envs/EDTA/lib/python3.6/site-packages/pandas/io/parsers.py", line 948, in __init__
    self._make_engine(self.engine)
  File "/home/user/emelianova/.conda/envs/EDTA/lib/python3.6/site-packages/pandas/io/parsers.py", line 1180, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/user/emelianova/.conda/envs/EDTA/lib/python3.6/site-packages/pandas/io/parsers.py", line 2010, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 540, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/user/emelianova/.conda/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/user/emelianova/.conda/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/user/emelianova/.conda/envs/EDTA/share/EDTA/bin/TIR-Learner2.5/Module3/GetAllSeq.py", line 32, in GetListFromFile
    f=open(file,"r+")
FileNotFoundError: [Errno 2] No such file or directory: 'TIR-Learner_FinalAnn_filter.gff3'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/emelianova/.conda/envs/EDTA/share/EDTA/bin/TIR-Learner2.5/Module3/GetAllSeq.py", line 63, in <module>
    pool.map(GetListFromFile,fileList) #shujun
  File "/home/user/emelianova/.conda/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/user/emelianova/.conda/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: 'TIR-Learner_FinalAnn_filter.gff3'
mv: cannot stat 'TIR-Learner/*FinalAnn*.gff3': No such file or directory
mv: cannot stat 'TIR-Learner/*FinalAnn*.fa': No such file or directory
Can't open ./TIR-Learner-Result/TIR-Learner_FinalAnn.fa: No such file or directory at /home/user/emelianova/.conda/envs/EDTA/share/EDTA/util/rename_tirlearner.pl line 19.
Warning: LOC list impolita.fasta.mod.TIR.ext30.list is empty.

Error: Error while loading sequenceCan't open ./TIR-Learner-Result/TIR-Learner_FinalAnn.gff3: No such file or directory.
Warning: The TIR result file has 0 bp!
```

Thanks in advance for your help! :)

Best,

Katie

**Comment by katieemelianova** [comment]
Hi Shujun,

apologies for not spotting that and thanks very much for the info, I’ll update my version of EDTA :)

Best,

Katie

**Comment by wch150667** [comment]
> 嗨，凯蒂，
> 
> 很抱歉回复晚了。这是一个已修复的错误 （#354 #281）。请使用 EDTA 的 github 版本（git clone 并指定要 EDTA.pl 路径）并再次运行。另一个简单的解决方法是将序列 ID 重命名为以字母开头，以便 python 认为这是一个字符串而不是数字。
> 
> 最好的，舒军

I changed the name of my sequence ID to contig1---contig8443, but what should I do if I still get an error?

**Comment by oushujun** [comment]
Please update your EDTA.

Shujun
