### ISSUE TITLE
TIR-Learner error

### ISSUE THREAD

**Issue by amandine-velt** [oushujun/EDTA#478]
Hello,

I installed EDTA by cloning this repo and launching : 
 
`mamba env create -f EDTA_2.2.x.yml`

EDTA works on test data. But on my genome (plant genome of 450Mb size), it generates this error. It seems there is a problem with TIR-Learner but I don't understand why. Can you help me please ? 

Here the command I launched : 

`/EDTA/EDTA.pl --genome $GENOME --species others --step all --sensitive 1 --anno 1 --overwrite 1 --threads $THREADS`

Here the log :

  ```
Thu Jul  4 01:39:10 UTC 2024  Identify TIR candidates from scratch.

  Species: others
  Traceback (most recent call last):
    File "/EDTA/bin/TIR-Learner3.0/bin/main.py", line 260, in load_checkpoint_file
      execution_progress_info = json.loads(checkpoint_info_file.readline().rstrip())
    File "/opt/conda/envs/EDTA2/lib/python3.9/json/__init__.py", line 346, in loads
      return _default_decoder.decode(s)
    File "/opt/conda/envs/EDTA2/lib/python3.9/json/decoder.py", line 340, in decode
      raise JSONDecodeError("Extra data", s, end)
  json.decoder.JSONDecodeError: Extra data: line 1 column 2 (char 1)

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/EDTA/bin/TIR-Learner3.0/TIR-Learner3.0.py", line 80, in <module>
      TIRLearner_instance = TIRLearner(genome_file, genome_name, species, TIR_length,
    File "/EDTA/bin/TIR-Learner3.0/bin/main.py", line 81, in __init__
      self.execute()
    File "/EDTA/bin/TIR-Learner3.0/bin/main.py", line 111, in execute
      self.load_checkpoint_file()
    File "/EDTA/bin/TIR-Learner3.0/bin/main.py", line 311, in load_checkpoint_file
      self.reset_checkpoint_load_state(f"WARN: Checkpoint file invalid, \"{df_file_name}.csv\" is empty. "
  UnboundLocalError: local variable 'df_file_name' referenced before assignment
  Can't open ./TIR-Learner-Result/TIR-Learner_FinalAnn.fa: No such file or directory at /EDTA/util/rename_tirlearner.pl line 19.
  Warning: LOC list Chinese_ref_v2.fa.mod.TIR.ext30.list is empty.

  Error: Error while loading sequence
  Filter sequence based on TEsorter classifications. Unclassified sequences will also be output to the clean file.
        Usage: perl cleanup_misclas.pl sequence.fa.rexdb.cls.tsv
        Author: Shujun Ou (shujun.ou.1@gmail.com) 10/11/2019

  mv: cannot stat 'Chinese_ref_v2.fa.mod.TIR.ext30.fa.pass.fa.dusted.cln.cln': No such file or directory
  cp: cannot stat 'Chinese_ref_v2.fa.mod.TIR.ext30.fa.pass.fa.dusted.cln.cln.list': No such file or directory
  cp: cannot stat 'Chinese_ref_v2.fa.mod.TIR.intact.raw.fa.anno.list': No such file or directory
  Can't open ./TIR-Learner-Result/TIR-Learner_FinalAnn.gff3: No such file or directory.
  ERROR: No such file or directory at /EDTA/util/output_by_list.pl line 39.
  Warning: The TIR result file has 0 bp!

  Thu Jul  4 01:40:18 UTC 2024  Start to find Helitron candidates.

  Thu Jul  4 01:40:18 UTC 2024  Identify Helitron candidates from scratch.

  Thu Jul  4 04:12:17 UTC 2024  Finish finding Helitron candidates.

  Thu Jul  4 04:12:17 UTC 2024  Execution of EDTA_raw.pl is finished!

  ERROR: Raw TIR results not found in Chinese_ref_v2.fa.mod.EDTA.raw/Chinese_ref_v2.fa.mod.TIR.intact.raw.fa
        If you believe the program is working properly, this may be caused by the lack of intact TIRs in your genome. Consider to use the --force 1 parameter to overwrite this check


```

**Comment by amandine-velt** [comment]
The problem came from the OS I was using when creating the Docker image (Ubuntu). Using rockylinux:9, the EDTA run works well.

**Comment by FayeFang17** [comment]
Hey, have you installed EDTA successfully? If not, currently I recommend installing by specifying all dependencies:
mamba create -n EDTA2.2 -c conda-forge -c bioconda -c r annosine2 biopython blast cd-hit coreutils genericrepeatfinder genometools-genometools glob2 h5py==3.9 keras==2.11 ltr_finder ltr_retriever mdust multiprocess muscle openjdk pandas perl perl-text-soundex pyarrow python r-base r-dplyr regex repeatmodeler r-ggplot2 r-here r-tidyr scikit-learn swifter tensorflow==2.11 tesorter

Let me know if you succeed.!

Best,
Faye

**Comment by amandine-velt** [comment]
Hello
As I said in my previous post, EDTA was generating this error on Ubuntu 16.04, and testing on rockylinux:9 it's OK now, it works fine.
Have a nice day
Amandine

**Comment by afurches** [comment]
Hi, I am getting this error. I am running EDTA on Linux Red Hat HPC cluster. I followed the same install directions as the OP above (git clone, mamba create env -f yml). Thanks!

**Comment by afurches** [comment]
UPDATE:
I resolved the error by deleting the TIR directory from the previous run. For some reason the files created in the previous run were causing this error. 

Thanks,
Anna
