### ISSUE TITLE
ERROR: Identify TIR candidates from scratch

### ISSUE THREAD

**Issue by Lee951108** [oushujun/EDTA#482]
Dear Dr. Ou，
I got an error，when i run the EDTA.pl for a plant genome. Please help me to figure this out.

Tue Jul 16 11:17:49 CST 2024 EDTA_raw: Check dependencies, prepare working directories.

Tue Jul 16 11:18:05 CST 2024 Start to find LTR candidates.

Tue Jul 16 11:18:05 CST 2024 Existing result file Zm-B73-REFERENCE-NAM-5.0.fa.mod.LTR.raw.fa found!
Will keep this file without rerunning this module.
Please specify --overwrite 1 if you want to rerun this module.

Tue Jul 16 11:18:06 CST 2024 Finish finding LTR candidates.

Tue Jul 16 11:18:06 CST 2024 Start to find SINE candidates.

Tue Jul 16 11:18:06 CST 2024 Existing result file Seed_SINE.fa found!
Will keep this file without rerunning this module.
Please specify --overwrite 1 if you want to rerun AnnoSINE_v2.

Tue Jul 16 11:18:14 CST 2024 Finish finding SINE candidates.

Tue Jul 16 11:18:14 CST 2024 Start to find LINE candidates.

Tue Jul 16 11:18:14 CST 2024 Existing result file Zm-B73-REFERENCE-NAM-5.0.fa.mod-families.fa found!
Will keep this file without rerunning this module.
Please specify --overwrite 1 if you want to rerun this module.

Use of uninitialized value in string ne at /share/home/caas_lws/software/EDTA-2.2.0/util/cleanup_misclas.pl line 61, <Clas> line 176.
Use of uninitialized value within %lib in string ne at /share/home/caas_lws/software/EDTA-2.2.0/util/cleanup_misclas.pl line 61, <Clas> line 176.
Tue Jul 16 11:18:20 CST 2024 Finish finding LINE candidates.

Tue Jul 16 11:18:20 CST 2024 Start to find TIR candidates.

Tue Jul 16 11:18:20 CST 2024 Identify TIR candidates from scratch.

Species: Maize
Process ForkPoolWorker-44:
Process ForkPoolWorker-43:
Process ForkPoolWorker-41:
Process ForkPoolWorker-42:
Process ForkPoolWorker-40:
Process ForkPoolWorker-39:
Process ForkPoolWorker-38:
Process ForkPoolWorker-37:
Traceback (most recent call last):
File "/share/home/caas_lws/miniconda3/envs/EDTA/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
self.run()
File "/share/home/caas_lws/miniconda3/envs/EDTA/lib/python3.10/multiprocessing/process.py", line 108, in run
self._target(*self._args, **self._kwargs)
File "/share/home/caas_lws/miniconda3/envs/EDTA/lib/python3.10/multiprocessing/pool.py", line 114, in worker
task = get()
File "/share/home/caas_lws/miniconda3/envs/EDTA/lib/python3.10/multiprocessing/queues.py", line 365, in get
res = self._reader.recv_bytes()
File "/share/home/caas_lws/miniconda3/envs/EDTA/lib/python3.10/multiprocessing/connection.py", line 216, in recv_bytes
buf = self._recv_bytes(maxlength)
File "/share/home/caas_lws/miniconda3/envs/EDTA/lib/python3.10/multiprocessing/connection.py", line 414, in _recv_bytes
buf = self._recv(4)
File "/share/home/caas_lws/miniconda3/envs/EDTA/lib/python3.10/multiprocessing/connection.py", line 379, in _recv
chunk = read(handle, remaining)
KeyboardInterrupt
Traceback (most recent call last):
File "/share/home/caas_lws/miniconda3/envs/EDTA/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
self.run()
File "/share/home/caas_lws/miniconda3/envs/EDTA/lib/python3.10/multiprocessing/process.py", line 108, in run
self._target(*self._args, **self._kwargs)
File "/share/home/caas_lws/miniconda3/envs/EDTA/lib/python3.10/multiprocessing/pool.py", line 114, in worker
task = get()
File "/share/home/caas_lws/miniconda3/envs/EDTA/lib/python3.10/multiprocessing/queues.py", line 364, in get
with self._rlock:
File "/share/home/caas_lws/miniconda3/envs/EDTA/lib/python3.10/multiprocessing/synchronize.py", line 95, in enter
return self._semlock.enter()
KeyboardInterrupt
Traceback (most recent call last):
Traceback (most recent call last):
File "/share/home/caas_lws/miniconda3/envs/EDTA/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
self.run()
File "/share/home/caas_lws/miniconda3/envs/EDTA/lib/python3.10/multiprocessing/process.py", line 108, in run
self._target(*self._args, **self._kwargs)
File "/share/home/caas_lws/miniconda3/envs/EDTA/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
self.run()
File "/share/home/caas_lws/miniconda3/envs/EDTA/lib/python3.10/multiprocessing/pool.py", line 114, in worker
task = get()
File "/share/home/caas_lws/miniconda3/envs/EDTA/lib/python3.10/multiprocessing/process.py", line 108, in run
self._target(*self._args, **self._kwargs)
File "/share/home/caas_lws/miniconda3/envs/EDTA/lib/python3.10/multiprocessing/queues.py", line 364, in get
with self._rlock:
File "/share/home/caas_lws/miniconda3/envs/EDTA/lib/python3.10/multiprocessing/pool.py", line 114, in worker
task = get()
File "/share/home/caas_lws/miniconda3/envs/EDTA/lib/python3.10/multiprocessing/synchronize.py", line 95, in enter
return self._semlock.enter()
File "/share/home/caas_lws/miniconda3/envs/EDTA/lib/python3.10/multiprocessing/queues.py", line 364, in get
with self._rlock:
Traceback (most recent call last):
File "/share/home/caas_lws/miniconda3/envs/EDTA/lib/python3.10/multiprocessing/synchronize.py", line 95, in enter
return self._semlock.enter()
KeyboardInterrupt
Traceback (most recent call last):
KeyboardInterrupt
Traceback (most recent call last):
File "/share/home/caas_lws/miniconda3/envs/EDTA/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
self.run()
Traceback (most recent call last):
File "/share/home/caas_lws/miniconda3/envs/EDTA/lib/python3.10/multiprocessing/process.py", line 108, in run
self._target(*self._args, **self._kwargs)
File "/share/home/caas_lws/miniconda3/envs/EDTA/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
self.run()
File "/share/home/caas_lws/miniconda3/envs/EDTA/lib/python3.10/multiprocessing/pool.py", line 114, in worker
task = get()
File "/share/home/caas_lws/miniconda3/envs/EDTA/lib/python3.10/multiprocessing/process.py", line 108, in run
self._target(*self._args, **self._kwargs)
File "/share/home/caas_lws/miniconda3/envs/EDTA/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
self.run()
File "/share/home/caas_lws/miniconda3/envs/EDTA/lib/python3.10/multiprocessing/queues.py", line 364, in get
with self._rlock:
File "/share/home/caas_lws/miniconda3/envs/EDTA/lib/python3.10/multiprocessing/pool.py", line 114, in worker
task = get()
File "/share/home/caas_lws/miniconda3/envs/EDTA/lib/python3.10/multiprocessing/process.py", line 108, in run
self._target(*self._args, **self._kwargs)
File "/share/home/caas_lws/miniconda3/envs/EDTA/lib/python3.10/multiprocessing/synchronize.py", line 95, in enter
return self._semlock.enter()
File "/share/home/caas_lws/miniconda3/envs/EDTA/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
self.run()
File "/share/home/caas_lws/miniconda3/envs/EDTA/lib/python3.10/multiprocessing/queues.py", line 364, in get
with self._rlock:
File "/share/home/caas_lws/miniconda3/envs/EDTA/lib/python3.10/multiprocessing/pool.py", line 114, in worker
task = get()
File "/share/home/caas_lws/miniconda3/envs/EDTA/lib/python3.10/multiprocessing/process.py", line 108, in run
self._target(*self._args, **self._kwargs)
File "/share/home/caas_lws/miniconda3/envs/EDTA/lib/python3.10/multiprocessing/synchronize.py", line 95, in enter
return self._semlock.enter()
KeyboardInterrupt
File "/share/home/caas_lws/miniconda3/envs/EDTA/lib/python3.10/multiprocessing/queues.py", line 364, in get
with self._rlock:
File "/share/home/caas_lws/miniconda3/envs/EDTA/lib/python3.10/multiprocessing/pool.py", line 114, in worker
task = get()
File "/share/home/caas_lws/miniconda3/envs/EDTA/lib/python3.10/multiprocessing/synchronize.py", line 95, in enter
return self._semlock.enter()
KeyboardInterrupt
File "/share/home/caas_lws/miniconda3/envs/EDTA/lib/python3.10/multiprocessing/queues.py", line 364, in get
with self._rlock:
File "/share/home/caas_lws/miniconda3/envs/EDTA/lib/python3.10/multiprocessing/synchronize.py", line 95, in enter
return self._semlock.enter()
KeyboardInterrupt
KeyboardInterrupt
Exception ignored in: <function _releaseLock at 0x2b577292dea0>
Traceback (most recent call last):
File "/share/home/caas_lws/miniconda3/envs/EDTA/lib/python3.10/logging/init.py", line 228, in _releaseLock
def _releaseLock():
KeyboardInterrupt:
Job 11314233 stderr output:

**Comment by santoshdu** [comment]
Dear Dr. Ou，
I   also got similar error，when i run the EDTA.pl for a plant genome. Please help me to figure this out.

**Comment by FayeFang17** [comment]
May I ask what method did you use to install EDTA?

**Comment by Lee951108** [comment]
I reinstall the EDTA. No error occur. Thanks!
