### ISSUE TITLE
Fails on identification of TIRs

### ISSUE THREAD

**Issue by pjm43** [oushujun/EDTA#49]
Shujun,

I've installed the Docker version to our HPC.  EDTA progesses through the LTR finding, but then crashes when trying to identify the TIR.  I'm pasting in the full slurm below.  Any help would be greatly appreciated. 
Thanks, Jeff

```##### Extensive de-novo TE Annotator (EDTA) v1.7.1    ####
> ##### Shujun Ou (shujun.ou.1@gmail.com)             ####
> ########################################################
>
>
>
> Fri Jan 24 02:09:53 UTC 2020    Dependency checking:
>                                 All passed!
> Fri Jan 24 02:10:03 UTC 2020    Obtain raw TE libraries using various structure-based programs:
> Fri Jan 24 02:10:03 UTC 2020    EDTA_raw: Check files and dependencies, prepare working directories.
>
> Fri Jan 24 02:10:03 UTC 2020    Start to find LTR candidates.
>
> Fri Jan 24 02:10:03 UTC 2020    Identify LTR retrotransposon candidates from scratch.
>
> Warning: LOC list ordered_atriplex_hortensis_04Apr2019_hkF1T_namedcorrectly_clean_00.fasta.mod.ltrTE.veryfalse is empty.
> Fri Jan 24 02:27:35 UTC 2020    Finish finding LTR candidates.
>
> Fri Jan 24 02:27:35 UTC 2020    Start to find TIR candidates.
>
> Fri Jan 24 02:27:35 UTC 2020    Identify TIR candidates from scratch.
>
> Species: others
> 2020-01-24 02:55:41.202424: F tensorflow/python/lib/core/bfloat16.cc:675] Check failed: PyBfloat16_Type.tp_base != nullptr
> Aborted (core dumped)
> cat: '*-+-DTA.fa': No such file or directory
> cat: '*-+-DTC.fa': No such file or directory
> cat: '*-+-DTH.fa': No such file or directory
> cat: '*-+-DTM.fa': No such file or directory
> cat: '*-+-DTT.fa': No such file or directory
> cat: '*-+-NonTIR.fa': No such file or directory
> cat: '*-+-*-+-*.gff3': No such file or directory
> rm: cannot remove '*-+-*-+-*.gff3': No such file or directory
> Traceback (most recent call last):
>   File "/EDTA/bin/TIR-Learner2.4/Module3_New/CombineAll.py", line 75, in <module>
>     f_m3=removeDupinSingle("%s.gff3"%(genome_Name+spliter+"Module3"))
>   File "/EDTA/bin/TIR-Learner2.4/Module3_New/CombineAll.py", line 57, in removeDupinSingle
>     f=pd.read_csv(file,header=None,sep="\t") #shujun
>   File "/opt/conda/lib/python3.6/site-packages/pandas/io/parsers.py", line 685, in parser_f
>     return _read(filepath_or_buffer, kwds)
>   File "/opt/conda/lib/python3.6/site-packages/pandas/io/parsers.py", line 457, in _read
>     parser = TextFileReader(fp_or_buf, **kwds)
>   File "/opt/conda/lib/python3.6/site-packages/pandas/io/parsers.py", line 895, in __init__
>     self._make_engine(self.engine)
>   File "/opt/conda/lib/python3.6/site-packages/pandas/io/parsers.py", line 1135, in _make_engine
>     self._engine = CParserWrapper(self.f, **self.options)
>   File "/opt/conda/lib/python3.6/site-packages/pandas/io/parsers.py", line 1917, in __init__
>     self._reader = parsers.TextReader(src, **kwds)
>   File "pandas/_libs/parsers.pyx", line 545, in pandas._libs.parsers.TextReader.__cinit__
> pandas.errors.EmptyDataError: No columns to parse from file
> multiprocessing.pool.RemoteTraceback:
> """
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.6/multiprocessing/pool.py", line 119, in worker
>     result = (True, func(*args, **kwds))
>   File "/opt/conda/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
>     return list(map(*args))
>   File "/EDTA/bin/TIR-Learner2.4/Module3/GetAllSeq.py", line 32, in GetListFromFile
>     f=open(file,"r+")
> FileNotFoundError: [Errno 2] No such file or directory: 'TIR-Learner_FinalAnn.gff3'
> """
>
> The above exception was the direct cause of the following exception:
>
> Traceback (most recent call last):
>   File "/EDTA/bin/TIR-Learner2.4/Module3/GetAllSeq.py", line 63, in <module>
>     pool.map(GetListFromFile,fileList) #shujun
>   File "/opt/conda/lib/python3.6/multiprocessing/pool.py", line 266, in map
>     return self._map_async(func, iterable, mapstar, chunksize).get()
>   File "/opt/conda/lib/python3.6/multiprocessing/pool.py", line 644, in get
>     raise self._value
> FileNotFoundError: [Errno 2] No such file or directory: 'TIR-Learner_FinalAnn.gff3'
> mv: cannot stat 'TIR-Learner/*FinalAnn*.gff3': No such file or directory
> mv: cannot stat 'TIR-Learner/*FinalAnn*.fa': No such file or directory
> Can't open ./TIR-Learner-Result/TIR-Learner_FinalAnn.fa: No such file or directory at /EDTA/util/rename_tirlearner.pl line 18.
> Warning: LOC list ordered_atriplex_hortensis_04Apr2019_hkF1T_namedcorrectly_clean_00.fasta.TIR.ext30.list is empty.
>
> Error: Error while loading sequenceCan't open ./TIR-Learner-Result/TIR-Learner_FinalAnn.gff3: No such file or directory.
> Warning: The TIR result file has 0 bp!
>
> Fri Jan 24 02:55:51 UTC 2020    Start to find Helitron candidates.
>
> Fri Jan 24 02:55:51 UTC 2020    Identify Helitron candidates from scratch.
>
> Fri Jan 24 03:49:16 UTC 2020    Finish finding Helitron candidates.
>
> Fri Jan 24 03:49:16 UTC 2020    Execution of EDTA_raw.pl is finished!
>
> ERROR: Raw TIR results not found in ordered_atriplex_hortensis_04Apr2019_hkF1T_namedcorrectly_clean_00.fasta.EDTA.raw/ordered_atriplex_hortensis_04Apr2019_hkF1T_namedcorrectly_clean_00.fasta.TIR.raw.fa at /EDTA/EDTA.pl line 285.
> cleaning up image```

**Comment by oushujun** [comment]
Seems like python is not correctly installed. You may try the conda
version. LTR is a bit strange too. How large is your genome?

**Comment by pjm43** [comment]
Thanks for the quick reply.  I am just testing to make sure the install was correct - so the data set was a single chromosome, ~113Mb.  

I've tried the conda version, but had similar issues at the TIR stage, hence the effort to install using the docker.  When I reached out to our HPC team, they said that the error was occurring within the container and that perhaps a pip install was missing in the Dockerfile or something.  Any ideas?

**Comment by oushujun** [comment]
The conda version v1.7.1 is a bit outdated. You may want to use the
cutrrent v1.7.4 version (conda), which should have the pip install issue
solved.

**Comment by michaelgreenburg** [comment]
I'm helping @pjm43 get EDTA working. Will the Docker container be updated to use 1.7.4 soon? According to DockerHub it was last updated 17 days ago while 1.7.4 was released more recently.

**Comment by oushujun** [comment]
Hello @pjm43 @michaelgreenburg 

Sorry for the delay. We just updated the Docker container to v1.7.7. Please update and try again.

Best,
Shujun
