### ISSUE TITLE
TIR-Learner error

### ISSUE THREAD

**Issue by qfh20m20m** [oushujun/EDTA#505]
**Hello，
I installed it using the method you recommended：**

> 
`mamba create -n EDTA2.2 -c conda-forge -c bioconda -c r annosine2 biopython cd-hit coreutils genericrepeatfinder genometools-genometools glob2 tir-learner ltr_finder_parallel ltr_retriever mdust multiprocess muscle openjdk perl perl-text-soundex r-base r-dplyr regex repeatmodeler r-ggplot2 r-here r-tidyr tesorter samtools bedtools LTR_HARVEST_parallel HelitronScanner -y
`
**The following error occurred while running the test data**：

> 
```
perl ../EDTA.pl --genome genome.fa --cds genome.cds.fa --curatedlib ../database/rice7.0.0.liban --exclude genome.exclude.bed --overwrite 1 --sensitive 1 --anno 1 --threads 10 > test.log
Fri Sep 13 19:54:56 HKT 2024    EDTA_raw: Check dependencies, prepare working directories.
Fri Sep 13 19:54:58 HKT 2024    Start to find LTR candidates.
Fri Sep 13 19:54:58 HKT 2024    Identify LTR retrotransposon candidates from scratch.
Warning: LOC list genome.fa.mod.ltrTE.veryfalse is empty.

Fri Sep 13 19:55:25 HKT 2024    Finish finding LTR candidates.
Fri Sep 13 19:55:25 HKT 2024    Start to find SINE candidates.
Fri Sep 13 19:56:20 HKT 2024    Warning: The SINE result file has 0 bp!
Fri Sep 13 19:56:20 HKT 2024    Start to find LINE candidates.
Fri Sep 13 19:56:20 HKT 2024    Identify LINE retrotransposon candidates from scratch.
Fri Sep 13 19:58:07 HKT 2024    Warning: The LINE result file has 0 bp!
Fri Sep 13 19:58:07 HKT 2024    Start to find TIR candidates.
Fri Sep 13 19:58:07 HKT 2024    Identify TIR candidates from scratch.
Species: others
Traceback (most recent call last):
  File "/nfs_fs/nfs1/pengxiaochang/software/EDTA/bin/TIR-Learner3.0/TIR-Learner3.0.py", line 14, in <module>
    from bin.main import TIRLearner
  File "/nfs_fs/nfs1/pengxiaochang/software/EDTA/bin/TIR-Learner3.0/bin/main.py", line 22, in <module>
    from prog_const import *
  File "/nfs_fs/nfs1/pengxiaochang/software/EDTA/bin/TIR-Learner3.0/bin/prog_const.py", line 29, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'
Can't open ./TIR-Learner-Result/TIR-Learner_FinalAnn.fa: No such file or directory at /nfs_fs/nfs1/pengxiaochang/software/EDTA/util/rename_tirlearner.pl line 19.
Warning: LOC list genome.fa.mod.TIR.ext30.list is empty.

Error: Error while loading sequence
Filter sequence based on TEsorter classifications. Unclassified sequences will also be output to the clean file.
        Usage: perl cleanup_misclas.pl sequence.fa.rexdb.cls.tsv
        Author: Shujun Ou (shujun.ou.1@gmail.com) 10/11/2019
mv: cannot stat 'genome.fa.mod.TIR.ext30.fa.pass.fa.dusted.cln.cln': No such file or directory
cp: cannot stat 'genome.fa.mod.TIR.ext30.fa.pass.fa.dusted.cln.cln.list': No such file or directory
cp: cannot stat 'genome.fa.mod.TIR.intact.raw.fa.anno.list': No such file or directory
Can't open ./TIR-Learner-Result/TIR-Learner_FinalAnn.gff3: No such file or directory.
ERROR: No such file or directory at /nfs_fs/nfs1/pengxiaochang/software/EDTA/util/output_by_list.pl line 39.
Error: TIR results not found!
ERROR: Raw TIR results not found in genome.fa.mod.EDTA.raw/genome.fa.mod.TIR.intact.raw.fa
        If you believe the program is working properly, this may be caused by the lack of intact TIRs in your genome. Consider to use the --force 1 parameter to overwrite this check
```

**When I run my data, I can predict the LTR, but the TIR prediction still gives an error：**

> 
```
perl /nfs_fs/nfs1/pengxiaochang/software/EDTA/EDTA.pl --genome Hedychium_hic.post.FINAL.fa --species others --overwrite 1 --sensitive 1 --anno 1 --threads 20 > test.log
Fri Sep 13 20:06:24 HKT 2024    EDTA_raw: Check dependencies, prepare working directories.
Fri Sep 13 20:06:41 HKT 2024    Start to find LTR candidates.
Fri Sep 13 20:06:41 HKT 2024    Identify LTR retrotransposon candidates from scratch.
Fri Sep 13 22:03:32 HKT 2024    Finish finding LTR candidates.
Fri Sep 13 22:03:32 HKT 2024    Start to find SINE candidates.
Sat Sep 14 00:44:59 HKT 2024    Finish finding SINE candidates.
Sat Sep 14 00:44:59 HKT 2024    Start to find LINE candidates.
Sat Sep 14 00:44:59 HKT 2024    Identify LINE retrotransposon candidates from scratch.
Sun Sep 15 03:14:29 HKT 2024    Finish finding LINE candidates.
Sun Sep 15 03:14:29 HKT 2024    Start to find TIR candidates.
Sun Sep 15 03:14:29 HKT 2024    Identify TIR candidates from scratch.
Species: others
Traceback (most recent call last):
  File "/nfs_fs/nfs1/pengxiaochang/software/EDTA/bin/TIR-Learner3.0/TIR-Learner3.0.py", line 14, in <module>
    from bin.main import TIRLearner
  File "/nfs_fs/nfs1/pengxiaochang/software/EDTA/bin/TIR-Learner3.0/bin/main.py", line 22, in <module>
    from prog_const import *
  File "/nfs_fs/nfs1/pengxiaochang/software/EDTA/bin/TIR-Learner3.0/bin/prog_const.py", line 29, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'
Can't open ./TIR-Learner-Result/TIR-Learner_FinalAnn.fa: No such file or directory at /nfs_fs/nfs1/pengxiaochang/software/EDTA/util/rename_tirlearner.pl line 19.
Warning: LOC list Hedychium_hic.post.FINAL.fa.mod.TIR.ext30.list is empty.

Error: Error while loading sequence
Filter sequence based on TEsorter classifications. Unclassified sequences will also be output to the clean file.
        Usage: perl cleanup_misclas.pl sequence.fa.rexdb.cls.tsv
        Author: Shujun Ou (shujun.ou.1@gmail.com) 10/11/2019
mv: cannot stat 'Hedychium_hic.post.FINAL.fa.mod.TIR.ext30.fa.pass.fa.dusted.cln.cln': No such file or directory
cp: cannot stat 'Hedychium_hic.post.FINAL.fa.mod.TIR.ext30.fa.pass.fa.dusted.cln.cln.list': No such file or directory
cp: cannot stat 'Hedychium_hic.post.FINAL.fa.mod.TIR.intact.raw.fa.anno.list': No such file or directory
Can't open ./TIR-Learner-Result/TIR-Learner_FinalAnn.gff3: No such file or directory.
ERROR: No such file or directory at /nfs_fs/nfs1/pengxiaochang/software/EDTA/util/output_by_list.pl line 39.
Error: TIR results not found!
ERROR: Raw TIR results not found in Hedychium_hic.post.FINAL.fa.mod.EDTA.raw/Hedychium_hic.post.FINAL.fa.mod.TIR.intact.raw.fa
        If you believe the program is working properly, this may be caused by the lack of intact TIRs in your genome. Consider to use the --force 1 parameter to overwrite this check
```

Hope to get your help, thanks!

**Comment by oushujun** [comment]
You installed the test branch for dependencies but used the master branch
of the program - they do not match.

Run git checkout EDTA2 on your program folder should solve it

Shujun

**Comment by oushujun** [comment]
#497
