### ISSUE TITLE
Error with add -w $genome_file_real_path.EDTA.raw/TIR

### ISSUE THREAD

**Issue by lpzoaa** [oushujun/EDTA#512]
HI Shujun,

I built EDTA2 following your recommendation (https://github.com/oushujun/EDTA/issues/497#issuecomment-2396852358), but I encountered an error during the TIR step.
`mkdir: cannot create directory ‘TIR-Learner_GRFmite’: No space left on device
mkdir: cannot create directory ‘TIR-Learner_GRFmite’: No space left on device
can't open file: TIR-Learner_GRFmite/candidate.fasta
mkdir: cannot create directory ‘TIR-Learner_GRFmite’: No space left on device
mkdir: cannot create directory ‘TIR-Learner_GRFmite’: No space left on device
can't open file: TIR-Learner_GRFmite/candidate.fasta
can't open file: TIR-Learner_GRFmite/candidate.fasta
can't open file: TIR-Learner_GRFmite/candidate.fasta
can't open file: TIR-Learner_GRFmite/candidate.fasta
mkdir: cannot create directory ‘TIR-Learner_GRFmite’: No space left on device
mkdir: cannot create directory ‘TIR-Learner_GRFmite’: No space left on device
can't open file: TIR-Learner_GRFmite/candidate.fasta
can't open file: TIR-Learner_GRFmite/candidate.fasta
mkdir: cannot create directory ‘TIR-Learner_GRFmite’: No space left on device`
Then  I added -w $genome_file_real_path.EDTA.raw/TIR to EDTA_raw.pl(https://github.com/oushujun/EDTA/issues/327#issuecomment-1940950826), but a new error occurred
`libgomp: Thread creation failed: Resource temporarily unavailable

libgomp: Thread creation failed: Resource temporarily unavailable

libgomp: Thread creation failed: Resource temporarily unavailable
/bin/sh: fork: retry: No child processes

libgomp: Thread creation failed: Resource temporarily unavailable

libgomp: 
libgomp: Thread creation failed: Resource temporarily unavailable
Thread creation failed: Resource temporarily unavailable
can't open file: TIR-Learner_GRFmite/candidate.fasta
can't open file: TIR-Learner_GRFmite/candidate.fasta
can't open file: TIR-Learner_GRFmite/candidate.fasta
can't open file: TIR-Learner_GRFmite/candidate.fasta
can't open file: TIR-Learner_GRFmite/candidate.fasta
can't open file: TIR-Learner_GRFmite/candidate.fasta
can't open file: TIR-Learner_GRFmite/candidate.fasta
can't open file: TIR-Learner_GRFmite/candidate.fasta
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/work/home/acn95ttd5d/mambaforge/envs/EDTA2/lib/python3.12/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/work/home/acn95ttd5d/mambaforge/envs/EDTA2/lib/python3.12/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/home/acn95ttd5d/mambaforge/envs/EDTA2/share/TIR-Learner3/bin/run_GRF.py", line 36, in GRF_mp
    GRF(genome_file_name, genome_name, cpu_cores, TIR_length, GRF_path)
  File "/work/home/acn95ttd5d/mambaforge/envs/EDTA2/share/TIR-Learner3/bin/run_GRF.py", line 29, in GRF
    subprocess.Popen(grf + shell_filter, shell=True).wait()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/home/acn95ttd5d/mambaforge/envs/EDTA2/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/work/home/acn95ttd5d/mambaforge/envs/EDTA2/lib/python3.12/subprocess.py", line 1885, in _execute_child
    self.pid = _fork_exec(
               ^^^^^^^^^^^
BlockingIOError: [Errno 11] Resource temporarily unavailable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/work/home/acn95ttd5d/mambaforge/envs/EDTA2/share/TIR-Learner3/TIR-Learner.py", line 95, in <module>
    TIRLearner_instance = TIRLearner(genome_file, genome_name, species, TIR_length,
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/home/acn95ttd5d/mambaforge/envs/EDTA2/share/TIR-Learner3/bin/main.py", line 91, in __init__
    self.execute()
  File "/work/home/acn95ttd5d/mambaforge/envs/EDTA2/share/TIR-Learner3/bin/main.py", line 131, in execute
    self.execute_M4()
  File "/work/home/acn95ttd5d/mambaforge/envs/EDTA2/share/TIR-Learner3/bin/main.py", line 598, in execute_M4
    self["GRF"] = run_GRF.execute(self)
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/work/home/acn95ttd5d/mambaforge/envs/EDTA2/share/TIR-Learner3/bin/run_GRF.py", line 182, in execute
    return run_GRF_py_para(genome_file, genome_name, TIR_length, cpu_cores, para_mode, flag_debug, GRF_path,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/home/acn95ttd5d/mambaforge/envs/EDTA2/share/TIR-Learner3/bin/run_GRF.py", line 82, in run_GRF_py_para
    pool.starmap(GRF_mp, mp_args_list)
  File "/work/home/acn95ttd5d/mambaforge/envs/EDTA2/lib/python3.12/multiprocessing/pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/home/acn95ttd5d/mambaforge/envs/EDTA2/lib/python3.12/multiprocessing/pool.py", line 774, in get
    raise self._value
  File "/work/home/acn95ttd5d/mambaforge/envs/EDTA2/lib/python3.12/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
^^^^^^^^^^^^^^^
  File "/work/home/acn95ttd5d/mambaforge/envs/EDTA2/lib/python3.12/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
      ^^^^^^^^^^^^^^^^^
  File "/work/home/acn95ttd5d/mambaforge/envs/EDTA2/share/TIR-Learner3/bin/run_GRF.py", line 36, in GRF_mp
    GRF(genome_file_name, genome_name, cpu_cores, TIR_length, GRF_path)
      ^^^^^^^^^^^^^^^^^
  File "/work/home/acn95ttd5d/mambaforge/envs/EDTA2/share/TIR-Learner3/bin/run_GRF.py", line 29, in GRF
    subprocess.Popen(grf + shell_filter, shell=True).wait()
      ^^^^^^^^^^^^^^^^^
  File "/work/home/acn95ttd5d/mambaforge/envs/EDTA2/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
^^^^^^^^^^^^^^^
  File "/work/home/acn95ttd5d/mambaforge/envs/EDTA2/lib/python3.12/subprocess.py", line 1885, in _execute_child
    self.pid = _fork_exec(
^^^^^^^
BlockingIOError: [Errno 11] Resource temporarily unavailable
Can't open ./TIR-Learner-Result/TIR-Learner_FinalAnn.fa: No such file or directory at /work/home/acn95ttd5d/software/EDTA/bin/rename_tirlearner.pl line 19.
Warning: LOC list Nasik_red.fa.mod.TIR.ext30.list is empty.

Error: Error while loading sequence
Filter sequence based on TEsorter classifications. Unclassified sequences will also be output to the clean file.
        Usage: perl cleanup_misclas.pl sequence.fa.rexdb.cls.tsv
        Author: Shujun Ou (shujun.ou.1@gmail.com) 10/11/2019

mv: cannot stat 'Nasik_red.fa.mod.TIR.ext30.fa.pass.fa.dusted.cln.cln': No such file or directory
cp: cannot stat 'Nasik_red.fa.mod.TIR.ext30.fa.pass.fa.dusted.cln.cln.list': No such file or directory
cp: cannot stat 'Nasik_red.fa.mod.TIR.intact.raw.fa.anno.list': No such file or directory
Can't open ./TIR-Learner-Result/TIR-Learner_FinalAnn.gff3: No such file or directory.
ERROR: No such file or directory at /work/home/acn95ttd5d/software/EDTA/bin/output_by_list.pl line 39.
Error: TIR results not found!`

Could you please give me some advice on how to fix it.

Thank you!
pengzheng.

**Comment by oushujun** [comment]
hello, please try out the v2.2.2 on conda. Please reopen the issue if you still have problems. - Shujun
