### ISSUE TITLE
TIR learner breaks despite --force=1

### ISSUE THREAD

**Issue by katieemelianova** [oushujun/EDTA#534]
Hi there,

I am trying to run EDTA v2.2.2 on a number of genomes using the same process, however some of the genomes result in an error with TIR learner. 

My command:

```
EDTA.pl --threads 32 --cds $cds --genome $genome --repeatmasker /lisc/app/repeatmasker/4.1.7-p1-3.12.7-5.40.0/RepeatMasker --repeatmodeler /lisc/app/repeatmodeler/2.0.6-4.1.7-p1-3.12.7-5.40.0-1.0.7/RepeatModeler  --force 1 --anno 1
```

And the error I get:
```
Traceback (most recent call last):
  File "/lisc/app/conda/miniforge3/envs/edta-2.2.2/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/lisc/app/conda/miniforge3/envs/edta-2.2.2/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/lisc/app/conda/miniforge3/envs/edta-2.2.2/lib/python3.12/multiprocessing/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/lisc/app/conda/miniforge3/envs/edta-2.2.2/lib/python3.12/multiprocessing/queues.py", line 399, in put
    self._writer.send_bytes(obj)
  File "/lisc/app/conda/miniforge3/envs/edta-2.2.2/lib/python3.12/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/lisc/app/conda/miniforge3/envs/edta-2.2.2/lib/python3.12/multiprocessing/connection.py", line 420, in _send_bytes
    self._send(header)
  File "/lisc/app/conda/miniforge3/envs/edta-2.2.2/lib/python3.12/multiprocessing/connection.py", line 384, in _send
    n = write(self._handle, buf)
        ^^^^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
Can't open ./TIR-Learner-Result/TIR-Learner_FinalAnn.fa: No such file or directory at /lisc/app/conda/miniforge3/envs/edta-2.2.2/bin/bin/rename_tirlearner.pl line 19.
Warning: LOC list yahouensis.fasta.mod.TIR.ext30.list is empty.

Error: Error while loading sequence
Filter sequence based on TEsorter classifications. Unclassified sequences will also be output to the clean file.
        Usage: perl cleanup_misclas.pl sequence.fa.rexdb.cls.tsv
        Author: Shujun Ou (shujun.ou.1@gmail.com) 10/11/2019
        
mv: cannot stat 'yahouensis.fasta.mod.TIR.ext30.fa.pass.fa.dusted.cln.cln': No such file or directory
cp: cannot stat 'yahouensis.fasta.mod.TIR.ext30.fa.pass.fa.dusted.cln.cln.list': No such file or directory
cp: cannot stat 'yahouensis.fasta.mod.TIR.intact.raw.fa.anno.list': No such file or directory
Can't open ./TIR-Learner-Result/TIR-Learner_FinalAnn.gff3: No such file or directory.
ERROR: No such file or directory at /lisc/app/conda/miniforge3/envs/edta-2.2.2/bin/bin/output_by_list.pl line 39.
Error: TIR results not found!
```

I have used the same command on related genomes but have had no problems despite having to use --force 1 due to a lack of TIR candidates. Can you suggest what could be happening?

Best,

Katie

**Comment by oushujun** [comment]
Hi Kaite,

Please reinstall EDTA2.2.2 because of the recent update of TIR-Learner 3.0.5. This issue should be fixed. Thanks!

Shujun
