### ISSUE TITLE
TEsorter issue

### ISSUE THREAD

**Issue by cai1991** [oushujun/EDTA#54]
Dear Shujun,

Thanks for developing EDTA. It's really helpful.
I am now running this pipeline for my genome but encounter an error:

2020-02-05 19:50:18,695 -INFO- generating gene anntations
Traceback (most recent call last):
  File "/media/bulk_01/users/cai020/software/miniconda3/envs/EDTA/bin/TEsorter", line 10, in <module>
    sys.exit(main())
  File "/media/bulk_01/users/cai020/software/miniconda3/envs/EDTA/lib/python3.6/site-packages/TEsorter/app.py", line 976, in main
    pipeline(Args())
  File "/media/bulk_01/users/cai020/software/miniconda3/envs/EDTA/lib/python3.6/site-packages/TEsorter/app.py", line 171, in pipeline
    for rc in Classifier(gff, db=args.hmm_database, fout=fc):
  File "/media/bulk_01/users/cai020/software/miniconda3/envs/EDTA/lib/python3.6/site-packages/TEsorter/app.py", line 391, in classify
    for rc in self.parse():
  File "/media/bulk_01/users/cai020/software/miniconda3/envs/EDTA/lib/python3.6/site-packages/TEsorter/app.py", line 380, in parse
    line = LTRgffLine(line)
  File "/media/bulk_01/users/cai020/software/miniconda3/envs/EDTA/lib/python3.6/site-packages/TEsorter/app.py", line 609, in __init__
    super(LTRgffLine, self).__init__(line)
  File "/media/bulk_01/users/cai020/software/miniconda3/envs/EDTA/lib/python3.6/site-packages/TEsorter/app.py", line 604, in __init__
    self.attributes = self.parse(self.attributes)
  File "/media/bulk_01/users/cai020/software/miniconda3/envs/EDTA/lib/python3.6/site-packages/TEsorter/app.py", line 606, in parse
    return dict(kv.split('=') for kv in attributes.split(';'))
ValueError: dictionary update sequence element #0 has length 3; 2 is required
Warning...unknown stuff <
>

my command line is below: (EDTA v1.7.9)
`EDTA.pl -genome $genome -species others -step all -overwrite 0 -cds $cds -sensitive 0 -anno 1 -evaluate 1 -threads $thread -repeatmasker $repeatMasker`

I checked your code and guess this might be caused by cleanup CDS with TEsorter, but not sure. I already generate $genome.mod.MAKER.masked, $genome.mod.EDTA.TEanno.gff/sum results. Now evaluating the level of inconsistency is running.
Could you please help me figure it out? Thank you very much in advance.

Best regards,
Chengcheng

**Comment by oushujun** [comment]
Hi Chengcheng,

First of, parametets should be specified with two dashes "--", a slight
change from the original version. For the TEsorter error, I am not sure...
Maybe you want to run TEsorter independently to see if it works normally.

Shujun

**Comment by cai1991** [comment]
Thanks for your fast reply. I installed the latest version of EDTA but didn't change the script of v1.7.3. I will try more.

Best regards,
Chengcheng

**Comment by oushujun** [comment]
I see. You also need to update the script. After conda installation you can
call the program directly from ENV.

Shujun
