### ISSUE TITLE
Error with EDTA_raw.pl type TIR

### ISSUE THREAD

**Issue by KristinaGagalova** [oushujun/EDTA#75]
Hi,
I have the following error in RunGRF.py
```
Fri Mar 20 12:07:28 PDT 2020    EDTA_raw: Check dependencies, prepare working directories.

Fri Mar 20 12:07:52 PDT 2020    Start to find TIR candidates.

Fri Mar 20 12:07:52 PDT 2020    Identify TIR candidates from scratch.

Species: others
Traceback (most recent call last):
  File "/home/kgagalova/src/EDTA/bin/TIR-Learner2.4/Module2/RunGRF.py", line 79, in <module>
    if (len(str(records[0].seq))>int(length)+500):
IndexError: list index out of range
```
Do you have any suggestions on what can that be?

**Comment by KristinaGagalova** [comment]
This is the full error messsage
```
nohup: ignoring input
Fri Mar 20 12:07:28 PDT 2020	EDTA_raw: Check dependencies, prepare working directories.

Fri Mar 20 12:07:52 PDT 2020	Start to find TIR candidates.

Fri Mar 20 12:07:52 PDT 2020	Identify TIR candidates from scratch.

Species: others
Traceback (most recent call last):
  File "/home/kgagalova/src/EDTA/bin/TIR-Learner2.4/Module2/RunGRF.py", line 79, in <module>
    if (len(str(records[0].seq))>int(length)+500):
IndexError: list index out of range
cp: cannot stat ‘TIR-Learner/*-p’: No such file or directory
cat: *-+-DTA.fa: No such file or directory
cat: *-+-DTC.fa: No such file or directory
cat: *-+-DTH.fa: No such file or directory
cat: *-+-DTM.fa: No such file or directory
cat: *-+-DTT.fa: No such file or directory
cat: *-+-NonTIR.fa: No such file or directory
cat: *-+-*-+-*.gff3: No such file or directory
rm: cannot remove ‘*-+-*-+-*.gff3’: No such file or directory
Traceback (most recent call last):
  File "/home/kgagalova/src/EDTA/bin/TIR-Learner2.4/Module3_New/CombineAll.py", line 75, in <module>
    f_m3=removeDupinSingle("%s.gff3"%(genome_Name+spliter+"Module3"))
  File "/home/kgagalova/src/EDTA/bin/TIR-Learner2.4/Module3_New/CombineAll.py", line 57, in removeDupinSingle
    f=pd.read_csv(file,header=None,sep="\t") #shujun
  File "/home/kgagalova/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/kgagalova/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 429, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/kgagalova/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/home/kgagalova/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1122, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/kgagalova/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1853, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 545, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/projects/spruceup_scratch/dev/anaconda3/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/projects/spruceup_scratch/dev/anaconda3/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/kgagalova/src/EDTA/bin/TIR-Learner2.4/Module3/GetAllSeq.py", line 32, in GetListFromFile
    f=open(file,"r+")
FileNotFoundError: [Errno 2] No such file or directory: 'TIR-Learner_FinalAnn_filter.gff3'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kgagalova/src/EDTA/bin/TIR-Learner2.4/Module3/GetAllSeq.py", line 63, in <module>
    pool.map(GetListFromFile,fileList) #shujun
  File "/projects/spruceup_scratch/dev/anaconda3/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/projects/spruceup_scratch/dev/anaconda3/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: 'TIR-Learner_FinalAnn_filter.gff3'
mv: cannot stat ‘TIR-Learner/*FinalAnn*.gff3’: No such file or directory
mv: cannot stat ‘TIR-Learner/*FinalAnn*.fa’: No such file or directory
Can't open ./TIR-Learner-Result/TIR-Learner_FinalAnn.fa: No such file or directory at /home/kgagalova/src/EDTA/util/rename_tirlearner.pl line 18.
Warning: LOC list PissodesStrobi_1000plusNams.fa.mod.TIR.ext30.list is empty.

Error: Error while loading sequenceCan't open ./TIR-Learner-Result/TIR-Learner_FinalAnn.gff3: No such file or directory.
Warning: The TIR result file has 0 bp!

Fri Mar 20 20:15:21 PDT 2020	Execution of EDTA_raw.pl is finished!
```

**Comment by KristinaGagalova** [comment]
I am posting another error message here, looks like the output from the Helitron rep prediction is missing
```
########################################################
##### Extensive de-novo TE Annotator (EDTA) v1.8.2  ####
##### Shujun Ou (shujun.ou.1@gmail.com)             ####
########################################################



Sun Mar 22 10:42:49 PDT 2020	Dependency checking:
				All passed!

Sun Mar 22 10:43:12 PDT 2020	The longest sequence ID in the genome contains 166 characters, which is longer than the limit (15)
				Trying to reformat seq IDs...
				Attempt 1...
Sun Mar 22 10:43:15 PDT 2020	Seq ID conversion successful!

Sun Mar 22 10:43:15 PDT 2020	Obtain raw TE libraries using various structure-based programs: 
Sun Mar 22 10:43:15 PDT 2020	EDTA_raw: Check dependencies, prepare working directories.

Sun Mar 22 10:43:18 PDT 2020	Start to find LTR candidates.

Sun Mar 22 10:43:18 PDT 2020	Identify LTR retrotransposon candidates from scratch.

Sun Mar 22 10:59:05 PDT 2020	Finish finding LTR candidates.

Sun Mar 22 10:59:05 PDT 2020	Start to find TIR candidates.

Sun Mar 22 10:59:05 PDT 2020	Identify TIR candidates from scratch.

Species: others
/home/kgagalova/src/EDTA/bin/TIR-Learner2.4/Module3_New/CombineAll.py:128: FutureWarning: read_table is deprecated, use read_csv instead.
  f=pd.read_table(finalFile,header=None,sep="\t")
Finish finding TIR candidates.

Sun Mar 22 11:31:21 PDT 2020	Start to find Helitron candidates.

Sun Mar 22 11:31:21 PDT 2020	Identify Helitron candidates from scratch.

Sun Mar 22 12:39:31 PDT 2020	Finish finding Helitron candidates.

Sun Mar 22 12:39:31 PDT 2020	Execution of EDTA_raw.pl is finished!

Sun Mar 22 12:39:31 PDT 2020	Obtain raw TE libraries finished.
				All intact TEs found by EDTA: 
					GCF_003254395.2_Amel_HAv3.1_genomic.fna.mod.EDTA.intact.fa
					GCF_003254395.2_Amel_HAv3.1_genomic.fna.mod.EDTA.intact.gff

Sun Mar 22 12:39:31 PDT 2020	Perform EDTA advcance filtering for raw TE candidates and generate the stage 1 library: 


	Input file "GCF_003254395.2_Amel_HAv3.1_genomic.fna.mod.TIR.Helitron.fa.stg1.raw.masked" not found!


        Usage: perl cleanup_tandem.pl -f sample.fa [options] > sample.cln.fa 
	Options:
		-misschar	[n|l]	Define the letter representing unknown sequences; default: n. l: recognize lower case letters
		-Nscreen	[0|1]	Enable (1) or disable (0) the -nc parameter; default: 1
		-nc		[int]	Ambuguous sequence len cutoff; discard the entire sequence if > this number; default: 0
		-nr		[0-1]	Ambuguous sequence percentage cutoff; discard the entire sequence if > this number; default: 1
		-minlen		[int]	Minimum sequence length filter after clean up; default: 100 (bp)
		-maxlen		[int]	Maximum sequence length filter after clean up; default: 25000 (bp)
		-cleanN		[0|1]	Retain (0) or remove (1) the -misschar taget in output sequence; default: 0
		-cleanT		[0|1]	Remove entire seq. if any terminal seq (20bp) has 15bp of N (1); disabled by default (0).
		-minrm		[int]	The minimum length of -misschar to be removed if -cleanN 1; default: 1.
		-trf		[0|1]	Enable (1) or disable (0) tandem repeat finder (trf); default: 1
		-trf_path	path	Path to the trf program
        

ERROR: Input sequence file is not exist!


Iteratively clean up nested TE insertions and remove redundancy.

Further info:
	Each sequence will be used as query to search the entire file.
	For a subject sequence containing >95% of the query sequence, the matching part in the subject will be removed.
	After removal, subject sequences shorter than the threadshold will be diacarded.
	The number of rounds of iterations is automatically decided (usually less than 8). User can also define this.

Usage:
perl cleanup_nested.pl -in file.fasta [options]
	-in	[file]	Input sequence file in FASTA format
	-cov	[float]	Minimum coverage of the query sequence to be considered as nesting. Default: 0.95
	-minlen	[int]	Minimum length of the clean sequence to retain. Default: 80 (bp)
	-miniden	[int]	Minimum identity of the clean sequence to retain. Default: 80 (%)
	-iter	[int]	Numbers of iteration to remove redundency. Default: automatic
	-blastplus [path]	Path to the blastn and makeblastdb program.
	-threads|-t	[int]	Threads to run this script. Default: 4

cat: GCF_003254395.2_Amel_HAv3.1_genomic.fna.mod.TIR.Helitron.fa.stg1.raw.cln.cln: No such file or directory
Sun Mar 22 12:41:15 PDT 2020	EDTA advcance filtering finished.

Sun Mar 22 12:41:15 PDT 2020	Perform EDTA final steps to generate a non-redundant comprehensive TE library:

				Use RepeatModeler to identify any remaining TEs that are missed by structure-based methods.
```

Can this be connected to the deprecated function?

**Comment by oushujun** [comment]
Hi Kristina,

From the last update seems like you have finished the TIR raw run. Please check the `GCF_003254395.2_Amel_HAv3.1_genomic.fna.mod.EDTA.raw` folder to see if raw files for TIRs exist or not.

For the Helitron error, please check if the file `GCF_003254395.2_Amel_HAv3.1_genomic.fna.mod.TIR.Helitron.fa.stg1.raw` in the folder `GCF_003254395.2_Amel_HAv3.1_genomic.fna.mod.EDTA.combine` exist or not.

Best,
Shujun

**Comment by KristinaGagalova** [comment]
Hi Shujun, 
About the TIR error. The directory has been created but all the files are empty
```
(base) -bash-4.2$ ll PissodesStrobi_1000plusNams.fa.mod.EDTA.raw/
total 22652
drwxr-sr-x 2 kgagalova btl    1797 Mar 21 00:37 Helitron
drwxr-sr-x 2 kgagalova btl    1286 Mar 20 14:12 LTR
-rw-r--r-- 1 kgagalova btl  988542 Mar 21 00:37 PissodesStrobi_1000plusNams.fa.mod.Helitron.intact.fa
-rw-r--r-- 1 kgagalova btl    5944 Mar 21 00:37 PissodesStrobi_1000plusNams.fa.mod.Helitron.intact.fa.gff
-rw-r--r-- 1 kgagalova btl  988542 Mar 21 00:37 PissodesStrobi_1000plusNams.fa.mod.Helitron.raw.fa
-rw-r--r-- 1 kgagalova btl 9835163 Mar 20 14:12 PissodesStrobi_1000plusNams.fa.mod.LTR.intact.fa
-rw-r--r-- 1 kgagalova btl 3360405 Mar 20 14:12 PissodesStrobi_1000plusNams.fa.mod.LTR.intact.fa.gff3
-rw-r--r-- 1 kgagalova btl 4588477 Mar 20 14:12 PissodesStrobi_1000plusNams.fa.mod.LTR.raw.fa
-rw-r--r-- 1 kgagalova btl       0 Mar 22 00:17 PissodesStrobi_1000plusNams.fa.mod.TIR.intact.fa
-rw-r--r-- 1 kgagalova btl       0 Mar 22 00:17 PissodesStrobi_1000plusNams.fa.mod.TIR.intact.fa.gff
-rw-r--r-- 1 kgagalova btl       0 Mar 22 00:17 PissodesStrobi_1000plusNams.fa.mod.TIR.raw.fa
drwxr-sr-x 4 kgagalova btl     991 Mar 22 00:17 TIR
(base) -bash-4.2$ ll PissodesStrobi_1000plusNams.fa.mod.EDTA.raw/TIR/
total 48
drwxr-sr-x 5 kgagalova btl 87 Mar 22 00:16 Module3_New
lrwxrwxrwx 1 kgagalova btl 40 Mar 20 11:58 PissodesStrobi_1000plusNams.fa.mod -> ../../PissodesStrobi_1000plusNams.fa.mod
-rw-r--r-- 1 kgagalova btl  0 Mar 22 00:16 PissodesStrobi_1000plusNams.fa.mod.TIR
-rw-r--r-- 1 kgagalova btl  0 Mar 22 00:17 PissodesStrobi_1000plusNams.fa.mod.TIR.ext30.fa
-rw-r--r-- 1 kgagalova btl 93 Mar 22 00:17 PissodesStrobi_1000plusNams.fa.mod.TIR.ext30.fa.cov0.9iden90.tabout
-rw-r--r-- 1 kgagalova btl  0 Mar 22 00:17 PissodesStrobi_1000plusNams.fa.mod.TIR.ext30.fa.pass.fa
-rw-r--r-- 1 kgagalova btl  0 Mar 22 00:17 PissodesStrobi_1000plusNams.fa.mod.TIR.ext30.fa.pass.fa.dusted
-rw-r--r-- 1 kgagalova btl  0 Mar 22 00:17 PissodesStrobi_1000plusNams.fa.mod.TIR.ext30.fa.pass.fa.dusted.cleanup
-rw-r--r-- 1 kgagalova btl  0 Mar 22 00:17 PissodesStrobi_1000plusNams.fa.mod.TIR.ext30.fa.pass.fa.dusted.cln
-rw-r--r-- 1 kgagalova btl  0 Mar 22 00:17 PissodesStrobi_1000plusNams.fa.mod.TIR.ext30.fa.pass.fa.ori
-rw-r--r-- 1 kgagalova btl  0 Mar 22 00:16 PissodesStrobi_1000plusNams.fa.mod.TIR.ext30.list
-rw-r--r-- 1 kgagalova btl  0 Mar 22 00:17 PissodesStrobi_1000plusNams.fa.mod.TIR.intact.fa
-rw-r--r-- 1 kgagalova btl  0 Mar 22 00:17 PissodesStrobi_1000plusNams.fa.mod.TIR.intact.fa.gff
-rw-r--r-- 1 kgagalova btl  0 Mar 22 00:17 PissodesStrobi_1000plusNams.fa.mod.TIR.raw.fa
drwxr-sr-x 2 kgagalova btl  0 Mar 20 19:41 TIR-Learner-Result
```
Regarding the Helitron results
The find is not found, this is the rest of the error message
```
Sun Mar 22 12:39:31 PDT 2020	Perform EDTA advcance filtering for raw TE candidates and generate the stage 1 library: 


	Input file "GCF_003254395.2_Amel_HAv3.1_genomic.fna.mod.TIR.Helitron.fa.stg1.raw.masked" not found!


        Usage: perl cleanup_tandem.pl -f sample.fa [options] > sample.cln.fa 
	Options:
		-misschar	[n|l]	Define the letter representing unknown sequences; default: n. l: recognize lower case letters
		-Nscreen	[0|1]	Enable (1) or disable (0) the -nc parameter; default: 1
		-nc		[int]	Ambuguous sequence len cutoff; discard the entire sequence if > this number; default: 0
		-nr		[0-1]	Ambuguous sequence percentage cutoff; discard the entire sequence if > this number; default: 1
		-minlen		[int]	Minimum sequence length filter after clean up; default: 100 (bp)
		-maxlen		[int]	Maximum sequence length filter after clean up; default: 25000 (bp)
		-cleanN		[0|1]	Retain (0) or remove (1) the -misschar taget in output sequence; default: 0
		-cleanT		[0|1]	Remove entire seq. if any terminal seq (20bp) has 15bp of N (1); disabled by default (0).
		-minrm		[int]	The minimum length of -misschar to be removed if -cleanN 1; default: 1.
		-trf		[0|1]	Enable (1) or disable (0) tandem repeat finder (trf); default: 1
		-trf_path	path	Path to the trf program
        

ERROR: Input sequence file is not exist!


Iteratively clean up nested TE insertions and remove redundancy.

Further info:
	Each sequence will be used as query to search the entire file.
	For a subject sequence containing >95% of the query sequence, the matching part in the subject will be removed.
	After removal, subject sequences shorter than the threadshold will be diacarded.
	The number of rounds of iterations is automatically decided (usually less than 8). User can also define this.

Usage:
perl cleanup_nested.pl -in file.fasta [options]
	-in	[file]	Input sequence file in FASTA format
	-cov	[float]	Minimum coverage of the query sequence to be considered as nesting. Default: 0.95
	-minlen	[int]	Minimum length of the clean sequence to retain. Default: 80 (bp)
	-miniden	[int]	Minimum identity of the clean sequence to retain. Default: 80 (%)
	-iter	[int]	Numbers of iteration to remove redundency. Default: automatic
	-blastplus [path]	Path to the blastn and makeblastdb program.
	-threads|-t	[int]	Threads to run this script. Default: 4

cat: GCF_003254395.2_Amel_HAv3.1_genomic.fna.mod.TIR.Helitron.fa.stg1.raw.cln.cln: No such file or directory
Sun Mar 22 12:41:15 PDT 2020	EDTA advcance filtering finished.

Sun Mar 22 12:41:15 PDT 2020	Perform EDTA final steps to generate a non-redundant comprehensive TE library:

				Use RepeatModeler to identify any remaining TEs that are missed by structure-based methods.


Input not found!
perl rename_RM_TE.pl RM_*/consensi.fa.classified > RepeatModeler.TE.raw.fa at /home/kgagalova/src/EDTA/util/rename_RM_TE.pl line 17.
				RepeatModeler is finished, but no consensi.fa.classified files found.

				Skipping the CDS cleaning step (-cds [File]) since no CDS file is provided or it's empty.

Mon Mar 23 08:34:54 PDT 2020	EDTA final stage finished! You may check out:
				The final EDTA TE library: GCF_003254395.2_Amel_HAv3.1_genomic.fna.mod.EDTA.TElib.fa
Mon Mar 23 08:34:54 PDT 2020	Perform post-EDTA analysis for whole-genome annotation:

Mon Mar 23 08:34:54 PDT 2020	Homology-based annotation of TEs using GCF_003254395.2_Amel_HAv3.1_genomic.fna.mod.EDTA.TElib.fa from scratch.

Mon Mar 23 08:44:44 PDT 2020	TE annotation using the EDTA library has finished! Check out:
				Whole-genome TE annotation (total TE: 0.48%): GCF_003254395.2_Amel_HAv3.1_genomic.fna.mod.EDTA.TEanno.gff
				Whole-genome TE annotation summary: GCF_003254395.2_Amel_HAv3.1_genomic.fna.mod.EDTA.TEanno.sum
				Low-threshold TE masking for MAKER gene annotation (masked: 0.64%): GCF_003254395.2_Amel_HAv3.1_genomic.fna.mod.MAKER.masked

Mon Mar 23 08:44:45 PDT 2020	Evaluate the level of inconsistency for whole-genome TE annotation (slow step):

Mon Mar 23 08:46:32 PDT 2020	Evaluation of TE annotation finished! Check out these files:

				Overall: GCF_003254395.2_Amel_HAv3.1_genomic.fna.mod.EDTA.TE.fa.stat.all.sum
				Nested: GCF_003254395.2_Amel_HAv3.1_genomic.fna.mod.EDTA.TE.fa.stat.nested.sum
				Non-nested: GCF_003254395.2_Amel_HAv3.1_genomic.fna.mod.EDTA.TE.fa.stat.redun.sum
```

**Comment by oushujun** [comment]
You may want to reinstall EDTA and rerun those steps with empty raw files.

Shujun

**Comment by KristinaGagalova** [comment]
I have the following version which I installed with Conda
```
########################################################
##### Extensive de-novo TE Annotator (EDTA) v1.8.2  ####
##### Shujun Ou (shujun.ou.1@gmail.com)             ####
########################################################
```
and I did few runs that were successful which is weird. Do you recommend any update for the underlying software?

**Comment by oushujun** [comment]
This is wierd. You may try but I am not sure.

Shujun

**Comment by KristinaGagalova** [comment]
Could be possible that there are no Helitrons or TIR repeats detected in the genome?

**Comment by oushujun** [comment]
This is possible. You know more about this genome than me. If you believe so, you can use `--force 1` to overwrite the missing of TIRs and Helitrons in this genome.

Shujun

**Comment by KristinaGagalova** [comment]
I don't know if that's useful (just proposing!) but why don't you add a check for the 3 classes of repeats that you are annotating, to see if  those were at all find into the genome?
Genomes are quite diverse and sometimes we don't know if a class is actually present or not.

**Comment by oushujun** [comment]
This is a good point and actually still a bit difficult to do. Because the program is not stabilized to be 100% executable in all platforms and HPCs, so it's a bit tricky to tell if a failed run is due to the program itself or the lack of some categories. Plus the current strategy to overcome the lack of certain TE class is to use the rice TE to trick the program, which may not favored by all users. So I left this point to the users, both promote their awareness of lacking certain TEs and let them decide whether to proceed with the trick.

**Comment by oushujun** [comment]
I will add more information when they have the error, which may alleviate some of the confusion and provide suggestions.

**Comment by KristinaGagalova** [comment]
Awesome @oushujun !

**Comment by oushujun** [comment]
Considered resolved. Please reopen this thread if necessary.

**Comment by philippbayer** [comment]
I'm now running into the same issue:

```
Mon Dec  7 11:40:52 AWST 2020   Identify TIR candidates from scratch.

Species: others
Traceback (most recent call last):
  File "/scratch/pawsey0149/pbayer/soybean_pan_nlr/EDTA/bin/TIR-Learner2.5/Module2/RunGRF.py", line 79, in <module>
    if (len(str(records[0].seq))>int(length)+500):
IndexError: list index out of range
```

almost immediately when it starts the TIR step. I'm running the almost-latest version from github:

```
commit 90eed595069734d6f79b5b264fcd04163ac55667
Author: Shujun Ou <shujun.ou.1@gmail.com>
Date:   Tue Dec 1 21:29:45 2020 +0800

    Update README.md
```

using the EDTA Singularity image v1.9.4 in my own overlay filesystem

<pre>
singularity pull EDTA.sif docker://quay.io/biocontainers/edta:1.9.4--0

singularity exec docker://library/ubuntu:18.04 bash -c " \
  mkdir -p overlay_tmp/upper && \
  dd if=/dev/zero of=my_overlay count=40000 bs=1M && \
  mkfs.ext3 -d overlay_tmp my_overlay && \
  rm -rf overlay_tmp \
  "
singularity exec --overlay `pwd`/my_overlay  EDTA.sif mkdir  /files

singularity exec --overlay `pwd`/my_overlay  EDTA.sif cp Brassica_v2.1_plus_bolepan.1kbp.fasta  /files

singularity exec --overlay `pwd`/my_overlay ../EDTA.sif bash -c 'cd /files && /scratch/pawsey0149/pbayer/soybean_pan_nlr/EDTA/EDTA.pl --genome ./Brassica_v2.1_plus_bolepan.1kbp.fasta'
</pre>

I think this is specific to the reference, because I am simultaneously running other EDTA runs for other assemblies and they've progressed much further in the TIR step (those run out of walltime instead.... while this run crashes almost immediately. The LTR step finished successfully.)

All I've tried is to remove smaller contigs < 1kbp, I'll next try removing <2kbp or <3kbp and see whether that makes a difference. The uploaded file has contigs >1kbp in length. This is *Brassica oleracea* so there are definitely TIRs in there. It runs and works at the same time for *Brassica napus*. 

I'll amend this post with a link to the reference once it has finished uploading.

**Comment by philippbayer** [comment]
Oh I think writing this post helped me fix it.

The reference file had an empty line at the end! So when I looked at the TIR-Learner Contig-names.txt file, the very last line was empty too, it somehow treated that empty line as its own contig without a name. However I don't understand how this line `records=list(SeqIO.parse(file,"fasta"))` then works? It should crash saying '' or '\n' is not a file.

So yeah, deleting the empty line seems to have fixed this issue for me.

**Comment by oushujun** [comment]
Did you mean the solution was on a wrong file or the `IndexError: list index out of range` issue is due to a wrong file?

BTW, the overlay seems interesting. Did you use the github version on the singularity container in this way?

**Comment by philippbayer** [comment]
The solution was on the wrong file :) I am still getting the same error. I'm looking at the runGRF code now

Yes to use the github EDTA you don't need to use the overlay FS, I use it because our cluster doesn't allow for more than a million files to exist at the same time and EDTA makes a few hundred thousand files, which is a bit problematic when you have six EDTA runs at the same time. I wrote a mini-tutorial here: https://gist.github.com/philippbayer/aacf8f32825f917e0b81785906f36754

**Comment by oushujun** [comment]
I checked the code, the error `IndexError: list index out of range` should be referring to that `records[0]` does not exist. Something may be wrong with the input.

**Comment by philippbayer** [comment]
Found it, the file that makes it crash is, TIR-Learner-+-2399.fasta which an empty file with one empty line. I'll try to see where it comes from, I'm still thinking it's a broken contig somewhere. That folder has 29,155 files out of which 3,409 are empty! That's heaps, it can't just be one broken contig. 

While I'm investigating where those 3,409 files are coming from I'm rerunning EDTA with this change in RunGRF.py:

80     for file in files:
81         if os.stat(file).st_size == 0:
82             continue
83         records=list(SeqIO.parse(file,"fasta"))

**Comment by philippbayer** [comment]
If you want to reproduce the error, here's the reference I use https://cloudstor.aarnet.edu.au/plus/s/XHmN4dTNxU5ikt1

**Comment by philippbayer** [comment]
OK this is definitely due to weird scaffold/contig names. Shortening the contig IIs lets TIR run through!

For this particular assembly, @oushujun's one-liner of `perl -nle '$_=(split)[0]; s/jcf718000([0-9]+)_(...).*/${2}_$1/; print $_' ` fixed it, but for other assemblies I replaced the contig names by a number starting from 1, that works too.
