### ISSUE TITLE
TIR learner error - sh: /usr/bin/cat: Argument list too long 

### ISSUE THREAD

**Issue by KristinaGagalova** [oushujun/EDTA#78]
Hi, 
I have the following error during the TIR-learner. Looks like the "cat" command can't handle the list length.

```
Tue Mar 31 09:58:36 PDT 2020	EDTA_raw: Check dependencies, prepare working directories.

Tue Mar 31 09:59:18 PDT 2020	The longest sequence ID in the genome contains 140 characters, which is longer than the limit (15)
				Trying to reformat seq IDs...
				Attempt 1...
Tue Mar 31 09:59:33 PDT 2020	Seq ID conversion successful!

Tue Mar 31 09:59:34 PDT 2020	Start to find TIR candidates.

Tue Mar 31 09:59:34 PDT 2020	Identify TIR candidates from scratch.

Species: others
sh: /usr/bin/cat: Argument list too long
sh: /usr/bin/cat: Argument list too long
sh: /usr/bin/cat: Argument list too long
sh: /usr/bin/cat: Argument list too long
sh: /usr/bin/cat: Argument list too long
sh: /usr/bin/cat: Argument list too long
cat: *-+-*-+-*.gff3: No such file or directory
rm: cannot remove ‘*-+-*-+-*.gff3’: No such file or directory
Traceback (most recent call last):
  File "/home/kgagalova/src/EDTA/bin/TIR-Learner2.4/Module3_New/CombineAll.py", line 75, in <module>
    f_m3=removeDupinSingle("%s.gff3"%(genome_Name+spliter+"Module3"))
  File "/home/kgagalova/src/EDTA/bin/TIR-Learner2.4/Module3_New/CombineAll.py", line 57, in removeDupinSingle
    f=pd.read_csv(file,header=None,sep="\t") #shujun
  File "/home/kgagalova/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/kgagalova/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 429, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/kgagalova/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/home/kgagalova/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1122, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/kgagalova/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1853, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 545, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/projects/spruceup_scratch/dev/anaconda3/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/projects/spruceup_scratch/dev/anaconda3/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/kgagalova/src/EDTA/bin/TIR-Learner2.4/Module3/GetAllSeq.py", line 32, in GetListFromFile
    f=open(file,"r+")
FileNotFoundError: [Errno 2] No such file or directory: 'TIR-Learner_FinalAnn_filter.gff3'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kgagalova/src/EDTA/bin/TIR-Learner2.4/Module3/GetAllSeq.py", line 63, in <module>
    pool.map(GetListFromFile,fileList) #shujun
  File "/projects/spruceup_scratch/dev/anaconda3/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/projects/spruceup_scratch/dev/anaconda3/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: 'TIR-Learner_FinalAnn_filter.gff3'
mv: cannot stat ‘TIR-Learner/*FinalAnn*.gff3’: No such file or directory
mv: cannot stat ‘TIR-Learner/*FinalAnn*.fa’: No such file or directory
Can't open ./TIR-Learner-Result/TIR-Learner_FinalAnn.fa: No such file or directory at /home/kgagalova/src/EDTA/util/rename_tirlearner.pl line 18.
Warning: LOC list wpw.purged-70.tigmint.arks.sealer.fa.mod.TIR.ext30.list is empty.

Error: Error while loading sequenceCan't open ./TIR-Learner-Result/TIR-Learner_FinalAnn.gff3: No such file or directory.
Warning: The TIR result file has 0 bp!

Tue Apr 14 10:11:47 PDT 2020	Execution of EDTA_raw.pl is finished!
```
Do you have any suggestions of how to fix that?
Thank you in advance

**Comment by KristinaGagalova** [comment]
Looks like an issue similar to #45

**Comment by oushujun** [comment]
Hi @KristinaGagalova,

Thanks for the report. What version of EDTA are you using? As indicated in #45, this bug should be fixed since v1.7.3.

Best,
Shujun

**Comment by KristinaGagalova** [comment]
I am using v1.8.2. Looks like a different issue than

**Comment by oushujun** [comment]
@KristinaGagalova Can you grep the lines in this file for me?
`grep cat /home/kgagalova/src/EDTA/bin/TIR-Learner2.4/TIR-Learner2.4.sh`

**Comment by KristinaGagalova** [comment]
```
-bash-4.2$ grep -in cat /home/kgagalova/src/EDTA/bin/TIR-Learner2.4/TIR-Learner2.4.sh
119:#cat $dir/Module1/$genomeName/*-select.csv > test.select.csv
120:for i in $dir/Module1/$genomeName/*-select.csv; do cat $i; done > test.select.csv
```

**Comment by oushujun** [comment]
Looks normal on my end. You may want to list these files and see what's happening:
`ls -l genome.fa.mod.EDTA.raw/TIR/Module1/TIR-Learner/*-select.csv`

**Comment by KristinaGagalova** [comment]
I don't have the Module1 directory. Is that expected?

This is what I have in the TIR dir:
```
drwxr-sr-x 5 kgagalova btl 87 Apr 14 10:11 Module3_New
drwxr-sr-x 2 kgagalova btl  0 Apr 14 10:11 TIR-Learner-Result
lrwxrwxrwx 1 kgagalova btl 46 Mar 31 09:59 wpw.purged-70.tigmint.arks.sealer.fa.mod -> ../../wpw.purged-70.tigmint.arks.sealer.fa.mod
-rw-r--r-- 1 kgagalova btl  0 Apr 14 10:11 wpw.purged-70.tigmint.arks.sealer.fa.mod.TIR
-rw-r--r-- 1 kgagalova btl  0 Apr 14 10:11 wpw.purged-70.tigmint.arks.sealer.fa.mod.TIR.ext30.fa
-rw-r--r-- 1 kgagalova btl 93 Apr 14 10:11 wpw.purged-70.tigmint.arks.sealer.fa.mod.TIR.ext30.fa.cov0.9iden90.tabout
-rw-r--r-- 1 kgagalova btl  0 Apr 14 10:11 wpw.purged-70.tigmint.arks.sealer.fa.mod.TIR.ext30.fa.pass.fa
-rw-r--r-- 1 kgagalova btl  0 Apr 14 10:11 wpw.purged-70.tigmint.arks.sealer.fa.mod.TIR.ext30.fa.pass.fa.dusted
-rw-r--r-- 1 kgagalova btl  0 Apr 14 10:11 wpw.purged-70.tigmint.arks.sealer.fa.mod.TIR.ext30.fa.pass.fa.dusted.cleanup
-rw-r--r-- 1 kgagalova btl  0 Apr 14 10:11 wpw.purged-70.tigmint.arks.sealer.fa.mod.TIR.ext30.fa.pass.fa.dusted.cln
-rw-r--r-- 1 kgagalova btl  0 Apr 14 10:11 wpw.purged-70.tigmint.arks.sealer.fa.mod.TIR.ext30.fa.pass.fa.ori
-rw-r--r-- 1 kgagalova btl  0 Apr 14 10:11 wpw.purged-70.tigmint.arks.sealer.fa.mod.TIR.ext30.list
-rw-r--r-- 1 kgagalova btl  0 Apr 14 10:11 wpw.purged-70.tigmint.arks.sealer.fa.mod.TIR.intact.fa
-rw-r--r-- 1 kgagalova btl  0 Apr 14 10:11 wpw.purged-70.tigmint.arks.sealer.fa.mod.TIR.intact.fa.gff
-rw-r--r-- 1 kgagalova btl  0 Apr 14 10:11 wpw.purged-70.tigmint.arks.sealer.fa.mod.TIR.raw.fa
```

This is inside Module3_New
```
total 416998
drwxr-sr-x 2 kgagalova btl  7569176 Apr  1 10:26 temp
drwxr-sr-x 2 kgagalova btl 56996323 Apr 14 10:10 TIR-Learner
drwxr-sr-x 2 kgagalova btl        0 Apr 14 10:11 TIR-Learner-Result
```

Is there ossible that the "cat" error has occurred to another step?

**Comment by oushujun** [comment]
Ahh, I see. This is a bug. #45 is not entirely fixed.

**Comment by oushujun** [comment]
@KristinaGagalova Please update the code and try again.

**Comment by KristinaGagalova** [comment]
@oushujun   The pipeline is now successfully finished. Just got one warning about the ```read_table``` python function. 
Thank you for fixing that!

```
(base) -bash-4.2$ cat nohup.out

########################################################
##### Extensive de-novo TE Annotator (EDTA) v1.8.4  ####
##### Shujun Ou (shujun.ou.1@gmail.com)             ####
########################################################



Tue Apr 21 22:12:03 PDT 2020	Dependency checking:
				All passed!

Tue Apr 21 22:13:12 PDT 2020	The longest sequence ID in the genome contains 142 characters, which is longer than the limit (15)
				Trying to reformat seq IDs...
				Attempt 1...
Tue Apr 21 22:13:30 PDT 2020	Seq ID conversion successful!

Tue Apr 21 22:13:31 PDT 2020	Obtain raw TE libraries using various structure-based programs: 
Tue Apr 21 22:13:31 PDT 2020	EDTA_raw: Check dependencies, prepare working directories.

Tue Apr 21 22:14:03 PDT 2020	Start to find LTR candidates.

Tue Apr 21 22:14:03 PDT 2020	Identify LTR retrotransposon candidates from scratch.

Wed Apr 22 01:21:30 PDT 2020	Finish finding LTR candidates.

Wed Apr 22 01:21:30 PDT 2020	Start to find TIR candidates.

Wed Apr 22 01:21:30 PDT 2020	Identify TIR candidates from scratch.

Species: others
/home/kgagalova/src/EDTA/bin/TIR-Learner2.5/Module3_New/CombineAll.py:128: FutureWarning: read_table is deprecated, use read_csv instead.
  f=pd.read_table(finalFile,header=None,sep="\t")
Fri Apr 24 14:44:35 PDT 2020	Finish finding TIR candidates.

Fri Apr 24 14:44:35 PDT 2020	Start to find Helitron candidates.

Fri Apr 24 14:44:35 PDT 2020	Identify Helitron candidates from scratch.

Sat Apr 25 06:43:48 PDT 2020	Finish finding Helitron candidates.

Sat Apr 25 06:43:48 PDT 2020	Execution of EDTA_raw.pl is finished!

Sat Apr 25 06:43:49 PDT 2020	Obtain raw TE libraries finished.
				All intact TEs found by EDTA: 
					wpw.purged-50.tigmint.arks.sealer.fa.mod.EDTA.intact.fa
					wpw.purged-50.tigmint.arks.sealer.fa.mod.EDTA.intact.gff

Sat Apr 25 06:43:49 PDT 2020	Perform EDTA advcance filtering for raw TE candidates and generate the stage 1 library: 

Sat Apr 25 07:35:07 PDT 2020	EDTA advcance filtering finished.

Sat Apr 25 07:35:07 PDT 2020	Perform EDTA final steps to generate a non-redundant comprehensive TE library:

				Use RepeatModeler to identify any remaining TEs that are missed by structure-based methods.
```
