### ISSUE TITLE
TIR-Learner issues

### ISSUE THREAD

**Issue by niederhuth** [oushujun/EDTA#86]
Hi @oushujun,

While running EDTA on Arabidopsis, I am getting the following error during TIR finding

Fri May 29 13:55:21 EDT 2020	Identify TIR candidates from scratch.

Species: others
Traceback (most recent call last):
  File "/mnt/ufs18/home-051/niederhu/miniconda3/envs/edta/share/EDTA/bin/TIR-Learner2.4/Module3_New/getDataset.py", line 18, in <module>
    tf.logging.set_verbosity(tf.logging.ERROR)
AttributeError: module 'tensorflow' has no attribute 'logging'
cat: *-+-DTA.fa: No such file or directory
cat: *-+-DTC.fa: No such file or directory
cat: *-+-DTH.fa: No such file or directory
cat: *-+-DTM.fa: No such file or directory
cat: *-+-DTT.fa: No such file or directory
cat: *-+-NonTIR.fa: No such file or directory
cat: *-+-*-+-*.gff3: No such file or directory
rm: cannot remove ‘*-+-*-+-*.gff3’: No such file or directory
Traceback (most recent call last):
  File "/mnt/ufs18/home-051/niederhu/miniconda3/envs/edta/share/EDTA/bin/TIR-Learner2.4/Module3_New/CombineAll.py", line 75, in <module>
    f_m3=removeDupinSingle("%s.gff3"%(genome_Name+spliter+"Module3"))
  File "/mnt/ufs18/home-051/niederhu/miniconda3/envs/edta/share/EDTA/bin/TIR-Learner2.4/Module3_New/CombineAll.py", line 57, in removeDupinSingle
    f=pd.read_csv(file,header=None,sep="\t") #shujun
  File "/mnt/home/niederhu/miniconda3/envs/edta/lib/python3.7/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/mnt/home/niederhu/miniconda3/envs/edta/lib/python3.7/site-packages/pandas/io/parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/mnt/home/niederhu/miniconda3/envs/edta/lib/python3.7/site-packages/pandas/io/parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "/mnt/home/niederhu/miniconda3/envs/edta/lib/python3.7/site-packages/pandas/io/parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/mnt/home/niederhu/miniconda3/envs/edta/lib/python3.7/site-packages/pandas/io/parsers.py", line 1891, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 532, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/mnt/home/niederhu/miniconda3/envs/edta/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/mnt/home/niederhu/miniconda3/envs/edta/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/mnt/ufs18/home-051/niederhu/miniconda3/envs/edta/share/EDTA/bin/TIR-Learner2.4/Module3/GetAllSeq.py", line 32, in GetListFromFile
    f=open(file,"r+")
FileNotFoundError: [Errno 2] No such file or directory: 'TIR-Learner_FinalAnn_filter.gff3'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/ufs18/home-051/niederhu/miniconda3/envs/edta/share/EDTA/bin/TIR-Learner2.4/Module3/GetAllSeq.py", line 63, in <module>
    pool.map(GetListFromFile,fileList) #shujun
  File "/mnt/home/niederhu/miniconda3/envs/edta/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/mnt/home/niederhu/miniconda3/envs/edta/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: 'TIR-Learner_FinalAnn_filter.gff3'
mv: cannot stat ‘TIR-Learner/*FinalAnn*.gff3’: No such file or directory
mv: cannot stat ‘TIR-Learner/*FinalAnn*.fa’: No such file or directory
Can't open ./TIR-Learner-Result/TIR-Learner_FinalAnn.fa: No such file or directory at /mnt/ufs18/home-051/niederhu/miniconda3/envs/edta/share/EDTA/util/rename_tirlearner.pl line 18.
Warning: LOC list Athaliana.fa.mod.TIR.ext30.list is empty.

Error: Error while loading sequenceCan't open ./TIR-Learner-Result/TIR-Learner_FinalAnn.gff3: No such file or directory.
Warning: The TIR result file has 0 bp!

**Comment by oushujun** [comment]
The first thing you want to try is to get EDTA installed correctly. It's tricky to get all these python dependencies to work for TIR-Learner and I have mixed feedbacks - it seems easy on some machines and troublesome on the others.

You may search other issues with something like "The TIR result file has 0 bp" and you will find many similar issues and may get ideas to make it work.

If it doesn't work out, you may try the `docker/singularity` version.

Best,
Shujun

**Comment by niederhuth** [comment]
Thanks for the speedy response @oushujun 

I found that it works if I install all the older version pre-reqs through conda and then install EDTA on conda after that. 

So it must just be that some of the newer packages are just not compatible/installed correctly when I simply install EDTA and let conda automatically install the pre-reqs.
